### PR TITLE
refactor(macros): clean up declare_oxc_secret

### PR DESCRIPTION
**Pull request by DonIsaac**

### CODE REVIEW

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5937?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5938** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5938?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5937** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5937?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5906** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5906?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5937?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5938** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5938?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5937** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5937?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5906** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5906?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
I have no idea what `declare_oxc_secret` is, so can't really review this. Feel free to merge if you're happy with it.

**Comment by DonIsaac** [comment]
### Merge activity

* **Oct 16, 4:08 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
