### PR TITLE
perf(sourcemap): reduce memory copies encoding JSON

### PR DESCRIPTION
**Pull request by overlookmotel**
Reduce memory copies when encoding source map as JSON, extending approach taken in #4476 to also avoid memory copies for source texts.

I believe reason this shows no benefit on benchmarks is because our benchmarks only create a source map from a single source file, but it should result in a speed-up when there are multiple sources.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4489?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4489** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4489?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4486** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@Brooooooklyn Do you think my explanation as to why this isn't producing a visible speed-up on benchmarks is plausible?

**Comment by Brooooooklyn** [comment]
> Do you think my explanation as to why this isn't producing a visible speed-up on benchmarks is plausible?

Yes, we can try it in rolldown like: https://github.com/rolldown/rolldown/pull/1726

**Comment by Brooooooklyn** [comment]
I've done the similar approach  in the https://github.com/oxc-project/oxc/pull/4487

**Pull request merged**
