### PR TITLE
refactor(ast/visit): fire node events as the outermost one.

### PR DESCRIPTION
**Pull request by rzvxa**
I'm going to be AFK today(till about 9 PM UTC). Meanwhile, I Didn't want to be a blocker so here we go.
It would fix the #4200 merge if you guys find it in the correct order otherwise feel free to close it.

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#4203** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4203?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
@Dunqing It breaks some stuff with scoping I don't have the time right now to investigate but the generated code is in the order you've suggested. You have my permission to directly edit this branch, Stack on top of it, or close it in favor of your own.

**Comment by Dunqing** [comment]
Thank you for working on this! That's exactly what I want. I'll take care of the rest! Have a nice day.

**Review by Dunqing — APPROVED** [review]

**Comment by Boshen** [comment]
@Dunqing You may fix the conflict and merge

**Pull request merged**
