### PR TITLE
docs(README): change the website domain.

### PR DESCRIPTION
**Pull request by rzvxa**

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#3652** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
@Boshen The CI is stuck again, I don't understand why it keeps happening recently. Is it a GitHub issue or something with the protection policies put in place?

**Comment by Boshen** [comment]
> @Boshen The CI is stuck again, I don't understand why it keeps happening recently. Is it a GitHub issue or something with the protection policies put in place?

CI is skipped when markdown file are changed.

**Comment by rzvxa** [comment]
Now it makes sense😅

**Pull request merged**
