### PR TITLE
refactor(linter): simplify `eslint/radix` rule

### PR DESCRIPTION
**Pull request by overlookmotel**
Refactor to remove duplicate logic.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#5447** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5447?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5446** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5446?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5445** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5445?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@DonIsaac Boshen has requested that we always assign reviewers to PRs. So, since you're "Mr linter", I've requested you review. But let me know if I should include others as reviewers on linter PRs.

**Comment by DonIsaac** [comment]
No worries 😁 @camc314 also works on the linter. Mysteryven (who I won't tag) is moving houses and mostly unavailable right now.

**Review by DonIsaac — APPROVED** [review]

**Comment by overlookmotel** [comment]
Cool. I'll add camc314 as a reviewer too in future. Thanks for swift merging!

**Comment by camc314** [comment]
Unfortunatly, my github notification are a mess so apologies if i miss it! 😅

**Pull request merged**
