### PR TITLE
feat(linter): support shared rule state in `ctx`

### PR DESCRIPTION
**Pull request by shulaoda**
Related to #5204

### CODE REVIEW

**Comment by shulaoda** [comment]
How about this?  @Boshen 
I have tested replacing all rules in the local commit and didn't find any errors.

**Review by Boshen — COMMENTED** [review]
:thinking: I'm not sure if this is going to work, can you continue prototyping by collecting state in `run`, and then inspect the state in `run_once` moved to the end? We probably need to implement this prototype with two rules.

I'd imagine the states need to be isolated, rule A cannot read data from rule B.

**Comment by shulaoda** [comment]
Let me reconsider, it seems like it's not feasible and a bit difficult. 😩

**Comment by DonIsaac** [comment]
I've got some ideas on how to implement this. I'll take a closer look tomorrow.

**Pull request closed without merging**
