### PR TITLE
refactor(parser): remove `TokenValue::Number` from `Token`

### PR DESCRIPTION
**Pull request by Boshen**
This PR is part of #1880.

Token size is reduced from 40 to 32 bytes.

### CODE REVIEW

**Comment by Boshen** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1945** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1945?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1945?utm_source=stack-comment).

**Comment by Boshen** [comment]
Note to self: number lexing no longer requires the string builder.

**Comment by Boshen** [comment]
image

@overlookmotel 😍

**Comment by Boshen** [comment]
We can add a `OnceCell` to all the values and make them truly lazy, but we'll need to figure out the memory leak problem before doing so.

**Review by Dunqing — APPROVED** [review]

**Comment by overlookmotel** [comment]
Nice one!

**Pull request merged**
