### PR TITLE
feat(sourcemap): add `ConcatSourceMapBuilder::from_sourcemaps`

### PR DESCRIPTION
**Pull request by overlookmotel**
Introduce new method `ConcatSourceMapBuilder::from_sourcemaps`.

Where all the sourcemaps being concatenated exist at time that you create `ConcatSourceMapBuilder`, it's faster to use `from_sourcemaps`, because it pre-allocates enough space for the data it will hold and so avoids memory copying.

Before:

```rs
let mut builder = ConcatSourceMapBuilder::default();
builder.add_sourcemap(&sourcemap1, 0);
builder.add_sourcemap(&sourcemap2, 100);
builder.add_sourcemap(&sourcemap3, 100);
let combined = builder.into_sourcemap();
```

After:

```rs
let builder = ConcatSourceMapBuilder::from_sourcemaps(&[
    (&sourcemap1, 0),
    (&sourcemap2, 100),
    (&sourcemap3, 200),
]);
let combined = builder.into_sourcemap();
```

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4639?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4639** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4639?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4638** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4634** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4634?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#4635](https://github.com/oxc-project/oxc/pull/4635) <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4635?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Rolldown should use this new API `from_sourcemaps` wherever possible. Where concatenating multiple large sourcemaps, it may produce a larger speed-up than the 2% we're seeing on our benchmark.

How do we communicate that to them, given that this API won't be available until next release?

**Comment by Boshen** [comment]
> Rolldown should use this new API `from_sourcemaps` wherever possible. Where concatenating multiple large sourcemaps, it may produce a larger speed-up than the 2% we're seeing on our benchmark.
> 
> How do we communicate that to them, given that this API won't be available until next Oxc release?

We PR with the intended change in our latest release.

**Comment by Boshen** [comment]
There's only 1 usage https://github.com/rolldown/rolldown/blob/0d5d1d498332a77176e1deeaecbb235e1d526c0d/crates/rolldown_sourcemap/src/concat_sourcemap.rs#L83

```rust
  fn into_concat_source(
    &self,
    final_source: &mut String,
    sourcemap_builder: &mut Option<ConcatSourceMapBuilder>,
    line_offset: u32,
  ) {
    if let Some(sourcemap_builder) = sourcemap_builder {
      sourcemap_builder.add_sourcemap(&self.sourcemap, line_offset);
    }

    final_source.push_str(&self.content);
  }
```

**Comment by underfin** [comment]
Before i have a try same as this, see https://github.com/rolldown/rolldown/pull/1764. But the real benchmark is not improved..

**Comment by overlookmotel** [comment]
@underfin Actually, I just realised there's a better way to do this than the `from_sourcemaps` API.

Please don't move to using `from_sourcemaps` - I'll make a new PR in next few days to remove it again, and do this a different way. It may also be possible to remove a bunch of memory copying.

**Pull request merged**
