### PR TITLE
feat(ast_codegen): generate `ast_kind.rs`.

### PR DESCRIPTION
**Pull request by rzvxa**
[List of 68 blacklisted items](https://github.com/oxc-project/oxc/pull/3888/files#diff-59cbea4a1444e752992821d3429a5f27bf1027a530977d075ec89aa55995912aR11)

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3888?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3888** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3888?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3852** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3852?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3815** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3815?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3855** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3855?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
As discussed, we'll need a hard-coded whitelist/blacklist to prevent generating `AstKind` variants for types where there isn't one at present.

Personally, I think a blacklist is better than whitelist, so if a new AST type is added, we don't need to remember to add it to whitelist too.

**Comment by overlookmotel** [comment]
I'm not completely sure about this, but as far as I can see, it looks like all enums are blacklisted. If that's the case, can we make a blanket rule that no enums go in `AstKind`, and remove them all from the blacklist? Remaining blacklist might end up being quite short, which would make it more obvious how much work we have left to cut it down to 0.

**Comment by rzvxa** [comment]
> I'm not completely sure about this, but as far as I can see, it looks like all enums are blacklisted. If that's the case, can we make a blanket rule that no enums go in AstKind, and remove them all from the blacklist? Remaining blacklist might end up being quite short, which would make it more obvious how much work we have left to cut it down to 0.

Sadly that's not the case here, There are enums with an `AstKind` (`ModuleDeclaration` and `SimpleAssignmentTarget` come to mind). We can blacklist all enums and then whitelist a handful of them that are actually used, But that would raise this issue again:

> so if a new AST type is added, we don't need to remember to add it to whitelist too.

> If you wouldn't mind, could you please separate out renaming BigintLiteral into a separate PR? It makes it easier to review if unrelated changes aren't grouped into a single PR.

Done and dusted!

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
> Sadly that's not the case here

Damn! OK, the lengthy blacklist it is...

**Pull request merged**
