### PR TITLE
feat(linter): eslint-plugin-next/no-html-link-for-pages

### LINKED ISSUE #3177: linter: finish nextjs plugin
Only 1 left [no-html-link-for-pages](https://nextjs.org/docs/messages/no-html-link-for-pages), which requires `oxc_resolver` exposed to the linter rules or cache all the paths.

https://github.com/oxc-project/oxc/pull/3196

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#3196** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3196?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Dunqing** [comment]
> Are we able to provide a cached fs in `LintContext`?

I will give a try. Also perhaps we could provide some sort of generic caching policy in the LintContext. As far as I know most rules could benefit from this

**Comment by Boshen** [comment]
It seems like we don't need the resolver, we just need to walk the directories and cache the found files ...

**Comment by DonIsaac** [comment]
@Dunqing mind if I take this PR over?

**Pull request closed without merging**
