### PR TITLE
feat(ast): remove serde skip for symbol_id and reference_id

### PR DESCRIPTION
**Pull request by Dunqing**
We want to see symbol_id and reference_id in ast

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2220** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2220?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2220?utm_source=stack-comment).

**Comment by Dunqing** [comment]
cc @hyf0

**Comment by Boshen** [comment]
It failed to compile https://github.com/oxc-project/oxc/actions/runs/7707957018/job/21006084925?pr=2220

**Comment by Boshen** [comment]
"Check Unused Dependencies" failed :-(

**Pull request merged**
