### PR TITLE
feat(linter): support eslint-plugin-vitest/valid-expect

### PR DESCRIPTION
**Pull request by eryue0220**
Rule detail: [link](https://github.com/veritem/eslint-plugin-vitest/blob/main/src/rules/valid-expect.ts)

### CODE REVIEW

**Comment by mysteryven** [comment]
I made some change about `TestPluginName`, could you rebase and solve the conflicts?

**Comment by eryue0220** [comment]
> I made some change about `TestPluginName`, could you rebase and solve the conflicts?

Okay I will update later.

**Comment by eryue0220** [comment]
Done.

**Comment by mysteryven** [comment]
There are some conflicts in `crates/oxc_linter/src/utils/mod.rs`, I updated them.

**Pull request merged**
