### PR TITLE
feat(linter): add eslint-plugin-import(export) rule

### PR DESCRIPTION
**Pull request by mysteryven**

### CODE REVIEW

**Comment by mysteryven** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1654** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1654?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1654?utm_source=stack-comment).

**Review by Boshen — COMMENTED** [review]
There's many more tests to port https://github.com/import-js/eslint-plugin-import/blob/main/tests/src/rules/export.js

shall we add a TODO for this and mark this as `nursery`?

**Comment by mysteryven** [comment]
> shall we add a TODO for this and mark this as `nursery`?

I didn't know how I thought yesterday when I set to restriction,😿 I'll add this.

> There's many more tests to port [import-js/eslint-plugin-import@`main`/tests/src/rules/export.js](https://github.com/import-js/eslint-plugin-import/blob/main/tests/src/rules/export.js?rgh-link-date=2023-12-12T04%3A35%3A06Z)

I am planing to add new rulegen for eslint-import-plugin.

**Comment by mysteryven** [comment]
> shall we add a TODO for this and mark this as `nursery`?

Done.

**Review by Boshen — APPROVED** [review]

**Pull request merged**
