### PR TITLE
refactor(linter): move `run_once` to the end 

### PR DESCRIPTION
**Pull request by shulaoda**
Related to #5204

### CODE REVIEW

**Comment by Boshen** [comment]
It feels like moving `run_once` to the end should make things work.

**Comment by shulaoda** [comment]
> It feels like moving `run_once` to the end should make things work.

Good idea!

**Comment by Boshen** [comment]
We can defer merging this until we figure out how to store rule states.

**Comment by DonIsaac** [comment]
> We can defer merging this until we figure out how to store rule states.

How would you feel about a cache object for each rule stored in `LintContext`?

**Comment by Boshen** [comment]
> > We can defer merging this until we figure out how to store rule states.
> 
> How would you feel about a cache object for each rule stored in `LintContext`?

Can give this a try.

**Pull request closed without merging**
