### PR TITLE
fix(oxlint): gate custom allocators by feature flag

### PR DESCRIPTION
**Pull request by lucab**
This tweaks the conditional compilation of custom allocators by wiring the dedicated Cargo feature flag `allocator` to the source code. It ensures that allocator gating is directly checking the relevant feature instead of trying to infer it from the build profile.

### CODE REVIEW

**Comment by Boshen** [comment]
My intention was to not enable allocators in dev mode, which hurts compilation speed for first timers.

**Comment by Boshen** [comment]
@lucab Thank you for going through our code. I assume you are a very good system engineer, I'm happy to help you and get you on-boarded with this project, as we appreciate a lot of helping hands. Please DM me either on twitter or discord for some quick chats.

For more hardcore problems, you may checkout our backlog https://github.com/oxc-project/backlog/issues, there are problems like [custom arena allocator](https://github.com/oxc-project/backlog/issues/49) that may interest you.

**Comment by lucab** [comment]
Thanks for the pointers. I had a look at your backlog tracker and I'm also around on the discord server.

Unfortunately these days I don't have large uninterrupted chunks of time to dedicate to larger tasks, and I'm also often away from my usual coding environment. I'm enjoying exploring both `oxc` and `rolldown` codebases, and sending PRs for small low-hanging fruits from time to time.

**Comment by Boshen** [comment]
@lucab That's ok, feel free to raise issues or DM them if you find anything that is interesting or worth exploring, I can create some good first issues if you don't have the time to code 😁

**Pull request merged**
