### PR TITLE
feat(linter): eslint-plugin-jest/require-hook

### PR DESCRIPTION
**Pull request by eryue0220**
part of https://github.com/oxc-project/oxc/issues/492

Rule Detail: [link](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/require-hook.ts)

### CODE REVIEW

**Comment by mysteryven** [comment]
This rule is a bit strict. 😢

**Review by mysteryven — APPROVED** [review]
Nice work :)

**Comment by eryue0220** [comment]
> This rule is a bit strict. 😢

Ok, I'll update the rule style in my next pr.

**Comment by mysteryven** [comment]
> Ok, I'll update the rule style in my next pr.

It's good to keep it `style`, I wanted to express my though about this rule, I may write many codes that go against this rule:(

**Pull request merged**
