### PR TITLE
remove all unstable let chains

### PR DESCRIPTION
**Pull request by sairajchouhan**

### CODE REVIEW

**Comment by Boshen** [comment]
Oh no! we have a race! https://github.com/web-infra-dev/oxc/pull/628

**Comment by sairajchouhan** [comment]
LOL, also @Boshen, when I run `cargo fmt` it says that some of the features are also unstable.
```
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
Warning: can't set `reorder_impl_items = true`, unstable features are only available in nightly channel.
Warning: can't set `version = Two`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
```

any recommendations on how to change the `rustfmt.toml` file?

**Comment by Boshen** [comment]
> any recommendations on how to change the `rustfmt.toml` file?

try `cargo +nightly fmt`

**Comment by Boshen** [comment]
https://github.com/web-infra-dev/oxc/pull/628/files has less nested code, so I'll probably go with that one, but a great opportunity for you to learn all the syntax sugars we can write.

**Pull request closed without merging**
