### PR TITLE
perf(parser): more efficient number parsing

### PR DESCRIPTION
**Pull request by overlookmotel**
Follow-on after #3296.

Make parsing binary/octal/hex numeric literals a little more efficient.

These changes all rely on that we know more than the compiler does - that strings passed to these `parse_*` functions can only contain a certain set of characters.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#3342** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3342?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@DonIsaac Apologies for code golfing your PR! I got interested after seeing the link to Godbolt you posted in #3296, and wondered if we could push it any further.

Obviously makes little difference in real world as binary/octal/hex literals are rare in JS code, but why not? Though it might inform your approach if you're going to tackle decimal literals too, which are much more common.

I've included Godbolt links showing before/after in the code, if you're interested.

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
@overlookmotel LGTM

**Comment by overlookmotel** [comment]
Thanks for reviewing @DonIsaac. Appreciate you checking I'm not doing anything stupid!

**Pull request merged**
