### PR TITLE
chore: fix failed publish caused by cyclic dev dependencies 

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
1. This looks like caused by https://github.com/rust-lang/cargo/issues/4242

## Ref
1. https://github.com/rust-lang/futures-rs/pull/2305

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Or we could remove `version` in https://github.com/IWANABETHATGUY/oxc/blob/89e037b231f75451e7152daf6b81e649fde2bd7c/Cargo.toml#L79-L79, instead.

**Comment by Dunqing** [comment]
Do we have a way to verify this is work

**Comment by IWANABETHATGUY** [comment]
I don't know, cc  @Boshen

**Comment by IWANABETHATGUY** [comment]
Because the dev cyclic dependency still exists, you can't make sure if this works until you try to make a new release, AFAIK, this is probably the best workaround, since `future-rs` and many linked pull request also use this trick.

**Comment by Dunqing** [comment]
Still failed https://github.com/oxc-project/oxc/actions/runs/10053226875/job/27785666460

**Pull request merged**
