### PR TITLE
fix(editor/vscode): set minimum supported ver. to `^1.93.0`

### PR DESCRIPTION
**Pull request by pashokitsme**
Hi,

I'm using Cursor which is based on VSCode `1.93` at the moment of this PR. And i've faced with an issue when i can't install latest version of oxc vscode plugin - by default plugin marketplace offers me `v0.0.1` and via `Install Specific Version` i can install only `v0.10.3` while latest is `v0.15.3`. No idea when Cursor will update its version.
There's no issue with VSCode, only Cursor.

After downgrading minimum version, Cursor allowed me to install plugin that i compiled by myself, everything seem to be working.

Not sure about how is usually contributions made here so correct me if i miss something

### CODE REVIEW

**Comment by Sysix** [comment]
@nrayburn-tech 1.93 is released in [August 2024](https://code.visualstudio.com/updates/v1_93).
Only supporting the latest version does not sounds right. What do you think?

@pashokitsme thanks for the fix and the details why this is needed. 
Can you tell [renovate](https://github.com/oxc-project/oxc/blob/main/.github/renovate.json) to ignore this npm package? 

I searched the documentation for you: 
https://docs.renovatebot.com/configuration-options/#ignoredeps

**Comment by nrayburn-tech** [comment]
Unless there’s a reason for the Oxc plugin to target a more recent version, I wouldn’t update it as a general rule. That being said, to avoid supporting really old versions we could target the current version minus 6 to only support 6 months worth of VS Code releases ( 6 just being an example, we could pick whatever).

So, targeting an older version is probably fine so long as it’s not ancient. I don’t have any concerns with this change.

Something to consider when targeting an older version is you might want to run tests against the old version and the latest version to ensure you are compatible with new releases as they come out.

**Comment by camc314** [comment]
> we could target the current version minus 6 to only support 6 months worth of VS Code releases ( 6 just being an example, we could pick whatever).

:+1: this seems reasonable

**Comment by pashokitsme** [comment]
> target the current version minus 6 to only support 6 months

Don't really know how to configure renovate like this. Something like?:
```json
"packageRules": [
  {
    "matchPackagePatterns": ["@types/vscode"],
    "minimumReleaseAge": "6 months"
  }
]
```

And will renovate update not only `devDependencies`, but version in `engines` too? Feels like it won't

**Comment by camc314** [comment]
Based on the docs that looks correct.

```json
"packageRules": [
  {
    "matchPackagePatterns": ["@types/vscode"],
    "minimumReleaseAge": "6 months",
    "postUpgradeTasks": {
        "commands": [
          "jq '.engines.vscode = \"^\" + (.dependencies.vscode | ltrimstr(\"^\"))' package.json > tmp.json && mv tmp.json package.json"
        ],
        "fileFilters": ["package.json"]
    }
  }
]
```

didn't test this, but chat gpt suggests this?

**Comment by Sysix** [comment]
> But actually, perhaps we want to keep @types/vscode up to date, and simply specify an older supported version in engines?

The build will fail because it detects different versions.

> Don't really know how to configure renovate like this.

I do not think you need to fix this in this PR.

**Comment by nrayburn-tech** [comment]
I would suggest downgrade the version here. Configure renovate to ignore it for now.

Once somebody can test how to get it working correctly (update to the 6 month old version and keep engines in sync) that can be a separate PR. From the docs, I do think something like @camc314 shared should work but I don’t have experience with Renovate.

This isn’t really a critical package to keep up to date for vulnerabilities or things of that nature, so I think it’s low risk to ignore for now.

**Comment by pashokitsme** [comment]
Let's merge it then

**Comment by camc314** [comment]
lock file needs updating

**Comment by pashokitsme** [comment]
Oops. Didn't noticed. Fixed

**Pull request merged**
