### PR TITLE
refactor(cli): Runners

### LINKED ISSUE #534: Language Server Protocol

### PR DESCRIPTION
**Pull request by DonIsaac**
# What
Introduces a standardized API for interacting with different parts of `oxc` within `oxc_cli` using a trait called `Runner`.

# Why
For the following reasons:
1. Prepare `oxc_cli` for new subcommand we plan on adding (e.g. `minify`)
2. Deduplicate code within `lint`
3. Prepare to expose runners as a public API, with the intention of using it to build an LSP

# How

The `check` and `lint` commands have been updated to implement `Runner`. This exposes three pieces of functionality:
1. A method for building `clap`-compatible `Commands`
2. Creating `Runner`s using their associated `RunnerOption`s
3. Executing whatever action they implement via `run()`

### CODE REVIEW

**Comment by Boshen** [comment]
I like this.

This is going to have a huge merge conflict with my import-plugin branch, but I can merge this and rebase because this is a lot cleaner.

Do you have anything else left to do before merging?

**Comment by DonIsaac** [comment]
Not exactly. This PR can be merged as-is. However, I'm working on a language server, so I haven't fully settled on a contract yet. Those changes could be merged later though.

**Comment by Boshen** [comment]
> 

Let me know when your LSP is working and you're satisfied with the abstractions from this PR. I'll merge when things are more tested.

**Comment by DonIsaac** [comment]
@Boshen I plan on refactoring `CliRunResult` but I think we should discuss some constraints there. This can (should) be made in a following PR. As such, this PR is ready for review.

**Review by Boshen — APPROVED** [review]
Nice! The CLI is more structured now, can't wait for the other refactors!

**Pull request merged**
