### PR TITLE
(feat/tasks): refactor lint_rules for subsequent todos

### PR DESCRIPTION
**Pull request by leaysgur**
Part of #2020 

- Handle args and flags
- Split files
- Prettify CLI outputs

### CODE REVIEW

**Comment by leaysgur** [comment]
```sh
$ cargo run -p lint_rules eslint

⚠️ Rule: no-new-symbol is implemented but not in their lists.
⚠️ Rule: no-return-await is implemented but not in their lists.
⚠️ Rule: no-mixed-operators is implemented but not in their lists.
- [ ] accessor-pairs
- [x] array-callback-return
- [ ] arrow-body-style
- [ ] block-scoped-var

... ✂
```

FYI: These rules appear to be deprecated for now.

**Comment by Boshen** [comment]
> FYI: These rules appear to be deprecated for now.

Nice catch! I'll look into their deprecation reasons.

**Comment by Boshen** [comment]
For `list_implemented_rules`, you may use `RULES` instead of reading the rules.rs file

https://github.com/oxc-project/oxc/blob/b5b2ef34afaf3c81cd5ded8e52ab53bc0d24db9e/crates/oxc_linter/src/lib.rs#L36

Make `RULES` public and import it. Each rule has a `.name()` and `.plugin_name()` method.

https://github.com/oxc-project/oxc/blob/b5b2ef34afaf3c81cd5ded8e52ab53bc0d24db9e/crates/oxc_macros/src/declare_all_lint_rules/mod.rs#L79-L101

Feel free to follow this up with another PR.

---

Sorry I was in a rush yesterday so the message was unclear.

**Comment by leaysgur** [comment]
> Sorry I was in a rush yesterday so

Never mind! I'll fix it later~ 🔜

**Pull request merged**
