### PR TITLE
refactor: change jest rule's category

### PR DESCRIPTION
**Pull request by mysteryven**

### CODE REVIEW

**Comment by mysteryven** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1155** <a href="https://app.graphite.dev/github/pr/web-infra-dev/oxc/1155" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/web-infra-dev/oxc/1155?utm_source=stack-comment).

**Comment by Boshen** [comment]
You need to run `gt ss` 😅

**Comment by mysteryven** [comment]
Done, forgot to create a new branch🙃

**Comment by Boshen** [comment]
> Done, forgot to create a new branch🙃

You don't need to create branches, just `gt c` and then `gt ss`.

**Review by Boshen — APPROVED** [review]

**Pull request merged**
