### PR TITLE
feat(linter): no-empty-pattern

### PR DESCRIPTION
**Pull request by magic-akari**

### CODE REVIEW

**Comment by Boshen** [comment]
Thank you! swcの人柱力！

I'd like to get https://github.com/Boshen/oxc/pull/70 merged before merging this.

In the meanwhile, do you mind taking a quick survey?

* How's the overall experience?
* Are there anything that needs to be improved?

**Comment by magic-akari** [comment]
The experience of completing this PR was not bad, because I chose a simple one.

---

So far, I don't know how to traverse the AST.
We need an introduction to the architecture of oxc.

**Comment by Boshen** [comment]
> The experience of completing this PR was not bad, because I chose a simple one.
> 
> So far, I don't know how to traverse the AST. We need an introduction to the architecture of oxc.

We only need to go up the tree most of the time, which can be accessed through `AstNodes`, which is an indextree. Going down the tree will be a manual process. Do you need anything else?

**Comment by Boshen** [comment]
> We need an introduction to the architecture of oxc.

Will do!

**Comment by magic-akari** [comment]
> Going down the tree will be a manual process.

Does this mean that if I need to check whether a certain AST element exists in a subtree, I need to manually recurse down all paths?

Is there a visitor pattern method that can be used instead?

**Comment by Boshen** [comment]
> 

Can you give me an example where a linter rule needs this? I haven't seen one so far. We implement almost all contexts in the semantic analyzer.

But if you really need it, you can still implement the [`Visitor`](https://github.com/Boshen/oxc/blob/main/crates/oxc_ast/src/visit.rs) trait.

**Pull request merged**
