### PR TITLE
Update to ezno-checker 0.0.12

### PR DESCRIPTION
**Pull request by kaleidawave**
Work in progress.

Updates the ezno checker integration from the June release to now

### CODE REVIEW

**Comment by kaleidawave** [comment]
This branch is still is a way to go. I thought I could do it this evening but having some problems with lifetimes here:

https://github.com/oxc-project/oxc/blob/499922e6818aa03ee38f7bf94dbfcaf19b4b95b1/crates/oxc_type_synthesis/src/lib.rs#L24-L32

Will work on creating a MRE. The current synthesis API is built for the non-lifetime based AST of my own parser. As all Oxc AST has a lifetime I need to figure out how introduce the lifetimes into the existing APIs.

---

Once that has been fixed, I still need to fix up all the current `todo!()`s and add use the new API stuff

**Comment by Boshen** [comment]
> This branch is still is a way to go. I thought I could do it this evening but having some problems with lifetimes here:
> 
> https://github.com/oxc-project/oxc/blob/499922e6818aa03ee38f7bf94dbfcaf19b4b95b1/crates/oxc_type_synthesis/src/lib.rs#L24-L32
> 
> Will work on creating a MRE. The current synthesis API is built for the non-lifetime based AST of my own parser. As all Oxc AST has a lifetime I need to figure out how introduce the lifetimes into the existing APIs.
> 
> Once that has been fixed, I still need to fix up all the current `todo!()`s and add use the new API stuff

Are there any unsafe Rust hackery that could ease the pain?

**Comment by kaleidawave** [comment]
Don't think so, it is a issue with Rust traits, impls and types. Looks like a change needs to be made to  [ezno-checker](https://github.com/kaleidawave/ezno), I think all the AST associated types (apart from `OwnedModule`) need a lifetime parameter. Should compile after then, but means that existing items have to include explicit lifetimes (unfortunately doesn't look like Rust lifetime elision works here)

Here is a example of the fix: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=47a251281f532f35cd231070a548bfdb

**Comment by Boshen** [comment]
Closing due to outdated.

**Pull request closed without merging**
