### PR TITLE
fix(transformer): optional-catch-binding unused variable side effect

### PR DESCRIPTION
**Pull request by rzvxa**
Before this PR for this given case:

```javascript
const _unused = "It's a lie, They gonna use me:(";
try {
    throw 0;
} catch {
  console.log(_unused);
}
```

We would've generated this:

```javascript
const _unused = "It's a lie, They gonna use me:(";
try {
    throw 0;
} catch (_unused) {
  console.log(_unused);
}
```

This is incorrect, This PR aims to use the `CreateVars` trait in order to ensure the variable uniqueness.

Now it would output this:

```javascript
const _unused = "It's a lie, They gonna use me:(";
try {
    throw 0;
} catch (_unused2) {
  console.log(_unused);
}
```

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#2822** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2822?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Dunqing** [comment]
There are no snapshots updated?

**Comment by rzvxa** [comment]
> There are no snapshots updated?

No the tests on eslint don't consider this so it was passing anyway.

**Review by Dunqing — APPROVED** [review]

**Comment by rzvxa** [comment]
@Dunqing I can add the appropriate tests to the eslint if you find it relative to oxc.

**Comment by Dunqing** [comment]
> @Dunqing I can add the appropriate tests to the eslint if you find it relative to oxc.

I prefer to add the test here. But this is babel repo 😅 https://github.com/babel/babel/blob/f856fc22d05bf886d1a58c5c91490e1af8f90c44/packages/babel-plugin-transform-optional-catch-binding/test/fixtures/optional-catch-bindings

**Comment by rzvxa** [comment]
> I prefer to add the test here. But this is babel repo 😅 https://github.com/babel/babel/blob/f856fc22d05bf886d1a58c5c91490e1af8f90c44/packages/babel-plugin-transform-optional-catch-binding/test/fixtures/optional-catch-bindings

I agree, We may want to add our set of unit tests on top of esbuild compatibility checks. However, I would add a try-catch-shadow case there when I get the time. Even if we don't rely on it, It would be net positive.

**Pull request merged**
