### PR TITLE
chore(doc): replace main/master to tag/commit to make the url always accessible

### LINKED ISSUE #7291: [Doc] the url of some file in some repo should have a specific commit or tag rather than branch
The doc/comment is great, but I noticed that some link is like 

> //! * Babel plugin implementation: <https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-nullish-coalescing-operator>

This is potentially buggy, because main branch is always changing and maybe someday the file is gone.

It would be better if the file is associated with a commit or tag, then it's expected to always be there.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fix #7291

The match relationship is :

```
 {
    "oxc-project/oxc": "main",
    "cvazac/eslint-plugin-react-perf": "9bfa930661a23218f5460ebd39d35d76ccdb5724",
    "DefinitelyTyped/DefinitelyTyped": "b5dc32740d9b45d11cff9b025896dd333c795b39",
    "estree/estree": "e6015c4c63118634749001b1cd1c3f7a0388f16e",
    "fregante/eslint-formatters": "ae1fd9748596447d1fd09625c33d9e7ba9a3d06d",
    "javascript-compiler-hints/compiler-notations-spec": "c14f7e197cb225c9eee877143536665ce3150712",
    "mozilla-spidermonkey/jsparagus": "24004745a8ed4939fc0dc7332bfd1268ac52285f",
    "privatenumber/minification-benchmarks": "d8d54ceeb206d318fa288b152904adf715b076b2",
    "tc39/source-map": "1930e58ffabefe54038f7455759042c6e3dd590e",
    "tc39/test262": "05c45a4c430ab6fee3e0c7f0d47d8a30d8876a6d",
    "biomejs/biome": "cli/v1.9.4",
    "eslint-community/eslint-plugin-promise": "v7.1.0",
    "eslint-community/eslint-plugin-n": "v17.13.2",
    "rollup/plugins": "pluginutils-v5.1.3",
    "rome/tools": "lsp/v0.28.0",
    "A11yance/aria-query": "v5.3.2",
    "babel/babel": "v7.26.2",
    "denoland/deno_graph": "0.84.0",
    "eslint/eslint": "v9.9.1",
    "evanw/esbuild": "v0.24.0",
    "facebook/react": "v18.3.1",
    "gajus/eslint-plugin-jsdoc": "v50.5.0",
    "getsentry/rust-sourcemap": "9.1.0",
    "google/closure-compiler": "v20240609",
    "guybedford/es-module-lexer": "1.5.4",
    "import-js/eslint-plugin-import": "v2.29.1",
    "jest-community/eslint-plugin-jest": "v28.9.0",
    "jsx-eslint/eslint-plugin-jsx-a11y": "v6.9.0",
    "jsx-eslint/eslint-plugin-react": "v7.37.2",
    "Kilian/electron-to-chromium": "v1.5.60",
    "lukastaegert/eslint-plugin-tree-shaking": "v1.12.2",
    "microsoft/TypeScript": "v5.6.3",
    "nicolo-ribaudo/babel": "v7.25.8",
    "nodevault/node-vault": "v0.10.2",
    "prettier/prettier": "3.3.3",
    "ratel-rust/ratel-core": "v0.7.0",
    "rolldown-rs/rolldown": "v0.14.0",
    "rust-lang/rust": "1.82.0",
    "sindresorhus/eslint-plugin-unicorn": "v56.0.0",
    "terser/terser": "v5.9.0",
    "typescript-eslint/typescript-eslint": "v8.9.0",
    "vercel/next.js": "v15.0.2",
    "veritem/eslint-plugin-vitest": "v1.1.9",
}

```

### CODE REVIEW

**Comment by Boshen** [comment]
### Errors in ./crates/oxc_prettier/README.md

* [404] [https://github.com/prettier/prettier/tree/v3.3.3/tests/format/js](https://github.com/prettier/prettier/tree/v3.3.3/tests/format/js) | Failed: Network error: Not Found

**Comment by ShuiRuTian** [comment]
Good catch, it's because the tag of following repo does not start with "v"
- 'https://github.com/prettier/prettier/tree/3.3.3',
- 'https://github.com/getsentry/rust-sourcemap/blob/9.1.0',
- 'https://github.com/rust-lang/rust/blob/1.82.0',
- 'https://github.com/denoland/deno_graph/blob/0.84.0',
- 'https://github.com/guybedford/es-module-lexer/blob/1.5.4',

Fixed

**Comment by overlookmotel** [comment]
Only one still failing: https://github.com/prettier/prettier/tree/v3.3.3/tests/format/js (the `v` shouldn't be there)

**Comment by ShuiRuTian** [comment]
> Only one still failing: https://github.com/prettier/prettier/tree/v3.3.3/tests/format/js (the `v` shouldn't be there)
> 
> (see the "Check links" CI task)

Thanks, it's actually because my force-push was failed on my local machine because of net issue. 

I wrote a script to repalce url, so the easier way is to rewrote everything and make a force push

**Comment by overlookmotel** [comment]
Nice one! Thanks very much for doing this.

**Pull request merged**
