### PR TITLE
ci: use deterministic allocator for benchmarks

### PR DESCRIPTION
**Pull request by overlookmotel**
An attempt to reduce variance in benchmarks. Just testing at this stage.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#4483** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4483?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
This does seem to work in that it removes almost all variance from the benchmarks.

Results for 5 dummy commits on #4485 which is on top of this PR:

benches

Remaining problem is that changing the allocator is showing as quite a significant speed-up on many benchmarks. Probably this allocator is faster than system allocator! Need to slow it down somehow so it matches system allocator better.

**Comment by Boshen** [comment]
> Need to slow it down somehow so it matches system allocator better.

Probably doesn't matter, we are interested in relative change, not the absolute value from codspeed.

**Comment by overlookmotel** [comment]
> Probably doesn't matter, we are interested in relative change, not the absolute value from codspeed.

Problem is that I think it will give us unrealistic *relative* results too.

Let's say we introduce a change that removes a bunch of allocations, but requires some extra work to do that (caching structs, bookkeeping etc). That is very likely to be a performance gain in real world, but if the allocator we use for benchmarks makes allocation unrealistically cheap (as this one does), benchmarks will lie to us and tell us it's a perf regression. For example, with this allocator, benchmarks probably would have told us #4213 was a bad change.

Ditto for using an arena allocator - benchmarks may tell us that using bumpalo is hurting perf (because its not much cheaper than our unrealistically cheap "global" allocator), when in fact it's a large perf gain.

NB: Allocations are a small part of the code overall. So if we're seeing 10% perf boost on some benchmarks, probably that means this allocator is ~double the speed of the system one. That's a very big discrepancy.

We might have more luck with https://crates.io/crates/dlmalloc which it sounds like is a closer analogue to the default system allocator (from `libc`), and so may reduce this discrepancy. I'll look into that.

**Comment by overlookmotel** [comment]
Have asked for help on CodSpeed Discord: https://discord.com/channels/1065233827569598464/1065686090452828251/threads/1267428778691399690

**Comment by Boshen** [comment]
Merge or close?

**Comment by overlookmotel** [comment]
Close!

**Pull request closed without merging**
