### PR TITLE
perf(parser): faster parsing decimal numbers

### LINKED ISSUE #3288: Fast path for parsing decimal literals
#3283 made an optimization to the parser to avoid checking for `_`s in numeric literals twice, and got a nice 1% speed-up on parser benchmarks.

It occurs to me that we could repeat the trick for the common case of simple decimal literals (e.g. `0`, `1`, `123`). `str::parse::<f64>()` is quite a complicated function which checks for all kinds of things (exponent, decimal point, valid input etc). All of this is repeated work, since we've already determined in the lexer what the input is.

Perhaps we could have a flag which lexer sets if the input is a simple case, and then use a hand-rolled `parse_simple_decimal` function to convert to `f64`, like the ones we have for binary and octal?

https://github.com/oxc-project/oxc/blob/f38d138d970f97897d545f42cdd7a0068b5e894c/crates/oxc_parser/src/lexer/number.rs#L76-L88

(we should base implementation on `std`'s `str::parse::<f64>` as it's probably very optimized already, but just cut out all the extraneous checks)

Given that #3283 got a 1% speed-up, maybe this can get the same again, or maybe more?

@DonIsaac Would you be interested in investigating?

### PR DESCRIPTION
**Pull request by overlookmotel**
Closes #3288.

Speed up parsing decimal literals (e.g. `123`), using same techniques as `parse_octal` etc.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4257?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4257** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4257?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4254** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4254?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Hardly any effect in benchmarks, but a tiny bit. Disappointing, but may as well merge.

**Comment by overlookmotel** [comment]
Huh? CodSpeed was showing +1% before, but now suddenly it's changed to -3%. I didn't push any new commits. Something is squiffy. Will look into it.

**Review by DonIsaac — APPROVED** [review]

**Comment by overlookmotel** [comment]
Thanks for reviewing @DonIsaac.

**Pull request merged**
