### PR TITLE
refactor(sourcemap): using binary search to search original position

### PR DESCRIPTION
**Pull request by underfin**
The ast span is not ordering at rolldown, eg the module original ast is `a,b,c`, after mutate could be `b,c,a`. So here revert changes from [here](https://github.com/oxc-project/oxc/pull/2728).

### CODE REVIEW

**Comment by Boshen** [comment]
Do we need to fix the performance issue 😅

**Comment by overlookmotel** [comment]
> Do we need to fix the performance issue 😅

In my view, ultimately the best solution is to be calculating UTF16/line-column spans in the lexer (as discussed in #959). That should be the most performant way to support sourcemaps' use case.

Unclear when we're going to do that, but we could leave worrying about performance until then if we think it's not urgent to fix the perf right now.

**Comment by underfin** [comment]
Yeah. The performance is little regression at rolldown, we could skip it at now.

**Comment by Boshen** [comment]
:shipit:

**Comment by Boshen** [comment]
Wait ... can we add some test cases?

**Review by Boshen — APPROVED** [review]

**Pull request merged**
