### PR TITLE
feat(linter/jsdoc): Implement require-param rule

### PR DESCRIPTION
**Pull request by leaysgur**
Part of #1170

> https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-param.md

NOTE: `config.useDefaultObjectProperties` is not implemented for now.

### CODE REVIEW

**Comment by leaysgur** [comment]
```
$ ./typos .
Warning: "bject" should be "object".
error: `bject` should be `object`
  --> ./crates/oxc_linter/src/rules/jsdoc/require_param.rs:90:14
   |
90 |     "^(?:[oO]bject|[aA]rray|PlainObject|Generic(?:Object|Array))$".to_string()
   |              ^^^^^
   |
```

How to fix this..?

**Comment by Boshen** [comment]
It seems like there is a huge performance regression, would you like to investigate?

**Comment by Boshen** [comment]
> ```
> $ ./typos .
> Warning: "bject" should be "object".
> error: `bject` should be `object`
>   --> ./crates/oxc_linter/src/rules/jsdoc/require_param.rs:90:14
>    |
> 90 |     "^(?:[oO]bject|[aA]rray|PlainObject|Generic(?:Object|Array))$".to_string()
>    |              ^^^^^
>    |
> ```
> 
> How to fix this..?

I found two intresting cases where we can implement line or block ignore:

* https://github.com/crate-ci/typos/blob/49d37361a04c8119928f7463881fbc32a1c1abd0/crates/typos-cli/tests/cmd/ignore-block.in/_typos.toml
* https://github.com/crate-ci/typos/blob/49d37361a04c8119928f7463881fbc32a1c1abd0/crates/typos-cli/tests/cmd/ignore-line.in/_typos.toml

**Comment by leaysgur** [comment]
Thanks!

> It seems like there is a huge performance regression, would you like to investigate?

Yes..., I will try it later. 😢

**Comment by leaysgur** [comment]
About previous rules, I have been re-implemented them in an efficient way, by first understanding all the implementation (and test cases and configuration).

However, this time, this rule was so complex and I gave up. So basically code flow is following the original.

Then, how to fix this... 🤔

**Comment by Boshen** [comment]
```
        let check_types_regex = Regex::new(config.check_types_pattern.as_str())
            .expect("`config.checkTypesPattern` should be a valid regex pattern");
```

image


Codspeed to the rescue! Constructing the regex on each turn is expensive! You need to cache it / make it static 😅

**Comment by leaysgur** [comment]
Oh~~~, thank you very much indeed! (I've just learned such view exists...)

> You need to cache it / make it static

I will try! 💪🏻

**Comment by leaysgur** [comment]
🎉

**Review by Boshen — APPROVED** [review]
Nice work! Learned something new!

**Pull request merged**
