### PR TITLE
fix(semantic): incorrect reference flag for TSTypeParameter

### LINKED ISSUE #2023: Incorrect symbol references
https://oxc-project.github.io/oxc/playground/?code=3YCAAIC2gICAgICAgIC0G8rnONK88wEEqaAR7TB6kap9ZsyLue0RBjpWSJG6bXYDMwOdJ7L3juP1dt5lItxqFGL6b5l0%2F36F7IA%3D

image

The correct result is that the reference should be in `SymbolId 2`.

### PR DESCRIPTION
**Pull request by Dunqing**
fix: #2023

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2070** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2070?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2070?utm_source=stack-comment).

**Comment by Dunqing** [comment]
I added `SymbolFlags::TypeBlock` for some ts blocks that need a scope. This seems to solve our problem, but I'm not sure if this is a good solution.

**Comment by Boshen** [comment]
This feels dangerous 🤔

**Comment by Dunqing** [comment]
> This feels dangerous 🤔

I think the main problem is adding a scope to the class declaration

**Pull request closed without merging**
