### PR TITLE
test(traverse): add an api to get the index of the current node in Vec<'a, Statements<'a>>.

### PR DESCRIPTION
**Pull request by Dunqing**
Try to get the index of the current node in `Vec<'a, Statements<'a>>`.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#6644** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Yes, agree this API would be good. But I'm afraid at present I think no way to do it without undefined behavior.

Problem is that `walk_statements` has a live mutable reference to the `Vec<Statement>`:

https://github.com/oxc-project/oxc/blob/92812349e5266b074d2cb050cc7a6f200e4ac914/crates/oxc_traverse/src/generated/walk.rs#L5646-L5656

So it's illegal to get a `&` ref to `Vec<Statement>` to get its start pointer.

But... once we take control of `Vec` (#6488), we can add APIs to allow iterating over the `Vec` while staying purely in pointer-land, without creating any `&mut` reference to it. And *then* we should be able to do this.

*Maybe* I can find a way to do it prior to implementing our own `Vec`, but it's tricky. Is there an urgent need for this in one of the transforms?

**Comment by Dunqing** [comment]
@overlookmotel check your discord DM

**Comment by Dunqing** [comment]
Closing as we have decided using `Address` to identifier `Statement`

**Pull request closed without merging**
