### PR TITLE
perf(codegen): speed up generating sourcemap mappings

### PR DESCRIPTION
**Pull request by overlookmotel**
This PR optimizes the `update_generated_line_and_column` function used in generating source maps.

The main change is that `generated_column` only depends on the last line, so just spin through bytes to find the last line break, and then only convert last line UTF-8 to UTF-16. There's also a fast path for when last line is ASCII, to avoid iterating over the last line twice in that common case.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2597?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2597** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2591** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2590** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2590?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2584** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2584?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2583** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2583?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
By the way, I don't actually know what this function does!

A couple of other Qs:

1. Can we change all the byte offset fields from `usize` to `u32`? (e.g. `byte_offset_to_first`) OXC parser has a 4 GiB size limit on source files, but I'm not sure if possible output gets larger than this after transforms.
2. Is there a reason for `output` being a `Vec<u8>` rather than a `&str`? This would allow safely using `str::from_utf8_unchecked` instead of `str::from_utf8`, which would be a bit faster.

**Comment by Boshen** [comment]
> By the way, I don't actually know what the purpose of this function is!
> 
> A couple of other Qs:
> 
> 1. Can we change all the byte offset fields from `usize` to `u32` (e.g. `byte_offset_to_first`)? OXC parser has a 4 GiB size limit on source files, but I'm not sure if possible output gets larger than this after transforms.
> 2. Is there a reason for `output` being a `Vec<u8>` rather than a `&str`? This would allow safely using `str::from_utf8_unchecked` instead of `str::from_utf8`, which would be a bit faster.

You're free to change these, @underfin ported these from esbuild without any context of Oxc.

**Comment by Boshen** [comment]
### Merge activity

* **Mar 3, 11:22 PM EST**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2597).

**Pull request merged**
