### PR TITLE
feat(linter): no-irregular-whitespace rule

### PR DESCRIPTION
**Pull request by DeividAlmeida**
Parser, trivias and trivias_builder were edited to get all whitespaces. Now Trivias struct store comments and whitespaces Vec. After that, i will implement the no-irregular-whitespace rule.

P.S.: There isn't a way to implement this feature without lose a little bit of performance, comparing with my last PR #1819 to minimax this trouble instead of store the irregular whitespace as Span it was stored as u32, i removed a map iterator and removed too a unused function. If you have a suggestion about it pls give me a feedback.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Can we just implement the rule in eslint way, https://github.com/eslint/eslint/blob/main/lib/rules/no-irregular-whitespace.js, they just use source code to detect irregular whitespace rule, https://github.com/eslint/eslint/blob/main/lib/rules/no-irregular-whitespace.js#L203-L205

**Comment by IWANABETHATGUY** [comment]
Because lexer is the infra of the Javascript tools, not only linter use it, transformer, formatter, minifier would use it too.

**Comment by DeividAlmeida** [comment]
Hi @IWANABETHATGUY thanks for your feedback, I did this way because in the insure of these feature @Boshen suggest to edit the parser and store it in a vec

**Comment by DeividAlmeida** [comment]
image

https://github.com/oxc-project/oxc/issues/612

**Comment by DeividAlmeida** [comment]
in discord channel
image

**Comment by DeividAlmeida** [comment]
but i am just wait you decide what way should i proceed, both way are well.

**Comment by IWANABETHATGUY** [comment]
Let's just hold this pull request, and wait @Boshen to take a look.

**Comment by Boshen** [comment]
To minimize the performance impact, we should only store the irregular whitespaces

https://github.com/oxc-project/oxc/blob/1f3f21d722d22f97f20d9d2b47050dc86e185660/crates/oxc_parser/src/lexer/mod.rs#L360

**Comment by DeividAlmeida** [comment]
done!

**Review by Dunqing — APPROVED** [review]

**Pull request merged**
