### PR TITLE
feat(linter) oxc: only used in recursion

### PR DESCRIPTION
**Pull request by camc314**
Inspired by https://rust-lang.github.io/rust-clippy/master/#/only_used_in_recursion

Examples from VSCode Repo

Screenshot 2023-12-26 at 20 29 23

### CODE REVIEW

**Comment by camc314** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1833?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1832** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1833** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1833?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1833?utm_source=stack-comment).

**Comment by camc314** [comment]
For the VSCode error, on `createTOCIterator` i looked into it - looks like it's removal was misseed as part of a refactoring 🙂 

Was made recursive here: https://github.com/microsoft/vscode/commit/ccb98c2c9bb6aa3af3cb4a27be80cea88ecee37f

The use of the property was removed here:
https://github.com/microsoft/vscode/pull/74462/files#diff-290d58c5a12f00298e55d5a2993c95a7e313052c187e9009c67745c063072c61

but likley not noticed since it's used in the recursive call

**Review by Boshen — APPROVED** [review]
This is epic!

**Comment by IWANABETHATGUY** [comment]
Can you add a test case that function only used in recursion but is exported?
like: 
```js
module.exports = function test(a) {
  test(a)
}
```
```js
export function test(a) {
  test(a)
}
```

**Comment by camc314** [comment]
done

**Comment by Boshen** [comment]
### Merge activity

* **Dec 27, 9:27 AM**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1833).

**Pull request merged**
