### PR TITLE
perf(linter): use simd (memchr) for no-useless-escape search

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1766** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1766?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1766?utm_source=stack-comment).

**Comment by Boshen** [comment]
@camc314 This is pretty cool, you may use the same technique in other places 😁

**Comment by Boshen** [comment]
The benchmark doesn't have enough strings.

**Comment by camc314** [comment]
> @camc314 This is pretty cool, you may use the same technique in other places 😁

Yeah this is awesome 👀

**Pull request merged**
