### PR TITLE
feat(transformer_conformance): test `ScopeTree` and `SymbolTable` for correctness after transformation

### PR DESCRIPTION
**Pull request by Dunqing**
part of #4549 

This test verifies that the correct symbols and scopes were added/changed during the transformation. From the snapshots, most of them are incorrect currently

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#4581** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4581?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by DonIsaac** [comment]
Also related: #4454

**Comment by overlookmotel** [comment]
Great that we have the beginnings of test infra for this. I'm not surprised that the TS tests are all failing because I didn't complete the work of setting scopes correctly in those transforms, but I would have hoped more of the React/JSX ones would pass.

@Dunqing are you working on fixing, or shall I?

**Review by DonIsaac — APPROVED** [review]

**Comment by Dunqing** [comment]
> @Dunqing are you working on fixing, or shall I?

Yes, I am working on this!

**Comment by overlookmotel** [comment]
@Dunqing OK great. Please can you ping me if you fix the JSX ones? I thought I'd got them at least *mostly* right, so I'd be interested to know where I went wrong.

**Pull request merged**
