### PR TITLE
fix(semantic): add `cfg` nodes for `ConditionalExpression`s.

### PR DESCRIPTION
**Pull request by rzvxa**
It is done similarly to how `IfStatement`s are structured at the moment.

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3127?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3127** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3127?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3122** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3122?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#3071](https://github.com/oxc-project/oxc/pull/3071) <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3071?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
> ## [CodSpeed Performance Report](https://codspeed.io/oxc-project/oxc/branches/04-29-fix_semantic_add_cfg_nodes_for_conditionalexpression_s)
> ### Merging #3127 will **improve performances by ×2.7**
> 
> Comparing `04-29-fix_semantic_add_cfg_nodes_for_conditionalexpression_s` ([b76f2e0](https://github.com/oxc-project/oxc/commit/b76f2e045457b3442af9a51ba3d844b4bca54646)) with `04-28-fix_connect_test_expression_of_for_statements_to_the_cfg` ([d24c226](https://github.com/oxc-project/oxc/commit/d24c2268659b3e15d30945193cdbddb01e2ac20b))
> ### Summary
> 
> `⚡ 16` improvements `✅ 11` untouched benchmarks
> 
> `⁉️ 3` dropped benchmarks
> 
> > ⚠️ _Please fix the performance issues or [acknowledge them on CodSpeed](https://codspeed.io/oxc-project/oxc/branches/04-29-fix_semantic_add_cfg_nodes_for_conditionalexpression_s)._
> 
> ### Benchmarks breakdown
> 	Benchmark 	`04-28-fix_connect_test_expression_of_for_statements_to_the_cfg` 	`04-29-fix_semantic_add_cfg_nodes_for_conditionalexpression_s` 	Change
> ⚡ 	`lexer[antd.js]` 	129.9 ms 	117 ms 	+10.99%
> ⚡ 	`lexer[checker.ts]` 	73 ms 	66.5 ms 	+9.8%
> ⚡ 	`lexer[pdf.mjs]` 	19.4 ms 	18.7 ms 	+4.17%
> ⁉️ 	`linter[RadixUIAdoptionSection.jsx]` 	7.3 ms 	N/A 	N/A
> ⁉️ 	`linter[antd.js]` 	10.3 s 	N/A 	N/A
> ⁉️ 	`linter[pdf.mjs]` 	1.8 s 	N/A 	N/A
> ⚡ 	`minifier[react.development.js]` 	9.1 ms 	8.7 ms 	+5.45%
> ⚡ 	`minifier[typescript.js]` 	1.4 s 	1.3 s 	+7.31%
> ⚡ 	`parser[RadixUIAdoptionSection.jsx]` 	292.4 µs 	281.9 µs 	+3.75%
> ⚡ 	`parser[antd.js]` 	599.8 ms 	565.9 ms 	+5.98%
> ⚡ 	`parser[cal.com.tsx]` 	129.6 ms 	124.3 ms 	+4.27%
> ⚡ 	`parser[checker.ts]` 	306.1 ms 	288.6 ms 	+6.08%
> ⚡ 	`parser[pdf.mjs]` 	96.5 ms 	92.1 ms 	+4.76%
> ⚡ 	`semantic[pdf.mjs]` 	145.7 ms 	140.1 ms 	+4.01%
> ⚡ 	`transformer[RadixUIAdoptionSection.jsx]` 	919.8 µs 	536.8 µs 	+71.36%
> ⚡ 	`transformer[antd.js]` 	1,496.2 ms 	673.8 ms 	×2.2
> ⚡ 	`transformer[cal.com.tsx]` 	378.5 ms 	164.3 ms 	×2.3
> ⚡ 	`transformer[checker.ts]` 	940 ms 	352.3 ms 	×2.7
> ⚡ 	`transformer[pdf.mjs]` 	263.7 ms 	108.6 ms 	×2.4

What is wrong with this bench mark?

**Comment by rzvxa** [comment]
Any chance that benchmark is wrong? It was perfectly fine a few days ago and now it shows regression after updating it to the new head.

**Review by Boshen — APPROVED** [review]

**Comment by Boshen** [comment]
### Merge activity

* **May 10, 10:11 AM EDT**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/3127).

**Pull request merged**
