### PR TITLE
perf(semantic): store unresolved refs in a stack

### PR DESCRIPTION
**Pull request by lucab**
This tweaks `SemanticBuilder` logic in order to accumulate unresolved
references in a stack, getting rid of the previous index-vector which
is not required under the current access pattern.

Ref: https://github.com/oxc-project/oxc/pull/4107#issuecomment-2214167393

### CODE REVIEW

**Comment by lucab** [comment]
* **#4162** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4162?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lucab and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Nice work! However, I think we can potentially do even better.

What I had in mind is that you never call `unresolved_references.pop()`. Instead, hold on to the hash map and re-use it. That way we avoid generating (and allocating) new hash map when entering a scope most of the time.

`unresolved_references` is `Vec<UnresolvedReferences>`, indexed by *scope depth*.

e.g. with this input:

```js
function foo() {}
function bar() {}
```

* Enter top level scope:
  * Depth is 0.
  * Push a `UnresolvedReferences` hash map to `unresolved_references`.
  * Current hashmap is `unresolved_references[0]`.
* Enter scope for `foo`:
  * Increment depth to 1.
  * Push another `UnresolvedReferences` hash map to `unresolved_references`.
  * Current hashmap is `unresolved_references[1]`.
* Exit scope for `foo`:
  * Clear current hashmap (`unresolved_references[1]`).
  * Decrement depth to 0.
  * Do NOT pop from `unresolved_references`.
  * Current hashmap is now `unresolved_references[0]`.
* Enter scope for `bar`:
  * Increment depth to 1.
  * Do NOT push to `unresolved_references`.
  * Current hashmap is `unresolved_references[1]` (i.e. reuse same hash map that was used for `foo`)
 * Exit scope for `bar`: same as for `foo`
 * Exit top level scope: same
 
Does this make any sense? I *think* it'll be a further perf boost due to reducing allocations, and reusing allocations which are already warm in the cache.

**Comment by lucab** [comment]
@overlookmotel I see, you want to reuse previously allocated hashmaps (sorry I missed that point from your original request). Mind if I try to do that in a separate PR after landing this one, so that it's easier to see the performance delta?

**Comment by overlookmotel** [comment]
> Do you mind if I try to do that in a separate PR after landing this one

Yes, sure. Whichever way you prefer. In any case, this PR is already a really nice perf boost. Also... feel free *not* to do it at all! It's completely up to you what you want to work on. I'm just making suggestions, not commands!

**Review by overlookmotel — APPROVED** [review]

**Comment by lucab** [comment]
Yes, this one is ready to merge.

**Pull request merged**
