### PR TITLE
chore(transformer): support passing babel options path in example

### PR DESCRIPTION
**Pull request by Dunqing**
Sometimes we want to use Babel test's options to test some code, If the example can get the TransformerOptions from Babel options, then we can easily do it

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7790** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7790?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7790?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Dunqing** [comment]
Merging without review as it's just an example changed

**Comment by Dunqing** [comment]
### Merge activity

* **Dec 10, 7:32 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by overlookmotel** [comment]
This will be really helpful. 👍

**Pull request merged**
