### PR TITLE
feat(linter): output rules to json array

### LINKED ISSUE #7517: linter: API for eslint-plugin-oxlint
the eslint plugin `eslint-plugin-oxlint` does not parse the `rules.rs`.
Instead it looks recursivly into the rules directory and getting all informations (category: correctness, style, .., plugin-name: folder)

I am already getting annoyed because of the 3 big parts:

- Documentation in oxlint
- Detection in `oxlintrc.json` (maybe even oxlint cli, did not test it)
- Remapping in `eslint-plugin-oxlint`

_Originally posted by @Sysix in https://github.com/oxc-project/oxc/discussions/7242#discussioncomment-11401060_

### PR DESCRIPTION
**Pull request by camc314**
closes #7517

cc @Sysix

### CODE REVIEW

**Comment by camc314** [comment]
* **#7574** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7574?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7574?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Sysix** [comment]
thanks you @camc314 ❤️ 

I also tried to implement it today and found some problems on the way. 
For the moment this looks great 👍 

For the future I would like to have an `OutputFormatter` interface. 
Then maybe we can handle all the use cases for the different `--format` options and other flag combinations

**Comment by Boshen** [comment]
### Merge activity

* **Dec 1, 10:13 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by Boshen** [comment]
@Sysix Feel free to add more meta data for your requirements.

**Pull request merged**
