### PR TITLE
refactor(linter): simplify NoObjCalls resolution logic

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
* **#4765** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4765?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lucab and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by lucab** [comment]
I was hoping for a larger improvement as this linting module came up as the largest runner in my local profiles:
samply_main

However CodSpeed shows that the gain is small enough that it doesn't move the needle much:
codspeed

**Comment by Boshen** [comment]
Different setup and test files will produce different profiles. Every bit helps!

**Comment by DonIsaac** [comment]
I think this was the first rule I ever wrote, thanks and well done!

**Pull request merged**
