### PR TITLE
perf(parser): optimize lexing strings

### PR DESCRIPTION
**Pull request by overlookmotel**
Optimize lexing strings a bit.

### CODE REVIEW

**Comment by overlookmotel** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2366** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2366?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2366?utm_source=stack-comment).

**Comment by overlookmotel** [comment]
This is as good as I can do for now. Still a bit disappointing.

[As discussed](https://github.com/oxc-project/oxc/pull/2353#issuecomment-1935300679) on #2353, the increasing use of macros may be a concern. But could we go with it for now? If we introduce SIMD, or implement #2368, the macro will change a lot, and it'd be easier to keep those changes in one place (the macro) until it's fairly locked. At that point, as you said, if the macros slow down compilation we could expand them all manually.

**Comment by Boshen** [comment]
> But could we go with it for now?

Of course! Improve then refactor.

**Comment by overlookmotel** [comment]
> Of course! Improve then refactor.

Thanks Boshen!

**Pull request merged**
