### PR TITLE
perf(linter, prettier, diagnostics): use `FxHashMap` instead of `std::collections::HashMap`

### PR DESCRIPTION
**Pull request by camchenry**
Using `FxHashMap` is faster than `HashMap` in many cases, especially for hashing-heavy workloads. This change improves the performance of the linter, prettier, and diagnostics crates by using `FxHashMap` instead of `std::collections::HashMap`.

### CODE REVIEW

**Comment by camchenry** [comment]
* **#5993** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5993?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camchenry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by camchenry** [comment]
The -1% changes appear to be noise related to `ModuleRecord`. However, the +1% in `transformer` appears to be genuine: 
image

The +1% in linter seems uncertain, but doesn't look like it hurts performance at all. I think this is worth it, just for the +1% in transformer.

**Comment by Boshen** [comment]
Oh my! How did these go under the radar? Would you like to try banning these in https://github.com/oxc-project/oxc/blob/f5eee723fa4c6becb4e170b1a99f49813f302ff8/.clippy.toml#L3?

**Comment by camchenry** [comment]
@Boshen yeah, was going to ask about that! I can do that

**Pull request merged**
