### PR TITLE
feat(transformer/arrow-function-converter): move scope to changed scope for `this_var` if scope have changed

### PR DESCRIPTION
**Pull request by Dunqing**
The scope can be moved or deleted, we need to check whether the scope id is the same as the container's scope id, if not, we need to move the `this_var` to the target scope id.

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7125?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7125** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7125?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7113** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7107** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7107?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by overlookmotel — COMMENTED** [review]
Any idea what's going on with all the exec test fails? Seems odd that this is affecting `transform-object-rest-spread` too.

**Comment by Dunqing** [comment]
> Any idea what's going on with all the exec test fails? Seems odd that this is affecting `transform-object-rest-spread` too.

I just realized we need to install dependencies in https://github.com/oxc-project/oxc/blob/549cc823818ac837df14f1f4a6dbb64ddcb6c591/tasks/transform_conformance

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
### Merge activity

* **Nov 5, 6:19 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
