### PR TITLE
test(coverage): add Test262 semantic tests

### PR DESCRIPTION
**Pull request by DonIsaac**
# What This PR Does

Adds a suite of `Semantic` tests that can be plugged in to existing coverage suites.

The tests seem to run correctly, but now all parser Test262 tests are failing...

### CODE REVIEW

**Comment by DonIsaac** [comment]
* **#4454** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4454?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Dunqing** [comment]
We copied a lot of tests from `typescrip-eslint` for testing scope/symbols in #3990. do we need this anymore?

**Comment by overlookmotel** [comment]
Despite #3990, I do still think testing scopes against Test262 too is probably a good idea, for 2 reasons:

1. I imagine Test262 probably covers more weird edge cases (e.g. some strange stuff in sloppy mode code).
2. #3990 ported the test cases, but doesn't actually check them against the `typescript-eslint`'s snapshots (see #4316).

How far off were you from getting this working @DonIsaac?

**Comment by DonIsaac** [comment]
@overlookmotel the test infra works, but the tests need review. Not sure how to continue. @Dunqing  thoughts?

**Comment by Dunqing** [comment]
I agreed to continue this work. But It's not just tests262. we also need to check that the semantics in the `TypeScript` is correct.

**Comment by Boshen** [comment]
I'm going to work on this in https://github.com/oxc-project/oxc/issues/4790

**Pull request closed without merging**
