### PR TITLE
feat(ast_codegen): add `#[visit(enter_before)]` hint.

### LINKED ISSUE #4142: must visit decorators before `enter_node` and `enter_scope` if have `decorators` field
Please see:
https://github.com/oxc-project/oxc/blob/daea29c0dab6a75289530e33ba9b0d79f923617f/crates/oxc_semantic/src/builder.rs#L1521-L1526

### PR DESCRIPTION
**Pull request by rzvxa**
Closes #4142

I can split it into 2 PRs but it seems pointless. Let me know if you guys disagree with me.

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#4147** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4147?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Please see https://github.com/oxc-project/oxc/issues/4142#issuecomment-2219125356. I'm not clear why this change is required.

**Comment by rzvxa** [comment]
> Please see [#4142 (comment)](https://github.com/oxc-project/oxc/issues/4142#issuecomment-2219125356). I'm not clear why this change is required.

I just saw your comment, Even with that it is a good thing to have the `visit(enter_before)` marker just in case we need it in the future. I can just remove the marker from `Class` and merge the generator code.

**Comment by Boshen** [comment]
@Dunqing do you know about the semantic details here?

**Comment by Dunqing** [comment]
> @Dunqing do you know about the semantic details here?

https://github.com/oxc-project/oxc/issues/4142#issuecomment-2219677568

**Comment by Dunqing** [comment]
> I just saw your comment, Even with that it is a good thing to have the `visit(enter_before)` marker just in case we need it in the future. I can just remove the marker from `Class` and merge the generator code.

Yes, I think we can keep the `visit(enter_before)` marker for now. It may be useful for reimplementing the adding scope and resolving references.

**Comment by overlookmotel** [comment]
Personally, I don't think we should *ever* enter the node late. It is just confusing, and I can't see a use case.

If you want to avoid throwing away the generator code you already wrote, by all means merge it in, but would you consider "deactivating" `visit(enter_before)`, so we don't start using it kind of by accident without discussing first?

**Comment by rzvxa** [comment]
I'll generate an error on encountering it for now.

**Pull request merged**
