### PR TITLE
feat(prettier/ts): print `type` keyword inside import specifier braces, fixes #2708

### LINKED ISSUE #2708: Prettier drops `type` keyword inside import specifier braces
## Details

It's working as expected
```ts
import type { FC } from 'react'
```

But in this case, `type` is dropped
```ts
import { type FC } from 'react'
// Will be
import { FC } from 'react'
```

## Expected Behavior
If only one specifier is listed, `type` will be moved to the outside, otherwise nothing will change
```ts
// One specifier
import { type FC } from 'react'
// Will be
import type { FC } from 'react'

// Multiple specifiers
import { type FC, useState } from 'react'
// Nothing changed
import { type FC, useState } from 'react'
```

### PR DESCRIPTION
**Pull request by LIMPIX31**
- #2708

### CODE REVIEW

**Comment by Boshen** [comment]
Thank you. Formatting TypeScript is only 4% done: https://github.com/oxc-project/oxc/blob/main/tasks/prettier_conformance/prettier.ts.snap.md

There's currently no one working on this so any help is appreciated.

**Comment by Boshen** [comment]
It seems like we are adding custom logic (`import_inner_type`) in this PR, I prefer not to introduce these options because this is not part of our initial goals.

I'm happy to merge if this PR only prints `type` without any custom logic.

**Comment by LIMPIX31** [comment]
> It seems like we are adding custom logic (`import_inner_type`) in this PR, I prefer not to introduce these options because this is not part of our initial goals.
> 
> I'm happy to merge if this PR only prints `type` without any custom logic.

No problem. But I need to think of a way around the use of this state.

Is there now a way to store the state or some context when formatting?

**Comment by Boshen** [comment]
`prettier` doesn't move the `type` keyword to the outside, I want to refrain from adding these kind of custom logic at this stage.

**Comment by LIMPIX31** [comment]
> `prettier` doesn't move the `type` keyword to the outside, I want to refrain from adding these kind of custom logic at this stage.

Then that simplifies it)

**Review by mysteryven — APPROVED** [review]
Thank you for your patience and work. :)

**Pull request merged**
