### PR TITLE
fix(transformer/object-rest-spread): generate catch variable binding with correct `SymbolFlags`

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7469?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7470** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7470?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7469** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7469?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7469?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#7423** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7423?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
### Merge activity

* **Nov 26, 6:31 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by overlookmotel** [comment]
> * **Nov 26, 6:39 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

It *does* meet the requirements. Get on with it Graphite!

**Comment by overlookmotel** [comment]
Have rebased on main. Hopefully that'll unblock Graphite.

**Pull request merged**
