### PR TITLE
feat(transformer): add preset-env

### PR DESCRIPTION
**Pull request by Dunqing**
Related issues: https://github.com/oxc-project/oxc/issues/2870

The `targets` is an option for preset-env

This preset has a lot of test failures, so let's skip it for now.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#3298** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3298?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
Is `@babel/preset-env` a pre-step for babel plugins? It feels like the API is something like

`Transformer::from_preset_env()` and produces a transformer with all the plugins set correctly.

What do you think?

**Comment by Dunqing** [comment]
> Is `@babel/preset-env` a pre-step for babel plugins? It feels like the API is something like
> 
> `Transformer::from_preset_env()` and produces a transformer with all the plugins set correctly.
> 
> What do you think?

Yes. The `@babel/preset-env` just returns a series plugins. `Transformer::from_preset_env()` is simpler than preset-env. I like it.

**Comment by Dunqing** [comment]
We decided to use `Transformer::from_babel_config()` instead of `preset-env`. This function will handle what preset-env does and return the transformer options and errors for unsupported plugins/options.

This function signature like this
```rust
pub fn from_babel_config(config: serde_json::Value) -> Result<TransformOptions, Vec<Error>> {
}
```

**Pull request closed without merging**
