### PR TITLE
fix(codegen): invalid codegen when `in` inside bin expr in or loop

### PR DESCRIPTION
**Pull request by camc314**
https://github.com/oxc-project/monitor-oxc/actions/runs/11278829870 ??

### CODE REVIEW

**Comment by camc314** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6431?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6431** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6431?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#6428** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6428?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camc314 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by camc314** [comment]
@Boshen after this stack. looks like monitor-oxc now passes

**Comment by camc314** [comment]
also `monitor-oxc` is sweet 🔥

**Comment by Boshen** [comment]
I'll need to check with esbuild's implement for this stack of PRs.

**Comment by Boshen** [comment]
### Merge activity

* **Oct 13, 2:39 AM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
