### PR TITLE
perf(oxc_ast): optimize ast layout

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
1. as https://github.com/oxc-project/oxc/issues/5601#issuecomment-2338034345 suggested, this time only box `FunctionBody.directives`.
2. Also change `ast_tools` to support auto generated `Box<Vec<T>>`

### CODE REVIEW

**Comment by Boshen** [comment]
`Box<Vec<_>>` feels weird, let me think about this.

**Comment by IWANABETHATGUY** [comment]
> `Box<Vec<_>>` feels weird, let me think about this.

https://github.com/oxc-project/oxc/issues/5601#issuecomment-2338034345:~:text=In%20my%20opinion,usually%20None)

**Comment by overlookmotel** [comment]
A `ThinVec` type would be preferable for this use case (https://github.com/oxc-project/backlog/issues/113). But who knows when we'll get around to implementing that?

In the meantime, I think `Box<Vec<T>>` is the best solution we have available.

Personally I think we should consider re-opening this and likely merging it. At the very least, the changes to `ast_tools` and the `Traverse` codegen are worthwhile. @Boshen?

**Comment by Boshen** [comment]
> A `ThinVec` type would be preferable for this use case ([oxc-project/backlog#113](https://github.com/oxc-project/backlog/issues/113)). But who knows when we'll get around to implementing that?
> 
> In the meantime, I think `Box<Vec<T>>` is the best solution we have available.
> 
> Personally I think we should consider re-opening this and likely merging it. At the very least, the changes to `ast_tools` and the `Traverse` codegen are worthwhile. @Boshen?

`<Box<Vec_>>` looks too strange, and there is no observable performance impact to get this merged.

**Comment by overlookmotel** [comment]
@IWANABETHATGUY I'm sorry I "led you up the garden path" with my comment https://github.com/oxc-project/oxc/issues/5601#issuecomment-2338034345. It seems Boshen and I disagree on this one. It's unfortunate we didn't realize that before you started on PRs. Sorry.

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY I'm sorry I "led you up the garden path" with my comment [#5601 (comment)](https://github.com/oxc-project/oxc/issues/5601#issuecomment-2338034345). It seems Boshen and I disagree on this one. It's unfortunate we didn't realize that before you started on PRs. Sorry.

that's fine

**Pull request closed without merging**
