### PR TITLE
feat(coverage): second transformer build does not print typescript

### PR DESCRIPTION
**Pull request by Dunqing**
Currently, we lack a test to check if the TS AST has been completely deleted. I have thought of a way to test it. Let's have our idempotency test print the TypeScript code the first time and the second time print the JavaScript code only. If the two results do not match, it means that there are still undeleted TS ASTs or other bugs. Since ideally the TS ASTs are completely deleted, the two results should be the same.

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3561?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3561** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3561?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3559** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3559?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
Shall we just combine these 2 PRs and fix most things at once?

**Comment by overlookmotel** [comment]
This is a great idea. But we're missing one possible class of bugs - if TS nodes are left in after 1st transform pass, but deleted in 2nd transform pass, that's a bug, but this test won't catch it currently.

I suggest we codegen *twice* after *1st* pass - once with TS nodes printed, once without - and compare the 2 there.

**Comment by Dunqing** [comment]
> Shall we just combine these 2 PRs and fix most things at once?

Wait me for to fix a redundant semicolon issue, this will fix tons of mismatch cases

**Pull request merged**
