### PR TITLE
add numeric-separator transformer

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Add numeric separator transformer.

This is a low hang fruit, why don't we pick it?

### CODE REVIEW

**Comment by camc314** [comment]
i think this already happens in oxc_codegen:

https://github.com/oxc-project/oxc/blob/44375a5662ee3e6451f1a5335c75d6379d1878a6/crates/oxc_codegen/src/gen.rs#L1151

**Comment by ShuiRuTian** [comment]
> i think this already happens in oxc_codegen:
> 
> https://github.com/oxc-project/oxc/blob/44375a5662ee3e6451f1a5335c75d6379d1878a6/crates/oxc_codegen/src/gen.rs#L1151
> 
> [playground](https://playground.oxc.rs/#eNo9jtEOwiAMRf+lzzzoK777GwaxmyTQkpY5l2X/LswxEtJ7e5vTruDBwvVS3+P/b2CAwa4gE7WiCxX3BVtkQgMxUOlaPWc8zZKeHLsr4kgHlgR2cFFxM5CdKEolVt0oXZ+jveH5hSO23dWkQGEIe1SDlAVVD6aB+R0Kana+XnG0kqMxdrvDqAjHe+S5IT4oT9Yz37YfrMVYyQ==)

Indeed, then we do not need  that for numberic literial.

bigint transformer is still in need anyway, right?

**Comment by camc314** [comment]
i guess so? not really familiar 

https://github.com/oxc-project/oxc/blob/44375a5662ee3e6451f1a5335c75d6379d1878a6/crates/oxc_codegen/src/gen.rs#L1171

looks like it prints the raw val from the original source text

**Comment by Boshen** [comment]
> i guess so? not really familiar
> 
> https://github.com/oxc-project/oxc/blob/44375a5662ee3e6451f1a5335c75d6379d1878a6/crates/oxc_codegen/src/gen.rs#L1171
> 
> looks like it prints the raw val from the original source text

Good catch, it should be removed from the codegen.

**Comment by camc314** [comment]
we could probably minify in codegen

**Comment by Boshen** [comment]
Close as not planeed.

**Pull request closed without merging**
