### PR TITLE
feat(ast_tools): Add #[estree(always_flatten)] to Span

### PR DESCRIPTION
**Pull request by ottomated**
Part of #6347

Other changes:
- added #[estree(skip)] to thisSpan in TSThisParameter
- Flattened the span in BoundaryAssertion (regex)

### CODE REVIEW

**Comment by ottomated** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6935?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6935** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6935?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#6934** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6934?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6933** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6933?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ottomated and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
### Merge activity

* **Oct 27, 9:49 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by overlookmotel** [comment]
Rebased on main to solve phantom merge conflicts.

Poggers! 😄

**Comment by overlookmotel** [comment]
@ottomated For future reference, I would have made the changes to `TSThisParameter` and `BoundaryAssertion` in separate PRs. Those changes actually affect how the types are serialized (bug fixes). Then this PR (everything else) would have been pure refactor - no external changes, only changing *how* we generate serialized output.

**Pull request merged**
