### PR TITLE
fix(transformer): RegExp transform only set span on final expression

### PR DESCRIPTION
**Pull request by overlookmotel**

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5508?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5508** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5508?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5504** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5504?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5501** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5501?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
I *think* this is correct. We're transforming the whole `RegExpLiteral` into a `NewExpression`.

In: `/abc/u`
Out: `new RegExp("abc", "u")`

So I think:

1. The entire `new RegExp(...)` expression should have the span of the original `RegExpLiteral`
2. All the component parts (`RegExp`, `"abc"`, `"u"`) should have anonymous spans.

If I'm wrong, and we *do* want the component parts to have real spans, I guess they should reference the corresponding sections of the original regexp, not it's entirety.

```js
 ___ span 1
/abc/u
     ^ span 2
```

```js
            ___ span 1
new RegExp("abc", "u")
                   ^ span 2
```

But I'm not that knowledgeable on source maps. @Dunqing @Boshen can you please advise?

**Comment by overlookmotel** [comment]
It's unclear what Babel is doing. This doesn't set spans on inner components, but it looks like it doesn't set span on the whole expression either!

https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-sticky-regex/src/index.ts

**Comment by Dunqing** [comment]
I'm not that knowledgeable on source maps too. I checked esbuild does. Looks like it does well. You can see the [source-map-visualization](
https://evanw.github.io/source-map-visualization/#MjQ0AG5ldyBSZWdFeHAoIi4iLCAidiIpOwovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247YmFzZTY0LGV3b2dJQ0oyWlhKemFXOXVJam9nTXl3S0lDQWljMjkxY21ObGN5STZJRnNpUEhOMFpHbHVQaUpkTEFvZ0lDSnpiM1Z5WTJWelEyOXVkR1Z1ZENJNklGc2lMeTR2ZGlKZExBb2dJQ0p0WVhCd2FXNW5jeUk2SUNKQlFVRkJMRmRCUVVNc1MwRkJSU3hIUVVGRE95SXNDaUFnSW01aGJXVnpJam9nVzEwS2ZRbz0xMjgAewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiPHN0ZGluPiJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiLy4vdiJdLAogICJtYXBwaW5ncyI6ICJBQUFBLFdBQUMsS0FBRSxHQUFDOyIsCiAgIm5hbWVzIjogW10KfQo=)

**Comment by Dunqing** [comment]
So far, I haven't checked to see if I've set the span in the transformer correctly. 😅

**Comment by Dunqing** [comment]
Once the merge label is added, no one can stop Graphite from merging PR🥲

**Comment by overlookmotel** [comment]
You can stop it by removing the merge label if you do that before it actually starts the merge process. But once the wheels are in motion, the train has no brakes and will continue rumbling down the track no matter what you do. Choo choo!

**Pull request merged**
