### PR TITLE
perf(linter): only computed regex once in jsx-a11y/no-redundant-alt

### PR DESCRIPTION
**Pull request by camc314**

### CODE REVIEW

**Comment by camc314** [comment]
* **#4515** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4515?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camc314 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by camc314** [comment]
not sure whether this is worth merging, look like a 3% perf improvement on the cal.com benchmark. but no other real changes.

will leave up to you guys - feel free to close

**Review by Boshen — CHANGES_REQUESTED** [review]
You can use the latest https://doc.rust-lang.org/std/sync/struct.LazyLock.html now.

**Comment by overlookmotel** [comment]
> You can use the latest https://doc.rust-lang.org/std/sync/struct.LazyLock.html now.

Are we OK only supporting >= Rust 1.80.0?

**Comment by Dunqing** [comment]
> > You can use the latest https://doc.rust-lang.org/std/sync/struct.LazyLock.html now.
> 
> Are we OK only supporting >= Rust 1.80.0?

I think yes, we don't publish oxlint-relates crates, so oxlint without limitation of MSRV

**Comment by DonIsaac** [comment]
Replaced by #4604

**Pull request closed without merging**
