### PR TITLE
[WIP] refactor(parser): reduce lexer branching

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
* **#4597** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lucab and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Please see my comment here: https://github.com/oxc-project/oxc/issues/3292#issuecomment-2263804311

**Comment by overlookmotel** [comment]
Just to add: It is possible like with my previous "top tips" for lexer optimization that this comes to nothing. I really hope that's not the case, but it could of course happen, and I'd feel really bad to have wasted your time *twice*.

So if you get weary, please feel free to stop. Or feel free to ask me to pitch in, or ask if you're not familiar with the viewing-assembly-in-Godbolt stuff - I'd be more than happy to talk you through it.

**Comment by lucab** [comment]
Unfortunately you are right, I checked with a disassembler the generated binary code and this PR is not producing the CMOV logic you were expected. Let's close this one and go back to the starting blocks with a smaller scope.

**Pull request closed without merging**
