### PR TITLE
refactor(transformer): shorten code

### PR DESCRIPTION
**Pull request by overlookmotel**
Use `BoundIdentifier::create_binding_pattern`, rather than writing out the code to create a `BindingPattern` manually each time.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#6809** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Dunqing — APPROVED** [review]
I have to say the `BoundIdentifier` is so great!

**Comment by Dunqing** [comment]
### Merge activity

* **Oct 23, 9:11 AM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by overlookmotel** [comment]
> I have to say the `BoundIdentifier` is so great!

I still think we can improve the API. I would prefer methods on the AST types e.g. `BindingIdentifier::from_binding(binding, ctx)`, `BindingPattern::from_binding(binding, ctx)`. But at least `BoundIdentifier` removes boilerplate code for things we do commonly.

**Comment by overlookmotel** [comment]
> Yes, that would be better, but unfortunately, we can't get the `Atom` from `SymbolTable::get_name`, this may incur additional performance overhead.

Yeah we need to switch `Semantic` from storing names as `CompactStr`s to `Atom`s. That'd be a significant perf boost, and make lots of other things simpler. The blocker on that is that it makes `SymbolTable` need a lifetime `SymbolTable<'a>`, and apparently that causes problems for Rolldown (though I don't understand why).

**Pull request merged**
