### PR TITLE
refactor(prettier) Remove flat_contents from IfBreak

### PR DESCRIPTION
**Pull request by camc314**

### CODE REVIEW

**Comment by camc314** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1322** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1322?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1323** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1324** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1324?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
        * **PR #1325** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1325?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1324?utm_source=stack-comment).

**Review by Boshen — COMMENTED** [review]
I left `flat_contents` in as a placeholder because prettier has them 😅

**Comment by Boshen** [comment]
### Merge activity

* **Nov 14, 9:08 PM**: [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1324) rebased this pull request as part of a merge.

**Comment by camc314** [comment]
> I left `flat_contents` in as a placeholder because prettier has them 😅 

Oh 😅 didn't look like prettier used it

**Comment by Boshen** [comment]
> > I left `flat_contents` in as a placeholder because prettier has them 😅
> 
> Oh 😅 didn't look like prettier used it

Prettier's code base's type information is pretty useless I guess :-)

**Comment by camc314** [comment]
> > > I left `flat_contents` in as a placeholder because prettier has them 😅
> > 
> > 
> > Oh 😅 didn't look like prettier used it
> 
> Prettier's code base's type information is pretty useless I guess :-)

oops you're right, sorry - https://github.com/prettier/prettier/blob/fa484156174a6553b4155a0a7455f69e404b61a7/commands.md#L82-L96

**Comment by Boshen** [comment]
> > > > I left `flat_contents` in as a placeholder because prettier has them 😅
> > > 
> > > 
> > > Oh 😅 didn't look like prettier used it
> > 
> > 
> > Prettier's code base's type information is pretty useless I guess :-)
> 
> oops you're right, sorry - https://github.com/prettier/prettier/blob/fa484156174a6553b4155a0a7455f69e404b61a7/commands.md#L82-L96

No need to be sorry! Let's just break fast and ship fast.

**Pull request merged**
