### PR TITLE
docs(diagnostics): fully document `oxc_diagnostics`

### PR DESCRIPTION
**Pull request by DonIsaac**
Just a step in my mission to document our entire API

### CODE REVIEW

**Comment by DonIsaac** [comment]
* **#5865** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5865?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
I can't really review this one, as I have no idea how diagnostics work!

**Comment by DonIsaac** [comment]
* **#5865** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5865?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Just to clarify my last comment: I absolutely support your docs mission. I think it's great. I just can't review this one, because I don't understand this area of the codebase at all, so I can't pass any opinion on the accuracy or otherwise of the comments you've added.

But if you do know it, and you're confident your comments are accurate, then please feel free to go ahead and merge.

**Pull request merged**
