### PR TITLE
refactor(transformer/es2020): move all entry points to implementation of Traverse trait

### PR DESCRIPTION
**Pull request by Dunqing**
part of #4881

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4973?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4973** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4973?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4972** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4972?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4965** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4965?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by overlookmotel — COMMENTED** [review]
I suggest moving the internal methods (`clone_identifier_reference`, `clone_expression`, `create_new_var_with_expression`) to bottom of the file.

I've amended the "style guide" to add the convention that you should be able to read the code for a transformer from top to bottom, and the logic flows downwards (#4993) - `new` method at the top, then entry points, then internal methods which entry points call further down.

**Comment by overlookmotel** [comment]
Actually probably better to do that in a follow-on so it doesn't disrupt the other PRs stacked on top of this.

**Comment by Dunqing** [comment]
> I suggest moving the internal methods (`clone_identifier_reference`, `clone_expression`, `create_new_var_with_expression`) to bottom of the file.
> 
> I've amended the "style guide" to add the convention that you should be able to read the code for a transformer from top to bottom, and the logic flows downwards (#4993) - `new` method at the top, then entry points, then internal methods which entry points call further down.

Great, This is what I thought before!

**Pull request merged**
