### PR TITLE
refactor(transformer/react): don't follow the Babel's imports order

### PR DESCRIPTION
**Pull request by Dunqing**
The `ImportDeclaration` orders are not matter, they are always hoisted. Previously to 100% match Babel's output to pass the tests, we did some weird logic in our implementation. In this PR I removed them, and always inserted the imports at the top of the statements. The reason for doing this is I am moving `ModuleImports` to https://github.com/oxc-project/oxc/blob/5b5aad856213df18f09bf1972f6e3a13a5302a15/crates/oxc_transformer/src/common/mod.rs#L14-16

After being moved to `common`,  the `NamedImports` will only insert imports once in `common` instead of inserting in each plugin that used it.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#6176** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6176?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Personally I am not keen on diverging from Babel at this stage.

My feeling is that Babel's transformer tests which we are using for conformance are not enough. To *really* test the transformer we need to throw a lot more code at it. The best way I can see to do that is to do something like this:

* Crawl all the JS/TS files from the top 1000 npm packages.
* Run each of them through both Babel and Oxc transformer.
* Compare the outputs.

When we have no mismatches all all, we can have high confidence that our transformer is bug-free (or at least has no more bugs than Babel). But to run those tests without spurious differences in the diffs we need our transformer's output to match Babel's exactly - even in cosmetic aspects like statement order.

I'll look into this further and try to find if we can achieve what we're trying to do (move `ModuleImports` into `common`) without failing any tests. I *think* it should be possible.

**Comment by Dunqing** [comment]
@overlookmotel Feel free to take over this stack, I am on holiday now. 🏖️

**Comment by overlookmotel** [comment]
#6183 negates the need for this.

**Pull request closed without merging**
