### PR TITLE
feat(span): impl `From<Atom<'a>>` for `Atom`

### PR DESCRIPTION
**Pull request by DonIsaac**

### CODE REVIEW

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5809?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5810** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5810?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5809** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5808** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5808?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5807** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5807?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5806** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5806?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by overlookmotel — COMMENTED** [review]
Can I ask: Do we need this?

`Atom<'a>` already derefs to `&'a str` (I believe it was you that fixed the lifetime on that impl) so you can pass an `Atom<'a>` to any function which expects a `&'a str` via auto-deref. And if you want explicit conversion, we have `.as_str()`.

A reasonable reply would be "sure, but why not? It doesn't hurt". My answer is this: Personally, I don't particularly like `into()`, because I find that it's unhelpfully ambiguous. When reading code which uses `.into()`, I often find myself asking "but into *what*?". That's particularly the case when reviewing PRs on Github, without the benefit of Rust Analyser's hints.

I find `.as_str()` more explicit and more descriptive.

So, while I'm not a complete fanatic (I don't propose outlawing all use of `.into()` or anything!), personally, I'd prefer not add *more* support for it, when other decent alternatives exist.

Does my logic make any sense?

**Comment by DonIsaac** [comment]
> Can I ask: Do we need this?
> 
> 
> 
> `Atom<'a>` already derefs to `&'a str` (I believe it was you that fixed the lifetime on that impl) so you can pass an `Atom<'a>` to any function which expects a `&'a str` via auto-deref. And if you want explicit conversion, we have `.as_str()`.
> 
> 
> 
> A reasonable reply would be "sure, but why not? It doesn't hurt". My answer is this: Personally, I don't particularly like `into()`, because I find that it's unhelpfully ambiguous. When reading code which uses `.into()`, I often find myself asking "but into *what*?". That's particularly the case when reviewing PRs on Github, without the benefit of Rust Analyser's hints.
> 
> 
> 
> I find `.as_str()` more explicit and more descriptive.
> 
> 
> 
> So, while I'm not a complete fanatic (I don't propose outlawing all use of `.into()` or anything!), personally, I'd prefer not add *more* support for it, when other decent alternatives exist.
> 
> 
> 
> Does my logic make any sense?

In general, this makes sense. I agree with your point on ambiguity. The reason I'm adding this is to leverage auto-trait impls for other types. It makes type conversion easier when using standard library functions (and other 3rd party libraries for that matter).

**Comment by DonIsaac** [comment]
@overlookmotel just saw this while scrolling through notifications on my phone 😅 I'm posting this comment to remind myself to respond tomorrow

**Pull request merged**
