### PR TITLE
feat(oxc_transformer): replace_global_define for assignmentTarget

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
related esbuild test: 

https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/internal/bundler_tests/bundler_default_test.go#L5430-L5497

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7505** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7505?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7505?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by overlookmotel** [comment]
I don't know the define plugin at all. Can I please leave this to someone else to review?

**Comment by IWANABETHATGUY** [comment]
> I don't know the define plugin at all. Can I please leave this to someone else to review?

Yeah, @Boshen may have a look when he has time.

**Comment by Boshen** [comment]
### Merge activity

* **Nov 27, 8:22 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
