### PR TITLE
feat(transformer): class properties transform

### PR DESCRIPTION
**Pull request by overlookmotel**
Add class properties transform.

Implementation is incomplete. Notable missing parts:

* Scopes are not updated where property initializers move from class body into class constructor / `_super` function.
* Does not handle binding shadowing problems when property initializers move from class body into class constructor.
* `this` and references to class name in static property initializers need to be transformed to point to a temp var.
* Not all usages of private properties are supported (see below).
* Code which is moved to outside of class body is not transformed by other transforms for class declarations (works OK for class expressions). This includes static property initializers, static blocks, and computed property/method keys.
* Only basic checks for whether computed property/method keys may have side effects.
* Numerous other small issues noted in TODO comments through the code.

### Private properties

Currently does not handle the following usages of private properties:

```js
class Class {
  #prop;
  static #static;
  
  method() {
    object?.#prop;
    object?.#prop();
    [object.#prop] = [1];
    ({x: object.#prop} = {x: 1});
    object.#prop`xyz`;
    
    object?.#static;
    object?.#static();
    [object.#static] = [1];
    ({x: object.#static} = {x: 1});
    object.#static`xyz`;
  }
}
```

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#7011** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7011?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Boshen — COMMENTED** [review]
Too much fixtures committed to this repo, let me think about https://github.com/oxc-project/oxc/issues/4048

**Comment by overlookmotel** [comment]
Yes, I hope there's a better solution. I just wanted some working tests while I'm building the transform.

**Comment by overlookmotel** [comment]
@Boshen How do I run monitor-oxc on this branch?

**Comment by overlookmotel** [comment]
As noted above, this transform is incomplete. But I think it's in a fit state to merge at this point so we can iterate on it.

Note: Transform is not enabled by default, so I *think* monitor-oxc won't fail if we merge this.

**Comment by Boshen** [comment]
### Merge activity

* **Nov 25, 5:23 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
