### PR TITLE
refactor(parser): extend `byte_search` macro

### PR DESCRIPTION
**Pull request by overlookmotel**
Preparatory step for #2374.

### CODE REVIEW

**Comment by overlookmotel** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2372** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2372?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #2373** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2373?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2374** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2372?utm_source=stack-comment).

**Comment by Boshen** [comment]
### Merge activity

* **Feb 9, 9:52 PM EST**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2372).

**Comment by Boshen** [comment]
@overlookmotel Do you have discord? And check your email btw ;-)

**Comment by overlookmotel** [comment]
@Boshen Glad you poked me! I very rarely check that inbox. Yes, I do have Discord. I'm "overlookmotel".

**Pull request merged**
