### PR TITLE
fix(linter): improve the boundary for eslint/for-direction

### PR DESCRIPTION
**Pull request by heygsc**
is_sign_positive() will treat 0.0 as true, which may cause some errors.

https://eslint.org/docs/latest/rules/for-direction#rule-details

demo
[oxc](https://oxc-project.github.io/oxc/playground/?code=3YCAAICfgICAgICAgICzm0omL6Rfsn9X7Kj61BmzN0yVAOAXkgdgAKNr9vvkaX9%2FKzKAgA%3D%3D)
[eslint](https://eslint.org/play/#eyJ0ZXh0IjoiZm9yKGxldCBpID0gMDsgaSA8IDEwOyBpLT0wKXtcbn0iLCJvcHRpb25zIjp7InJ1bGVzIjp7ImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)

### CODE REVIEW

**Comment by DonIsaac** [comment]
Thanks for your contribution @heygsc!

I only see a bug fix in this PR, did you mean to commit a fixer implementation as well?

**Comment by heygsc** [comment]
> Thanks for your contribution @heygsc!
> 
> I only see a bug fix in this PR, did you mean to commit a fixer implementation as well?

Oh, I think this is just a bug fix. 
Haha, I didn't quite understand the `fixer implementation` in #4179

**Comment by DonIsaac** [comment]
No worries! If this is just a bug fix, would you please mind changing the title of the PR?

**Comment by heygsc** [comment]
> No worries! If this is just a bug fix, would you please mind changing the title of the PR?

Okay, I changed the title.

**Review by DonIsaac — APPROVED** [review]

**Comment by heygsc** [comment]
Some tests didn't pass just now, but now some format errors have been fixed.

**Comment by heygsc** [comment]
Some tests about format didn't pass just now, but now some format errors have been fixed.
Re test? @DonIsaac

**Pull request merged**
