### PR TITLE
feat(transformer/typescript): report error relate mts/cts files

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3278?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3278** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3278?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3258** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3258?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
This feels so weird thrown from the transformer, let me double check.

**Comment by Boshen** [comment]
These are checker errors, we should throw them from the typescript checker.

From checker.ts:

```typescript
    function checkAssertion(node: AssertionExpression, checkMode: CheckMode | undefined) {
        if (node.kind === SyntaxKind.TypeAssertionExpression) {
            const file = getSourceFileOfNode(node);
            if (file && fileExtensionIsOneOf(file.fileName, [Extension.Cts, Extension.Mts])) {
                grammarErrorOnNode(node, Diagnostics.This_syntax_is_reserved_in_files_with_the_mts_or_cts_extension_Use_an_as_expression_instead);
            }
        }
        return checkAssertionWorker(node, checkMode);
    }
```

```
    function checkGrammarArrowFunction(node: Node, file: SourceFile): boolean {
        if (!isArrowFunction(node)) {
            return false;
        }

        if (node.typeParameters && !(length(node.typeParameters) > 1 || node.typeParameters.hasTrailingComma || node.typeParameters[0].constraint)) {
            if (file && fileExtensionIsOneOf(file.fileName, [Extension.Mts, Extension.Cts])) {
                grammarErrorOnNode(node.typeParameters[0], Diagnostics.This_syntax_is_reserved_in_files_with_the_mts_or_cts_extension_Add_a_trailing_comma_or_explicit_constraint);
            }
        }

        const { equalsGreaterThanToken } = node;
        const startLine = getLineAndCharacterOfPosition(file, equalsGreaterThanToken.pos).line;
        const endLine = getLineAndCharacterOfPosition(file, equalsGreaterThanToken.end).line;
        return startLine !== endLine && grammarErrorOnNode(equalsGreaterThanToken, Diagnostics.Line_terminator_not_permitted_before_arrow);
    }
```

We don't run semantic check in the test suite, I wonder whether we should 😅

**Review by Boshen — CHANGES_REQUESTED** [review]
The check should be done somewhere else.

**Comment by Dunqing** [comment]
> We don't run semantic check in the test suite, I wonder whether we should 😅

The transformer doesn't need semantic now.

**Comment by Boshen** [comment]
Let's throw these in semantic checker, and ignore them from the transformer suite because they shouldn't be there ...

**Comment by Dunqing** [comment]
> Let's throw these in semantic checker, and ignore them from the transformer suite because they shouldn't be there ...

The semantic doesn't have a source_path. Should we pass it in?

**Comment by Boshen** [comment]
> source_path

Why do we need source_path?

**Comment by Dunqing** [comment]
> > source_path
> 
> Why do we need source_path?

These errors only report in files with the .mts or .cts extension

**Comment by Boshen** [comment]
> > > source_path
> > 
> > 
> > Why do we need source_path?
> 
> These errors only report in files with the .mts or .cts extension

Oh, the information should be encoded in crates/oxc_span/src/source_type.rs

what are their official names and categories?

**Comment by Dunqing** [comment]
> Oh, the information should be encoded in crates/oxc_span/src/source_type.rs
> 
> what are their official names and categories?

Seems they are no official names.

https://github.com/microsoft/TypeScript/blob/64d2eeea7b9c7f1a79edf42cb99f302535136a2e/src/compiler/checker.ts#L36039-L36047

https://github.com/microsoft/TypeScript/blob/4ece0a381be3d925b12b9a1626583578b8735805/src/compiler/moduleNameResolver.ts#L180-L187

**Comment by Boshen** [comment]
> > Oh, the information should be encoded in crates/oxc_span/src/source_type.rs
> > what are their official names and categories?
> 
> Seems they are no official names.
> 
> https://github.com/microsoft/TypeScript/blob/64d2eeea7b9c7f1a79edf42cb99f302535136a2e/src/compiler/checker.ts#L36039-L36047
> 
> https://github.com/microsoft/TypeScript/blob/4ece0a381be3d925b12b9a1626583578b8735805/src/compiler/moduleNameResolver.ts#L180-L187

`ModuleType`: ESM / CJS

**Pull request closed without merging**
