### PR TITLE
feat(linter/eslint-plugin-vitest): implement no-conditional-in-test

### PR DESCRIPTION
**Pull request by shulaoda**
Related to #4656

### CODE REVIEW

**Comment by mysteryven** [comment]
Do you want to implement jest/no-conditional-in-test too? It can be placed in path `rules/jest` 👀

**Comment by shulaoda** [comment]
> Do you want to implement jest/no-conditional-in-test too? It can be placed in path `rules/jest` 👀

Of course, it seems that their logic is the same, I just need to change the file position and map it?

**Comment by mysteryven** [comment]
> I just need to change the file position and map it?
 
 I think so.

**Review by mysteryven — APPROVED** [review]
Nice! 👍🏻

**Pull request merged**
