### PR TITLE
[WIP] feat(linter): add `eslint/no-unused-vars`

### LINKED ISSUE #595: feat(linter): no-unused-vars

### PR DESCRIPTION
**Pull request by DonIsaac**
> This PR is a work in progress and not ready to be merged

Closes #595 

### vars
- [x] support `vars: "local"`
- [x] ignore vars by name using regex option
- [x] Ignore object patterns based on same name
- [x] Ignore array spreads based on both ignored vars regex and restructured array regex 
- [ ] support `ignoreRestSiblings`
- [x] support `caughtErrors`
- [x] support ignoring unused caught errors with `caughtErrorsIgnorePattern` option

### functions and classes
- [x] report unused functions
- [x] report unused classes
- [ ] report functions that only get called recursively
 
### function args
- [x] report unused args
- [x] ignore unused args that match `argsIgnorePattern` 
- [x] support `after-used` option
- [x] report unused args from obj/arr spreads that occur "after" a used option when `after-used` is set

### In Rule
- [ ] vars that are used as iterators in `for in` loops should count as a valid read, e.g.
```js
// this is valid
(function(obj) {
  var name;
  for ( name in obj ) return;
})({});
```
- [ ] bindings declared within the rhs of an assignment should count as a usage, e.g.
```js
//           vvv used b/c exported 
export const Foo = class Foo {}
//                       ^^^ used b/c assigned
```

### (Possibly) in Semantic Analysis
- [ ] variables used in the rhs of an assignment that are also mutated are (incorrectly) not flagged as a read. e.g.
```js
/// this should count as a read usage, but it doesn't
var a = 1; a ||= 1;
```
```js
// x is incorrectly reported as not read
var x = 1; var y = x++; console.log(y)
```

### CODE REVIEW

**Comment by Boshen** [comment]
You may draft this to reduce some noise.

**Comment by DonIsaac** [comment]
blocked by #660

**Comment by Boshen** [comment]
Note to self: merge some of this and close this PR.

**Comment by Boshen** [comment]
After inspecting this PR closely, it seems like this is in a unmergable state, so I'll close this for now. Thank you for working on this @DonIsaac!

I think we have the semantic data for reading unused vars now.

**Pull request closed without merging**
