### PR TITLE
fix(ast_codegen): detect "complex" type wrappers

### PR DESCRIPTION
**Pull request by rzvxa**
Detect types such as `Cell<Option<ScopeId>>` and mark them as such! We didn't used to use this method for these options but now we have to check all types to calculate their layouts which means we need to process them correctly(instead of falling to their inner value).

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4617?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4540** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4540?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4404** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4404?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4615** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4614** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4617** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4617?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4612** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
What constitutes "complex"? In practice at present, is it only `Cell<Option<T>>`?

A couple of suggestions:

Could we add `Cell` and `CellOpt` variants to `TypeWrapper`, to explicitly handle these, rather than a catch-all `Complex`?

At present are you assuming that `Cell<Option<T>>` has same size and alignment as `T`? If so, that's only true accidentally, because `ScopeId`, `SymbolId` and `ReferenceId` are all `NonZeroU32` under the hood, and so have a niche. If someone changed `ScopeId` to a `u32`, or wrapped some other field in a `Cell`, this assumption would break.

This isn't entirely academic - Dunqing was talking about making `IdentifierReference::reference_flag` a `Cell` in #4512.

Using the following rules would make type layout calculations more robust in the face of such changes:

* `Cell<T>` is same size and align as `T` (so where `T` is an `Option`, calculate size + alignment of the `Option` using same logic as for other `Option`s).
* `Cell<T>` never has a niche, even if `T` does.

Taking it a bit further (which I'm not suggesting doing now, but we maybe could in future) could make `TypeWrapper` more flexible by turning it into a `Vec<TypeWrapperPart>`. So then you could handle any possible combination of wrappers e.g. `my_field: Option<Vec<Option<Box<Something>>>`.

**Comment by rzvxa** [comment]
> What constitutes "complex"? In practice at present, is it only Cell<Option<T>>?

Any type that has more than one part(e.g. Adt<T>) and `Adt` isn't covered by other wrappers.

> Could we add Cell and CellOpt variants to TypeWrapper, to explicitly handle these, rather than a catch-all Complex?

We sure can but we don't need it at the moment. We never care for misc types such as `Cell<Option<XXX>>`. We do not run any analysis on them. It is always just a simple match to detect these and do a predefined behavior.

> At present are you assuming that Cell<Option<T>> has same size and alignment as T? If so, that's only true accidentally, because ScopeId, SymbolId and ReferenceId are all NonZeroU32 under the hood, and so have a niche. If someone changed ScopeId to a u32, or wrapped some other field in a Cell, this assumption would break.

No; Instead we have the whole type as well-known (as opposed to having well-known wrappers and calculating the layout).

https://github.com/oxc-project/oxc/blob/8cdd9d9795000abbd4af461d255fd8f9adeac31f/tasks/ast_codegen/src/passes/calc_layout.rs#L356-L358

As you can see unlike the other wrappers which we only mark the wrapper part(for example `Vec`) as well-known, These are fully identified types with predefined layouts.

https://github.com/oxc-project/oxc/blob/8cdd9d9795000abbd4af461d255fd8f9adeac31f/tasks/ast_codegen/src/passes/calc_layout.rs#L219-L249

If a type isn't AST And doesn't have well-known information to calculate its layout, We check if the whole type is well-known or not. If it is we use that layout otherwise we fail to do so.

As a follow up we can calculate these, But we don't have to. I assert all of the types so if a well-known layout changes we get an updated assertion or old assertions break(if we don't call just ast with new layouts).


I think the only scenario where calculating Cell is necessary is if we use it to wrap actual AST types. In that case, we should add `Cell` as an actual wrapper.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
Thanks for clarifying. I hadn't clocked that layout for `Cell<Option<ScopeId>>` etc are hard-coded. That's totally fine for now.

**Pull request merged**
