### PR TITLE
refactor(ast): add explicit enum discriminants.

### PR DESCRIPTION
**Pull request by rzvxa**
Related to oxc-project/backlog#123 but doesn't close it.

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#4682** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4682?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4689** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4689?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@rzvxa I'm not sure if this is a temporary measure, but please see my comment here: https://github.com/oxc-project/oxc/issues/4622#issuecomment-2271554506

**Comment by overlookmotel** [comment]
Ah ha OK. Would you not prefer to implement adding the discriminants in `ast` macro?

If that's tricky at the moment as codegen is in flux, we can merge this as is, but we'd ideally then remove them again later on.

**Comment by rzvxa** [comment]
> Ah ha OK. Would you not prefer to implement adding the discriminants in `ast` macro?
> 
> If that's tricky at the moment as codegen is in flux, we can merge this as is, but we'd ideally then remove them again later on.

Yeah, I prefer it for obvious reasons. However, I'd like to do that as a follow-up at another time.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
> I'd like to do that as a follow-up at another time.

OK sure.

**Pull request merged**
