### PR TITLE
perf(transformer/optional-chaining): mark `enter_expression` as inline

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7390** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7390?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7390?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by overlookmotel — COMMENTED** [review]
I suggest to move more code out of `enter_expression`. To make sure `enter_expression` gets inlined, you want the function to be as small as possible. Only include logic which is "unless [cheap check], do nothing".

The point is that in most cases `expr` is *not* a `ChainExpression` or a `UnaryExpression` with `delete` operator, so want to make `enter_expression` as optimized as possible for the common "nothing to do here" path.

In practice, this means to move these two blocks out into separate functions:

```rs
if self.is_inside_function_parameter {
    // To insert the temp binding in the correct scope, we wrap the expression with
    // an arrow function. During the chain expression transformation, the temp binding
    // will be inserted into the arrow function's body.
    Self::wrap_arrow_function(expr, ctx)
} else {
    self.transform_chain_expression(false, expr, ctx)
}
```

```rs
if self.is_inside_function_parameter {
    // Same as the above explanation
    Self::wrap_arrow_function(expr, ctx)
} else {
    self.transform_chain_expression(true, &mut unary_expr.argument, ctx)
}
```

**Comment by Dunqing** [comment]
> I suggest to move more code out of `enter_expression`. To make sure `enter_expression` gets inlined, you want the function to be as small as possible. Only include logic which is "unless [cheap check], do nothing".
> 
> The point is that in most cases `expr` is _not_ a `ChainExpression` or a `UnaryExpression` with `delete` operator, so want to make `enter_expression` as optimized as possible for the common "nothing to do here" path.
> 
> In practice, this means to move these two blocks out into separate functions:
> 
> ```rust
> if self.is_inside_function_parameter {
>     // To insert the temp binding in the correct scope, we wrap the expression with
>     // an arrow function. During the chain expression transformation, the temp binding
>     // will be inserted into the arrow function's body.
>     Self::wrap_arrow_function(expr, ctx)
> } else {
>     self.transform_chain_expression(false, expr, ctx)
> }
> ```
> 
> ```rust
> if self.is_inside_function_parameter {
>     // Same as the above explanation
>     Self::wrap_arrow_function(expr, ctx)
> } else {
>     self.transform_chain_expression(true, &mut unary_expr.argument, ctx)
> }
> ```

Thank you for your long explanation, I think I understand now!

**Comment by Boshen** [comment]
No change 🤔 Maybe it was already inlined.

**Comment by overlookmotel** [comment]
I'm going to try some stuff... marking as draft for now.

**Comment by Boshen** [comment]
### Merge activity

* **Nov 25, 3:36 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by overlookmotel** [comment]
No change in benchmarks. But I still think this change is good. The smaller we can make all `enter_expression` / `exit_expression` methods, the more likely `enter_expression` / `exit_expression` in *other* transforms can be inlined too.

**Pull request merged**
