### PR TITLE
refactor(lexer): change `TokenValue::String(Atom)` to `TokenValue::String(&str)`

### PR DESCRIPTION
**Pull request by Boshen**
Based on #171, we discovered that we don't need to create the Atom inside the lexer, it should be done in the parser.

The code was written this way because the borrow checker won the lifetime game a year ago, but this time I tamed it in like 5 minutes ;-)

### CODE REVIEW

**Comment by Boshen** [comment]
for `TokenValue(RegExp)`, `RegExp.pattern` can also be converted. I'll leave this to the next person :-)

**Comment by gaowujie2004** [comment]
> 对于`TokenValue(RegExp)`，`RegExp.pattern`也可以转换。这个留给下一个人吧 :-)

Can I do this task?

**Comment by overlookmotel** [comment]
Thanks for your interest, but the codebase has moved on since this PR was merged. `TokenValue` no longer exists, and the approach for handling `Token`s is quite different in general. So I'm afraid the comment you replied to is rather out of date.

If you're interested in getting involved with Oxc, maybe reach out to us [on Discord](https://discord.gg/9uXCAwqQZW) or have a look at the list of [good first issues](https://github.com/oxc-project/oxc/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22).

**Comment by gaowujie2004** [comment]
> 感谢您的关注，但自从此 PR 合并以来，代码库已经发生了变化。`TokenValue`不再存在，而且处理`Token`s 的方法总体上也大不相同。因此，恐怕您回复的评论已经过时了。
> 
> 如果您有兴趣参与 Oxc，可以[通过 Discord](https://discord.gg/9uXCAwqQZW)与我们联系，或者查看[优秀首个问题](https://github.com/oxc-project/oxc/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22)的列表。

thank

**Pull request merged**
