### PR TITLE
ci: update babel version

### PR DESCRIPTION
**Pull request by rzvxa**
In my privius PR I changed this version in justfile It seems like the version used in CI is different from justfile.

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#2814** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2814?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Dunqing — APPROVED** [review]

**Comment by rzvxa** [comment]
@Dunqing It changes snapshots that were not included in this PR, My bad! It will break the CI I'm running the task to update it but since I haven't cloned submodules it would take a while to run from a cold start, Sorry for the inconvenience. Since it might take a while to run the tests feel free to push the updated snapshots yourself, Don't wait for my PR. If I see it fixed I will close my PR.

**Comment by Dunqing** [comment]
> @Dunqing It changes snapshots that were not included in this PR, My bad! It will break the CI I'm running the task to update it but since I haven't cloned submodules it would take a while to run from a cold start, Sorry for the inconvenience. Since it might take a while to run the tests feel free to push the updated snapshots yourself, Don't wait for my PR. If I see it fixed I will close my PR.

Don't worry. I think we should make sure ci runs when `clone-submodules/action.yml` changes. I made a fix in https://github.com/oxc-project/oxc/pull/2816

**Comment by rzvxa** [comment]
> Don't worry. I think we should make sure ci runs when `clone-submodules/action.yml` changes. I made a fix in #2816

Thanks, It is a good idea.
I found the issue on why the conformance doesn't run on my local machine, But I'm relieved to see that you already addressed it.

**Pull request merged**
