### PR TITLE
test(linter): improve test failure output

### PR DESCRIPTION
**Pull request by camchenry**
Improves the test output when a test fails, based on the type of expectation. The output now includes the config that was passed, as well as the source code that failed. Additional formatting makes it a little bit easier to parse.

Before:

Screenshot 2024-10-27 at 11 54 02 PM

&nbsp;

Screenshot 2024-10-27 at 11 54 56 PM

---

After:

Screenshot 2024-10-27 at 11 49 36 PM

&nbsp;

Screenshot 2024-10-27 at 11 58 56 PM

### CODE REVIEW

**Comment by camchenry** [comment]
* **#6975** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6975?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camchenry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Boshen — COMMENTED** [review]
Nice!

**Comment by DonIsaac** [comment]
Ship it 🚀

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
### Merge activity

* **Oct 28, 8:54 AM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
