### PR TITLE
perf(isolated-declarations): use `FxHashSet` instead of `Vec` to speed up the `contain`

### PR DESCRIPTION
**Pull request by Dunqing**
I tried it on my laptop. It was nearly three times faster than before.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#4074** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4074?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
We need a benchmark at this point, can you add a large one to https://github.com/oxc-project/benchmark-files, generate a benchmark on main, and then rebase this PR so we observe the difference?

**Review by Boshen — CHANGES_REQUESTED** [review]
We need a benchmark at this point, can you add a large one to https://github.com/oxc-project/benchmark-files, generate a benchmark on main, and then rebase this PR so we observe the difference?

**Comment by Dunqing** [comment]
5.x faster than before 🤩

**Review by Boshen — APPROVED** [review]

**Pull request merged**
