### PR TITLE
feat(codegen): configurable typescript codegen

### PR DESCRIPTION
**Pull request by andymac4182**
- Adds option to `CodegenOptions` - `enable_typescript` to enable output of TS. 
- Stops skipping output that is TS when `enable_typescript` is enabled
- Adds TS support to 
    - Function
    - FormalParameter
    - BindingPattern
 - Adds basic tests for TS generation

### CODE REVIEW

**Comment by Boshen** [comment]
I'll clean this up a bit today and merge, to avoid a huge PR.

**Comment by andymac4182** [comment]
Appreciate that :) I am working on a few more PRs that will improve the coverage 😄

**Comment by Boshen** [comment]
I merged the codegen tests to make sure we don't break existing behavior. It already caught some bugs :-)

**Comment by andymac4182** [comment]
Thanks for that 👍 

Are you happy with this PR? I will rebase my next bit of work on this one.

**Pull request merged**
