### PR TITLE
refactor(oxc_transformer): use enum to represent `Pragma`

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#7613** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7613?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7613?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by overlookmotel** [comment]
@IWANABETHATGUY Oh I'm sorry. I didn't realize you were working on this.

**Comment by overlookmotel** [comment]
One question, if you don't mind me asking: Same as in #7553, here you `Box` the result of the various match arms. What's the advantage of doing that?

**Comment by IWANABETHATGUY** [comment]
> One question, if you don't mind me asking: Same as in #7553, here you `Box` the result of the various match arms. What's the advantage of doing that?

No special reason, I saw your code and I think it is better than me, I just don't realize early return could avoid Boxing a iter trait.

**Comment by overlookmotel** [comment]
Ah ha now I understand the `Box`. Thanks for explaining.

**Pull request closed without merging**
