### PR TITLE
fix(tasks): find the right output to diff

### PR DESCRIPTION
**Pull request by mysteryven**

### CODE REVIEW

**Comment by mysteryven** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1596** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1596?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1596?utm_source=stack-comment).

**Comment by Boshen** [comment]
I also noticed that 

https://github.com/oxc-project/oxc/blob/ba5b13da2cedbeaeb53414e78193cfd5621e2385/tasks/prettier_conformance/src/lib.rs#L329

would return `None`

and then 

https://github.com/oxc-project/oxc/blob/ba5b13da2cedbeaeb53414e78193cfd5621e2385/tasks/prettier_conformance/src/lib.rs#L306

would become an empty string, which lead to producing an empty diff.

**Comment by mysteryven** [comment]
> I also noticed that
> 
> https://github.com/oxc-project/oxc/blob/ba5b13da2cedbeaeb53414e78193cfd5621e2385/tasks/prettier_conformance/src/lib.rs#L329
> 
> would return `None`

Curious about which case will return `None`, do you remember which case?

**Comment by Boshen** [comment]
### Merge activity

* **Dec 3, 2:29 AM**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1596).

**Pull request merged**
