### PR TITLE
feat(transform_conformance): custom reporter for exec test

### LINKED ISSUE #7704: Remove extraneous detail from snapshots for transformer "exec" tests
Snapshots for transformer "exec" tests contain extraneous details which make snapshot changes hard to read, and causes erroneous conformance task failures.

## Irrelevant details cause CI failures

For example, #7687 adds a new exec test. The problem is that the snapshot contains irrelevant details, which cause changes in the snapshot on every run, and so an erroneous failure:

```diff
- RUN  v2.1.2 /Users/overlookmotel/Programming/crates/oxc/tasks/transform_conformance
+ RUN  v2.1.2 /home/runner/work/oxc/oxc/tasks/transform_conformance
 
- ✓ fixtures/oxc/babel-plugin-transform-class-properties-test-fixtures-this-in-computed-key-exec.test.js  (1 test) 2ms
+ ✓ fixtures/oxc/babel-plugin-transform-class-properties-test-fixtures-this-in-computed-key-exec.test.js  (1 test) 5ms
 
-   Start at  10:54:43
-   Duration  160ms (transform 12ms, setup 0ms, collect 6ms, tests 2ms, environment 0ms, prepare 38ms)
+   Start at  10:59:00
+   Duration  242ms (transform 19ms, setup 0ms, collect 12ms, tests 5ms, environment 0ms, prepare 61ms)
```

https://github.com/oxc-project/oxc/actions/runs/12197559497/job/34027460327?pr=7687

I'm not sure if we can get vitest to not output these irrelevant details, or whether we'd need to post-process vitest's output to remove them before outputting snapshot.

## Test numbering creates large diffs

Snapshots include a number before each test failure e.g.:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/28]⎯
```

This creates a lot of churn in the diff when you fix a test, which makes it harder to see the relevant changes. Because you get a ton of irrelevant changes like:

```diff
- ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/28]⎯
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/27]⎯

- ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/28]⎯
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/27]⎯

- ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[3/28]⎯
+ ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[3/27]⎯
```

This is not so important, it's just a bit messy.

@Boshen I'm not familiar with vitest, so not sure how best to tackle these.

### PR DESCRIPTION
**Pull request by Boshen**
closes #7704

### CODE REVIEW

**Comment by Boshen** [comment]
* **#7715** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7715?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Dunqing** [comment]
I think we should keep the error stack trace, as it is very helpful for testing and debugging.

**Comment by overlookmotel** [comment]
@Dunqing I agree, but `JsonReporter` doesn't seem to include stack traces anywhere in output. We'd probably need to write our own reporter from scratch.

**Comment by overlookmotel** [comment]
Scratch that. #7722 adds stack traces to snapshot.

**Pull request merged**
