### PR TITLE
perf(semantic): remove redeclare_variables

### PR DESCRIPTION
**Pull request by Dunqing**
I think we should remove the property used by a single rule

Now just a test

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2082** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2082?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2082?utm_source=stack-comment).

**Comment by Boshen** [comment]
Performance should be negligible because there aren't many re-declared variables.

I told the implementor to add this state because it's the easiest implementation. Happy to improve it.

**Comment by Dunqing** [comment]
> Performance should be negligible because there aren't many re-declared variables.
> 
> I told the implementor to add this state because it's the easiest implementation. Happy to improve it.

I have figured out how to implement this rule and be compatible with more cases, but I don't want to add anything to `semantic`, is it possible for us to make the `run` method support `&mut self`.

**Comment by Dunqing** [comment]
image

I am not certain if a 4% performance improvement can be achieved on every run

**Comment by Boshen** [comment]
> is it possible for us to make the run method support &mut self

Impossible. The linter assumes all states are stabilized, making it `mut` will be chaotic 😰

**Pull request closed without merging**
