### PR TITLE
refactor(transformer/react-refresh): calculate signature key once

### PR DESCRIPTION
**Pull request by Dunqing**
I can't remember why I wrote such code. This change reduced big allocation.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7970** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7970?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7970?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=7970).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by overlookmotel — APPROVED** [review]
Nice. Avoids allocating lots of `Atom`s into arena which never end up in the AST.

**Comment by overlookmotel** [comment]
### Merge activity

* **Dec 17, 12:11 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Dec 17, 12:11 PM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

**Comment by overlookmotel** [comment]
I think there's one further thing you could do if you wanted.

If I understand right (which maybe I don't), the values of `self.hook_calls` always end up being inserted into AST.

So instead of building a `Vec<CompactString>`, you could build a single `oxc_allocator::String` and push new keys onto the end of it. Then when you come to use it, convert to an `Atom` with `Atom::from(the_string.into_bump_str())`.

That remove *all* heap allocations, as the string is built entirely in the arena.

**Comment by overlookmotel** [comment]
Or, after #7973, can just do `Atom::from(arena_string)`.

**Comment by Dunqing** [comment]
> I think there's one further thing you could do if you wanted.
> 
> If I understand right (which maybe I don't), the values of `self.hook_calls` always end up being inserted into AST.
> 
> So instead of building a `Vec<CompactString>`, you could build a single `oxc_allocator::String` and push new keys onto the end of it. Then when you come to use it, convert to an `Atom` with `Atom::from(arena_string.into_bump_str())`.
> 
> That remove _all_ heap allocations, as the string is built entirely in the arena.

By default, we also need to hash the key by `sha1`, so we can't call `arena_string.into_bump_str()` directly
https://github.com/oxc-project/oxc/blob/67d255c15fcc0a2786497866e114131b71201e6b/crates/oxc_transformer/src/jsx/refresh.rs#L521-L530

**Comment by overlookmotel** [comment]
Ah I missed that. Doh!

Still, I think you could probably make a gain by replacing the `Vec<CompactString>` with a single `String` (`std`'s `String`, not `ArenaString`) which you push onto the end of each time a hook is found. That'd be 1 allocation rather than many, and no need for the `join` call at the end.

**Pull request merged**
