### PR TITLE
fix(linter): panic in consistent-function-scoping

### LINKED ISSUE #5608: Panic  `called Option::unwrap() on a None value` in `oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:188:50`
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
if(f)function f(){}
```

command
```
timeout -v 100 oxlint -D all -D nursery --import-plugin --jsdoc-plugin --jest-plugin --vitest-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin TEST___FILE.js --fix
```

cause this
```
thread '<unnamed>' panicked at crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:188:50:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/16921692/compressed.zip)

### PR DESCRIPTION
**Pull request by DonIsaac**
Closes #5608

### CODE REVIEW

**Comment by DonIsaac** [comment]
* **#5613** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5613?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by camc314** [comment]
@DonIsaac why was the symbol id `None` ?

**Comment by DonIsaac** [comment]
No idea. If there's a bug in semantic, it still needs fixing. Either way, the linter should not panic because of bugs in semantic.

**Comment by camc314** [comment]
> No idea. If there's a bug in semantic, it still needs fixing. Either way, the linter should not panic because of bugs in semantic.

agreed. although we have a lot of `.expect`s on getting symbol ids. e.x. https://playground.oxc.rs/#eNo9jtENwyAMRFdB/mqlqAMwQCfoApRC5QpMZIzUKGL3mqTJl30+3Tuv4MECRnOJVxMbecFCRuXVrB0mKGBX4EZj1IXEfcFGl2qYICEJWOGme/VlDqdY8rOkQwk7qrFw/gf7BLPjGnhDlsY+3DEFclkBIKHK7VO1ebcey+Aqn3EW0Oxo3bK6n+jj4MsrvMN4VkVGwoi71fsPwABQsA== panics inside `only_used_in_recursion.rs:226:56`, so might just be better to fix in semantic

**Comment by camc314** [comment]
maybe we should add debug asserts here for the `symbol_id == None` case

**Comment by Boshen** [comment]
This is they only case that makes it none, let me create an separate issue.

**Pull request merged**
