### PR TITLE
feat(transformer):  add ast changed hint in `InjectGlobalVariables`

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
here is a usage, https://github.com/rolldown/rolldown/blob/01197ec5548a091f8f1c1b6f112c1d30e883b0d9/crates/rolldown/src/utils/pre_process_ecma_ast.rs#L100-L106, 
this hint could avoid recreating semantic info, if the ast is not changed.

### CODE REVIEW

**Review by Boshen — COMMENTED** [review]
Need some tests.

**Comment by IWANABETHATGUY** [comment]
For every test, I add an extra assert to make sure if the ast changed, the `XXXXReturn.changed` is also needs to be `true`

**Comment by IWANABETHATGUY** [comment]
Seems noise, same as https://github.com/oxc-project/oxc/pull/7203#issuecomment-2463925786

**Comment by Dunqing** [comment]
It seems the plugin is not very complex, I suggest syncing the semantic rather than adding a state to indicate it's no change.

**Comment by IWANABETHATGUY** [comment]
> It seems the plugin is not very complex, I suggest syncing the semantic rather than adding a state to indicate it's no change.

Not sure this should do it with

**Pull request closed without merging**
