### PR TITLE
feat(linter): bad bitwise operator rule

### PR DESCRIPTION
**Pull request by mysteryven**
feat: #243 

I had thought that if I wanted to implement the rule, I would have to implement all the detail of this rule, but I didn't find the source code of this rule, so I only implement the cases I can think of.

I didn't implement the part that requires type inference, it will all pass:

```js
let a = '1'
a |= {} // should error, but current pass
```

Maybe it is not the right implementation, any advice is welcome!

### CODE REVIEW

**Comment by Boshen** [comment]
So far so good, request a review when you are done.

**Comment by mysteryven** [comment]
It's beyond my ability to implement type inference, I am not plan to do it in this PR, except it, It's ready for review.

**Comment by mysteryven** [comment]
It's beyond my ability to implement type inference, I am not plan to do it in this PR, except it, It's ready for review.

**Comment by Boshen** [comment]
Amazing work! Thank you so much for working on a rule that doesn't have existing tests!

**Comment by Boshen** [comment]
I ran this in the VSCode repo, it seems people love to work on bitflag enums 🤔 I may have to demote this to another category later on. But it's fine for now.

**Comment by Boshen** [comment]
> 

Another option is to only use this in js files.

**Pull request merged**
