### PR TITLE
fix: skip early error check for ts definition

### LINKED ISSUE #214: bug(linter): need to disable all early checks in `.d.ts`
`.d.ts` need not be checked due to it's a generated file, we don't care anything about it, which means we don't even need to read it in the linter cli.

### PR DESCRIPTION
**Pull request by mysteryven**
fix: #214

### CODE REVIEW

**Comment by Boshen** [comment]
Thank you for the PR! 

Does it make sense to not check `.d.ts` at all? We can filter it out if this is the case. 

https://github.com/Boshen/oxc/blob/3e3cbec1a8a303bae90d71dc79c425958f85d70e/crates/oxc_cli/src/lint/runner.rs#L120-L123

**Comment by Boshen** [comment]
Thank you for sponsoring as well! Much appreciated 😁

**Comment by mysteryven** [comment]
> Thank you for sponsoring as well! Much appreciated 😁

I really enjoy your [JavaScript parser tutorial](https://boshen.github.io/javascript-parser-in-rust/) and I admire your selflessness in contributing to open source community and helping others without expecting anything in return. You are a role model for me!

**Comment by mysteryven** [comment]
> Does it make sense to not check .d.ts at all

Maybe people create [global.d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html) for global scope:

```ts
interface myLib {
  arr: Array<string>;
       ^^^ Array type using 'Array<string>' is forbidden. Use 'string[]' instead.
}
```

[Playground](https://typescript-eslint.io/play/#ts=5.0.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgLYE8AywBGyDeAUMsnFFAFzICC5c6APAM5hSgDmAfANyEC+QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRREXAPbRI4MAF8QUoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

**Comment by Boshen** [comment]
> > Does it make sense to not check .d.ts at all
> 
> Maybe people create [global.d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html) for global scope:
> 
> ```ts
> interface myLib {
>   arr: Array<string>;
>        ^^^ Array type using 'Array<string>' is forbidden. Use 'string[]' instead.
> }
> ```
> 
> [Playground](https://typescript-eslint.io/play/#ts=5.0.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgLYE8AywBGyDeAUMsnFFAFzICC5c6APAM5hSgDmAfANyEC+QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRREXAPbRI4MAF8QUoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

Ok, let's merge and see how this turns out. Can you rebase to get the CI going?

**Comment by Boshen** [comment]
Thank you for your first contribution!

**Pull request merged**
