### PR TITLE
fix(semantic): function is value

### PR DESCRIPTION
**Pull request by ShuiRuTian**
`Function` should be `Value`

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
And a stupid question, just out of curious...

The implementation seems to refer typescript's design. Then why it is missed?

**Comment by Boshen** [comment]
This breaks many tests 🤔

**Comment by ShuiRuTian** [comment]
> This breaks many tests 🤔

Yeah, strange, investigating...

**Comment by Dunqing** [comment]
The `SymbolFlags` is port from `TypeScript` and did some adjustments to support `non-strict` checks. I have changed this in #7479 as well

**Pull request closed without merging**
