### PR TITLE
test(transformer/class-properties): more testing for assignment to `super[prop]`

### PR DESCRIPTION
**Pull request by overlookmotel**
Amend test added in #7991 to test transform of `super[prop] = value` where `prop` is not bound.

We should ideally have the `_unbound` temp vars *inside* the arrow function rather than outside, as Babel does, but that's not possible with our double-visitor scheme at present, and I think current output will operate correctly anyway.

Probably these temp vars could be hoisted even higher up - to very top level of the file, even if the class and `super[prop]` were deeply nested in many functions - and it'd still be correct. That'd be good for transformer performance as less `var` statements to insert, and also slightly smaller output size - less `var`s in code. But I don't know if that would be worse for runtime performance, as it makes the arrow function more impure. 🤔

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#7992** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7992?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7992?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=7992).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by overlookmotel** [comment]
We could also reduce size of output by adding more helpers.

e.g.:
* `super.prop += 123` -> `_superPropAdd(_Outer, unbound, 123)`
* `super.prop -= 123` -> `_superPropMinus(_Outer, unbound, 123)`
* `super.prop &&= 123` -> `_superPropAnd(_Outer, unbound, 123)`
* etc

Then no temp vars required at all.

**Comment by Dunqing** [comment]
> Just a thought for the future...
> 
> We could also reduce size of output by adding more helpers.
> 
> e.g.:
> 
> * `super.prop += 123` -> `_superPropAdd(_Class, "prop", 123)`
> * `super.prop -= 123` -> `_superPropMinus(_Class, "prop", 123)`
> * `super.prop &&= 123` -> `_superPropAnd(_Class, "prop", 123)`
> * etc
> 
> Then no temp vars required at all.
> 
> Same thing for lots of other transforms which currently produce very long output.
> 
> `foo() ?? bar()` -> `_isNullOrUndefined(_foo = foo()) ? bar() : _foo` or `_coalesce(foo(), () => bar())`

Yes, this is a good direction to reduce size of the transformation output

**Review by Dunqing — APPROVED** [review]

**Comment by Dunqing** [comment]
### Merge activity

* **Dec 18, 7:49 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Dec 18, 7:49 AM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

**Pull request merged**
