### PR TITLE
refactor(transformer): handle `<CWD>` in test runner

### PR DESCRIPTION
**Pull request by Dunqing**
We should move the handling of  `<CWD>` to the test runner because this is just only used in testing, and it causes us always get a path by `self.ctx.source_path` like `<CWD>/xxx/xxx.js`, we should get a real path for this.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7799** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7799?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7799?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by overlookmotel** [comment]
I would be very happy to see this change happen. The path manipulation in `TransformCtx::new` is one of the largest sources of variance in our transformer benchmarks, so removing it will help a lot with that.

But... just to check, does not stripping `options.cwd` from start of source path affect the output of JSX Source transform, which uses `source_path`?

**Comment by overlookmotel** [comment]
> Yes, it will.

Is that not a problem?

**Comment by Dunqing** [comment]
> > Yes, it will.
> 
> Is that not a problem?

It is not a problem, we should always get a real path except for testing

**Comment by overlookmotel** [comment]
Agreed we can remove the special case for `<CWD>`, but doesn't Babel remove `cwd` from start of the path?

i.e.:

```js
var _jsxFileName = "/src/foo/bar.jsx";
```

not full path:

```js
var _jsxFileName = "/Users/bozo/projects/clownhouse-app/src/foo/bar.jsx";
```

**Comment by overlookmotel** [comment]
OK great. Thanks for bearing with all my questions!

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
### Merge activity

* **Dec 12, 12:21 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Dec 12, 12:21 PM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

**Pull request merged**
