### PR TITLE
refactor(traverse): simplify `ChildScopeCollector` to use `enter_scope` method

### PR DESCRIPTION
**Pull request by Dunqing**
related: https://github.com/oxc-project/oxc/pull/4168

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#4688** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4688?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
The point of `ChildScopeCollector` is to get *direct* child scopes only. So each of the visitors records the `ScopeId` but then also does *not* call `walk_*` to continue traversal.

`ChildScopeCollector` is used when inserting a scope into middle of scope chain. We need only the direct child scopes, in order to alter their parent. More deeply nested scopes do not change their parent, so should not be collected.

This PR changes that behavior, which isn't correct.

**Comment by overlookmotel** [comment]
The point of `ChildScopeCollector` is to get *direct* child scopes only. So each of the visitors records the `ScopeId` but then also does *not* call `walk_*`, so they don't continue traversing deeper.

`ChildScopeCollector` is used when inserting a scope into middle of scope chain. We need only the direct child scopes, in order to alter their parent. More deeply nested scopes do not change their parent, so should not be collected.

This PR changes that behavior, which isn't correct.

**Comment by Dunqing** [comment]
> The point of `ChildScopeCollector` is to get _direct_ child scopes only. So each of the visitors records the `ScopeId` but then also does _not_ call `walk_*`, so they don't continue traversing deeper.
> 
> `ChildScopeCollector` is used when inserting a scope into middle of scope chain. We need only the direct child scopes, in order to alter their parent. More deeply nested scopes do not change their parent, so should not be collected.
> 
> This PR changes that behavior, which isn't correct.

Ah, I see, Is it possible to add a test to cover this incorrect behavior?

**Comment by overlookmotel** [comment]
> Is it possible to add a test to cover this incorrect behavior?

Well I'm hoping that as we add more test coverage to transformer, it'll get covered through imported test cases.

**Pull request closed without merging**
