### PR TITLE
refactor(website): rename fields in Playground from `flag` to `flags`

### PR DESCRIPTION
**Pull request by overlookmotel**
Part of #4991.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5033?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5033** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5033?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5032** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5032?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5031** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5031?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5030** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5030?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5028** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5028?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5027** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5027?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5026** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5026?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5025** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5025?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5024** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5024?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5023** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5023?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@DonIsaac I'm not familiar with playground, and I'm not sure if it's tested in CI. Does this look like it'd cause any problems?

**Comment by overlookmotel** [comment]
PS: This concludes my one-man war on "flag"!

**Comment by DonIsaac** [comment]
> @DonIsaac I'm not familiar with playground, and I'm not sure if it's tested in CI. Does this look like it'd cause any problems?

It's possible; I can test it out locally.

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
Approved, but please don't merge this yet

**Comment by overlookmotel** [comment]
> Approved, but please don't merge this yet

OK cool. I'm off for bed. I'm not sure of the reason for saying "don't merge this yet". If whatever question is the blocker is resolved, you have the energy/bandwidth, and you think the stack as a whole is OK, please can you merge it? But if any problems or queries outstanding, no worries - just let me know and I'll pick it up tomorrow.

**Comment by DonIsaac** [comment]
LGTM
image

**Pull request merged**
