### PR TITLE
chore(linter/vitest): improve docs for vitest rules

### PR DESCRIPTION
**Pull request by shulaoda**
Please fill in the "why this is bad" section

_Originally posted by @DonIsaac in https://github.com/oxc-project/oxc/pull/5360#discussion_r1739617907_

### CODE REVIEW

**Comment by shulaoda** [comment]
Should we wrap the document to make it clearer?

**Comment by DonIsaac** [comment]
Beautiful.

**Comment by DonIsaac** [comment]
Lmk when you're done making changes and I'll merge this.

**Comment by shulaoda** [comment]
> Lmk when you're done making changes and I'll merge this.

I don't know how many lengths are suitable, perhaps we can also write a rule for this. I followed the rule you wrote before.

**Review by DonIsaac — APPROVED** [review]

**Pull request merged**
