### PR TITLE
refactor(transformer): convert `ModuleImports` into common transform

### PR DESCRIPTION
**Pull request by overlookmotel**
An alternative version of #6177.

Convert `ModuleImports` into a common transform. Works much as before, but it inserts `import` / `require` statements by passing them to `TopLevelStatements` common transform, so they get inserted in one go with any other inserted top-level statements. This avoids shuffling up the `Vec<Statement>` multiple times, which can be slow with large files.

`VarDeclarations` also inserts any declarations via `TopLevelStatements` but runs after `ModuleImports`, so can control whether a `var` statement is inserted before or after `import` statements by inserting it via `VarDeclarations` (to appear after `import` statements) or directly into `TopLevelStatements` (to appear before `import` statements). Insertion order is not actually important, but allows us to match Babel's output and pass its tests.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6186?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6186** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#6185** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6185?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6184** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6183** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@Dunqing I'm sorry to interrupt your holiday to request your review. But I thought it would be rather rude to just merge it myself, as it's an alternative version of your PR! But if you're busy/enjoying time off, feel free to just give it a swift look and say "OK", or say "I don't have time for this" and we can look at it when you're free. No great hurry.

**Review by Dunqing — DISMISSED** [review]
LGTM

**Review by Dunqing — APPROVED** [review]
LGTM

**Pull request merged**
