### PR TITLE
WIP: react-hooks/exhaustive-deps

### PR DESCRIPTION
**Pull request by alisnic**
I gotta be honest with you - I don't know Rust much and this may be too much for me. But I decided at least I can move things forwarding by creating the scaffolding and porting the tests

Related to #2174

### CODE REVIEW

**Comment by alisnic** [comment]
@Boshen pushed my latest code. Currently stuck by 2 things:

1. How do I check that the identifier `id` is defined within the component scope? So I don't generate false positives
```
function Counter() {
  let [count, setCount] = useState(0);

  function increment(x) {
    return x + 1;
  }

  useEffect(() => {
    let id = setInterval(() => {
      setCount(increment);
    }, 1000);
    return () => clearInterval(id);
  }, []);

  return <h1>{count}</h1>;
}

```

2. Given a `AstNode`, how to check that is it used inside of an expression that is assigned to itself?

```
function Example() {
  const foo = useCallback(() => {
    foo();
  }, []);
}
=
```

**Comment by alisnic** [comment]
I think I need a completely different approach here. Instead I should iterate over all identifier references and traverse the tree upwards to detect whether I'm in a hook or not. This should remove most of traversal boilerplate I wrote

**Comment by Boshen** [comment]
This rule is pretty complicated, let's see whether @rzvxa can help. Feel free to ask questions.

**Comment by rzvxa** [comment]
> I think I need a completely different approach here. Instead I should iterate over all identifier references and traverse the tree upwards to detect whether I'm in a hook or not. This should remove most of traversal boilerplate I wrote

Hey mate, First off thanks for this impressive work.

I was reading through the code when I got an idea that might make it easier to implement, Have you tried to create a custom visitor instead of using the `check_statements` function?

If you add something like this:

```rust
#[derive(Default)]
struct DependencyCollector<'a> {
    deps: DependencyList<'a>,
}

impl<'a> Visit<'a> for DependencyCollector<'a> {
    fn visit_identifier_reference(&mut self, ident: &IdentifierReference<'a>) {
        self.deps.into(/* dependency */);
    }
    /* .... */
}
```

and use it like this:

```rust
DependencyCollector::default().visit_statements(&body_expr.statements);
```

instead of calling the `check_statement`, It can abstract away most of the walk functions you've used and as a result make it less cluttered and easier to read/write.

I think it can result in what you want from visiting every identifier, I'm not sure which one is more performant though, Since one skips redundant checks but requires additional visits and the other one has a lot of redundant checks and no additional visit.

**Comment by rzvxa** [comment]
> 1. How do I check that the identifier `id` is defined within the component scope? So I don't generate false positives
> 
> 
> ```
> function Counter() {
>   let [count, setCount] = useState(0);
> 
>   function increment(x) {
>     return x + 1;
>   }
> 
>   useEffect(() => {
>     let id = setInterval(() => {
>       setCount(increment);
>     }, 1000);
>     return () => clearInterval(id);
>   }, []);
> 
>   return <h1>{count}</h1>;
> }
> ```

Given the scope_id of the `id` and the scope id for `Counter`, Can't we just check recursively whether this scope id has a direct ancestor which is the `Counter`?

But we have to check `ScopeFlags` and look for any shadowed variable in our path.

Maybe it can be easier if you go for checking the `SymbolId` instead of `ScopeId`s.

**Comment by alisnic** [comment]
> I was reading through the code when I got an idea that might make it easier to implement, Have you tried to create a custom visitor instead of using the `check_statements` function?

How would this approach be different from:

```rust
    ctx.semantic().nodes().iter().for_each(|node| {
            let AstKind::IdentifierReference(iref) = node.kind() else { return };
            // do stuff
        })
```

Will the visitor visit nodes that the iter above would not?

**Comment by rzvxa** [comment]
> > I was reading through the code when I got an idea that might make it easier to implement, Have you tried to create a custom visitor instead of using the `check_statements` function?
> 
> How would this approach be different from:
> 
> ```rust
>     ctx.semantic().nodes().iter().for_each(|node| {
>             let AstKind::IdentifierReference(iref) = node.kind() else { return };
>             // do stuff
>         })
> ```
> 
> Will the visitor visit nodes that the iter above would not?

I know there are some types missing from `AstKind` but to be honest I'm not sure if any of the vital ones are missing.

If there is nothing important missing in the `AstKind` then yeah your snippet above would basically do the same thing. But here is the thing, You didn't use the nodes iterator, Instead you rely on [this recursive function](https://github.com/oxc-project/oxc/pull/2637/files#diff-839f60262eb522a19bb4abd48a6928d15659d5e02d0603a7a12a43242daaba93R329-R406) which doesn't support all types containing an `IdentifierReference` - can't recall the exact type but I remember noticing one missing in my initial review - We are most probably going to use codegen for our visitors/AST since it is growing in complexity so using them would reduce the risk of human error.

Just to point out, We recently found out some types are missing a visit event in our Visit trait, So you can see even core stuff can be wrong when written by humans(since the visitor pattern is tedious and has a lot of boilerplate code).

But feel free to use either one of these approaches since they should perform the same.

**Comment by alisnic** [comment]
Hey guys, if anyone else wants to continue working on this please feel free. I thought I would be able to give it more time, but unfortunately I can't. My second child will be born soon so my attention it switched to other pressing matters 😄

**Comment by rzvxa** [comment]
> Hey guys, if anyone else wants to continue working on this please feel free. I thought I would be able to give it more time, but unfortunately I can't. My second child will be born soon so my attention it switched to other pressing matters 😄

WOW, Congrats!

I'll pick it up in the future, And thanks for all the work you've done on this rule, I'll make sure you get credited as the co-author.

I'll announce when I start working on this issue so to anyone who wants to work on this, Until then feel free to propose a PR either based on this or written from scratch.

**Comment by overlookmotel** [comment]
@rzvxa I'm not clear how far off completion this is. If it's require a lot of work to finish off, shall we close it?

**Comment by rzvxa** [comment]
> @rzvxa I'm not clear how far off completion this is. If it's require a lot of work to finish off, and no obvious prospect of that happening in near future, shall we close it?

I'm not sure about the correctness of it - as I haven't really reviewed it in depth - but it contains tremendous amount of work, And all the tests(I assume).

It wouldn't hurt to keep it open, Or merge it without adding it to the rules. Either way we should make sure to credit the original author.

**Comment by alisnic** [comment]
Don't worry about credit guys, do what suits you best

**Comment by tutturen** [comment]
The rule **react-hooks/exhaustive-deps** is the last missing piece for us to switch over to oxlint exclusively. Much needed!
I would like to help moving it forward, but I don't yet have any experience with oxc. And to be honest, it seems fairly complicated.

By the way, great work @alisnic and congrats with your second child!

**Comment by camc314** [comment]
going to take a look at this

**Comment by Boshen** [comment]
Continue in https://github.com/oxc-project/oxc/pull/7151

**Pull request closed without merging**
