### PR TITLE
feat(linter) eslint-plugin-unicorn no await in promise methods

### PR DESCRIPTION
**Pull request by camc314**

### CODE REVIEW

**Comment by camc314** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2963?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2963** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2963?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2962** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2962?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camc314 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Dunqing — APPROVED** [review]
Thanks!

**Comment by Dunqing** [comment]
### Merge activity

* **Apr 13, 10:38 PM EDT**: @Dunqing started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2963).

**Comment by Boshen** [comment]
Thank you and welcome back again! These are some really nice correctness rules!

**Pull request merged**
