### PR TITLE
perf(semantic): calculate number of nodes, scopes, symbols, references before visiting AST

### PR DESCRIPTION
**Pull request by Dunqing**
context: #4328

### CODE REVIEW

**Comment by DonIsaac** [comment]
Please hold on from merging this for a few days; I'm testing some things out locally.

**Comment by DonIsaac** [comment]
NVM, storing statistics in AstBuilder is more trouble than it's worth. Borrow checking woes. Merge whenever.

**Review by DonIsaac — APPROVED** [review]

**Comment by overlookmotel** [comment]
Can I make 1 suggestion: Before we get to point of merging, I'd suggest temporarily changing the `debug_assert!`s to `assert!`s so conformance suite runs with those assertions active (conformance is compiled in release mode so `debug_assert!` won't run). If there are any more counter bugs lurking, that'd likely flush them out.

**Comment by Dunqing** [comment]
> Can I make 1 suggestion: Before we get to point of merging, I'd suggest temporarily changing the `debug_assert!`s to `assert!`s so conformance suite runs with those assertions active (conformance is compiled in release mode so `debug_assert!` won't run). If there are any more counter bugs lurking, that'd likely flush them out.

Good suggestion! I saw you already retain `debug_assert!` in conformance in #4386. So do I need to change anything else?

**Comment by overlookmotel** [comment]
> Good suggestion! I saw you already retain `debug_assert!` in conformance in #4386. So do I need to change anything else?

#4386 is now merged, so my previous comment is now irrelevant. If you rebase on main, it'll reveal whether anything in the conformance tests causes the counts to be wrong.

**Comment by overlookmotel** [comment]
Conformance passes! I'll take a look at this shortly.

**Comment by Dunqing** [comment]
> Conformance passes! I'll take a look at this shortly.

Feel free to add more docs to this PR if you want

**Comment by overlookmotel** [comment]
@Dunqing I'd like to suggest a bunch of changes which are all cosmetic - just naming and comments etc.

Rather than writing them up as a review, would you mind if I just push a bunch of commits to this branch? You can revert any you don't like.

**Comment by Dunqing** [comment]
> @Dunqing I'd like to suggest a bunch of changes which are all cosmetic - just naming and comments etc.
> 
> Rather than writing them up as a review, would you mind if I just push a bunch of commits to this branch? You can revert any you don't like.

Go for it. I always like your revised code.😁

**Comment by overlookmotel** [comment]
Thanks. I've pushed 7 commits. Please take a look and see if you're happy with them.

Now the cosmetic stuff is done, I'm reviewing the meat of the PR. Please don't merge yet.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
@Dunqing I've reviewed the whole PR and tested out the wacky parts with e.g. `<foo.bar />`, `<foo:bar />` and `enum X { [f()] = 1, 'Q1' = 2 }`. Counts are still accurate in these edge case - it all seems to work!

If you're happy with the changes in extra commits I pushed, please go ahead and merge. If you're not, please let me know (do feel free to argue if you don't like what I've done).

**Comment by Dunqing** [comment]
> If you're happy with the changes in extra commits I pushed, please go ahead and merge. If you're not, please let me know (do feel free to argue if you don't like what I've done).

I am happy with your changes!! Let's merge it

**Comment by overlookmotel** [comment]
30% speed-up landed! 🎉 🎉 🎉 Nice one Dunqing.

**Pull request merged**
