### PR TITLE
feat(linter): eslint-plugin-jest/valid-expect-in-promise

### PR DESCRIPTION
**Pull request by eryue0220**
part of https://github.com/oxc-project/oxc/issues/492

Rule Detail: [link](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/valid-expect-in-promise.ts)

The last recommend rules of eslint-plugin-jest. But there're still many test cases to fix.

### CODE REVIEW

**Comment by DonIsaac** [comment]
@eryue0220 any updates on this PR?

**Comment by eryue0220** [comment]
> @eryue0220 any updates on this PR?

No, previously @mysteryven said that something may has changed in `jest` rule, and can continue to implement other jest's rules except `valid-expect-in-promise`. 

More detail: https://github.com/oxc-project/oxc/pull/3358#issuecomment-2119649800

**Comment by mysteryven** [comment]
> any updates on this PR?

I am lack of time recently, you are welcome to continue working on it if you like.

**Comment by eryue0220** [comment]
> > any updates on this PR?
> 
> I am lack of time recently, you are welcome to continue working on it if you like. 😁

Okay, I'll back for this PR.

**Comment by Boshen** [comment]
@mysteryven no longer have the time to do what he wants to do. @eryue0220 are you still available to clean up this PR?

**Comment by eryue0220** [comment]
@Boshen Sorry, I'm also not available recently, if anyone wants to contribute on it, I will close this.

**Comment by Boshen** [comment]
Ok let's close for now.

**Pull request closed without merging**
