### PR TITLE
ci: pin github action versions

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
* **#7826** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7826?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7826?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=7826).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Boshen** [comment]
https://docs.renovatebot.com/modules/manager/github-actions/ seems like the best approach to version pinning.

**Comment by AaronDewes** [comment]
In my opinion, pinning to a more exact tag does not provide more security.

Someone manipulating the action could still probably force-push (unless GitHub actions prevents this somehow, but I don't think so).

https://woodruffw.github.io/zizmor/audits/#unpinned-uses

zizmor's pendantic mode requires you to pin to a specific commit. I would recommend doing that instead and set up a tool to automatically bump that commit hash to the latest stable release instead.

**Comment by Boshen** [comment]
I'm pinning these versions first in preparation for renovate bot to work.

**Pull request merged**
