### PR TITLE
test: reduce size of vec

### PR DESCRIPTION
**Pull request by Dunqing**
related: https://github.com/oxc-project/oxc/issues/9706

TEST ONLY!

Everything is hard-coded, just for testing

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#6488** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6488?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
Need to measure memory change.

**Comment by Boshen** [comment]
First phase should not introduce breaking change. Only change the underlying `u64`s to `u32`.

**Comment by Dunqing** [comment]
> First phase should not introduce breaking change. Only change the underlying `u64`s to `u32`.

I have changed the underlying `usize` to `u32` in this PR and have saved the original changes in `back-reduce-size-of-vec` branch

**Comment by Boshen** [comment]
Close as stale. 

This experimentation is successful, just need the time to land this properly.

**Pull request closed without merging**
