### PR TITLE
fix(linter/no-control-regex): better diagnostic messages

### PR DESCRIPTION
**Pull request by DonIsaac**
1. Handle plural/singular cases in message and help text
2. Shrink spans in `RegExp` constructors to only cover the regular expression itself.

### CODE REVIEW

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6530?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6530** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6530?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#6529** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6528** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6527** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by camc314 — APPROVED** [review]

**Review by camchenry — APPROVED** [review]
Nice, this is better than the eslint diagnostics now 👍

**Comment by camc314** [comment]
### Merge activity

* **Oct 13, 3:29 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by pumano** [comment]
looks like issue not closed after merge

**Pull request merged**
