### PR TITLE
chore(clippy): disable nursery group rules

### PR DESCRIPTION
**Pull request by Dunqing**
#2318

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #2319** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2319?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2319?utm_source=stack-comment).

**Comment by hyf0** [comment]
I guess what you need to do is deleting this line

https://github.com/oxc-project/oxc/blob/d571839ab8f0f99fefc9127468a876cf300d4c6b/Cargo.toml#L43

**Review by Boshen — CHANGES_REQUESTED** [review]
Remove it from workspace lints in Cargo.toml

**Comment by Dunqing** [comment]
> nursery = { level = "warn", priority = -1 }

Yes, Thank you!

**Review by Boshen — APPROVED** [review]

**Pull request merged**
