### PR TITLE
fix(codegen): correct sourcemaps when unicode chars

### PR DESCRIPTION
**Pull request by overlookmotel**
#2565 added source map support in codegen. But there was a bug in creating the line offset tables for Unicode. This PR fixes that.

This function could probably be made more efficient, but I think this at least makes it correct.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#2583** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
One thing I'm not sure about:

If source is `"Ö"` (2 bytes in UTF-8, but 1 UTF-16 char):

* Position 0 maps to line 0, column 0.
* Position 2 maps to line 0, column 1.

But what should position 1 map to? (it's in middle of the character) Currently it maps to line 0, column 0 i.e. the *start* of the character.

**Comment by overlookmotel** [comment]
The speed-up is an incidental benefit. Previously it was writing too many values to `columns`.

**Comment by Boshen** [comment]
The 4 PRs, a learning opportunity for you @underfin 😁

**Comment by Boshen** [comment]
### Merge activity

* **Mar 3, 11:22 PM EST**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2583).

**Pull request merged**
