### PR TITLE
feat(transformer): add react plugins

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2867?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2867** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2867?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2866** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2866?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Boshen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
While going through this I learned that we'll need to add a cli, and support presets and targets from the very beginning :-)

**Comment by Dunqing** [comment]
> While going through this I learned that we'll need to add a cli, and support presets and targets from the very beginning :-) Scope creep!

In what scenarios is cli currently needed?

**Review by Dunqing — APPROVED** [review]

**Comment by Boshen** [comment]
### Merge activity

* **Mar 30, 8:49 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2867) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
