### PR TITLE
fix(codegen): do not print parenthesis for `in` expression in ArrowFunctionExpression

### PR DESCRIPTION
**Pull request by Dunqing**
Please check out [esbuild](https://esbuild.github.io/try/#dAAwLjI0LjAAACgpID0+ICIiIGluIHt9)

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7360** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7360?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7360?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Dunqing** [comment]
Executing https://github.com/oxc-project/monitor-oxc/actions/runs/11914971455

**Comment by Dunqing** [comment]
> Executing https://github.com/oxc-project/monitor-oxc/actions/runs/11914971455

Only test262 failed and seems not related to this change

**Comment by Boshen** [comment]
### Merge activity

* **Nov 19, 9:28 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
