### PR TITLE
feat: vscode extension

### PR DESCRIPTION
**Pull request by cijiugechu**
related: #688 .
There are some unfinished things that need to be finalised by Boshen.

1. Official icon and description for the package.
2. Publishing strategy ( It's probably not a good idea to use `package.json` as a probe to publish extension, as there's too much vscode configuration coupled to it, a git tag like `vscode_v0.0.x` might be worth considering ).
3. License for the extension.

### CODE REVIEW

**Review by Boshen — COMMENTED** [review]
Can you add a little README detail how to run this thing? I don't even have vscode installed yet 😅

**Review by Boshen — DISMISSED** [review]
Oh I saw it now. Let me get someone to test it.

**Comment by mysteryven** [comment]
It's really really cool!

Just some questions:

1. Not family with VSCode Plugin, there is an 'any', is it some wrong?
CleanShot 2023-08-06 at 16 12 47@2x

2. Quick fix not work for me:

```js
describe.only('foo', () => { });
// expect to be 
// fix to be: `;`
```

```js
null==null
// expect to be 'null === null'
// fix to be ' === '
```

`cmd + .`  not work for me. Maybe some wrong with my VSCode config?

CleanShot 2023-08-06 at 16 24 16@2x

3. what about we make this area fixed 🙂:

CleanShot 2023-08-06 at 16 20 58@2x

**Comment by mysteryven** [comment]
If you think this area is not convenient for communication. We can also chat in our [discord channel](https://discord.gg/xEzvuZR2). I'd like to help you test this plugin!

**Comment by cijiugechu** [comment]
> It's really really cool!
> 
> Just a few questions:
> 
> 1. Not family with VSCode Plugin, there is an 'any', is it some wrong?
>    CleanShot 2023-08-06 at 16 12 47@2x
> 2. Quick fix not work for me:
> 
> ```js
> describe.only('foo', () => { });
> // expect to be 
> // fix to be: `;`
> ```
> 
> ```js
> null==null
> // expect to be 'null === null'
> // fix to be ' === '
> ```
> 
> `cmd + .` not work for me. Maybe some wrong with my VSCode config?
> 
> CleanShot 2023-08-06 at 16 24 16@2x
> 3. what about we make this area fixed 🙂:
> 
> CleanShot 2023-08-06 at 16 20 58@2x

Thank you very much for the comprehensive test! 
1. This information does not come from oxc extension, in fact, `any` can be seen in editors without the oxc extension activated, because vscode is distributed with tsc.
屏幕截图(54)
2.
  a. `Quick fix` does not come from oxc extension, we can observe that its `source` attribute is `system`, all the oxc commands are prefixed with `Oxc`, you can use command palette and input `oxc` to use oxc commands:
屏幕截图(53)
  b. `null==null` will be fixed to `' === '`, which should be a bug, I forgot to distinguish the difference between delete and replace range.
3. I'm not quite sure what exactly is being referred to here, can you give more descriptive information, thanks.

**Comment by cijiugechu** [comment]
The fixer has been fixed!

**Comment by mysteryven** [comment]
> I'm not quite sure what exactly is being referred to here, can you give more descriptive information, thanks.

It's just my personal option. My meaning is let the action area (referred by the arrow, and where quick fixed and view problem placed) addressed at the footer of this dialog, so I can directly press shortcuts of actions. But it's simply a small question as I want to discuss with you, doesn't need to change!

https://github.com/web-infra-dev/oxc/assets/33973865/5db51576-b23f-45da-bdd1-03641602cffb

**Comment by cijiugechu** [comment]
> > I'm not quite sure what exactly is being referred to here, can you give more descriptive information, thanks.
> 
> It's just my personal option. My meaning is let the action area (referred by the arrow, and where quick fixed and view problem placed) addressed at the footer of this dialog, so I can directly press shortcuts of actions. But it's simply a small question as I want to discuss with you, doesn't need to change!
> 
>  CleanShot.2023-08-06.at.19.37.15.mp4

I don't know if it's a vscode issue, but after enabling eslint extension, using ctrl+. still does not produce any reaction.

**Comment by mysteryven** [comment]
> I don't know if it's a vscode issue, but after enabling eslint extension, using ctrl+. still does not produce any reaction.

https://github.com/web-infra-dev/oxc/assets/33973865/0c250555-f30b-4c91-8cf1-a723cf425ad0

I press `ctrl + .` firstly in this video, it shows a quick fix dialog. Next, I press `Enter`, it fixes this error.

You can try this piece of code: https://stackblitz.com/edit/vitejs-vite-xecdjv?file=main.js 😉

**Comment by mysteryven** [comment]
I have no more questions. Do you have anything want to add?

**Comment by cijiugechu** [comment]
> I have no more questions. Do you have anything want to add?

That will be all for now. We can revisit adding this functionality once we have a clearer understanding of how the quickfix shortcuts work. Thank you for your patience while testing!

**Review by Boshen — APPROVED** [review]

**Comment by Boshen** [comment]
Thank you so much @cijiugechu, and @mysteryven for testing this.

I'll block sometime later and figure out how to publish this. Probably sometime after I finish the resolver.

**Comment by cijiugechu** [comment]
> Thank you so much @cijiugechu, and @mysteryven for testing this.
> 
> I'll block sometime later and figure out how to publish this. Probably sometime after I finish the resolver.

We can refer to [this section of the documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions) and [this workflow](https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml) to publish platform-specific binary packages.

**Pull request merged**
