### PR TITLE
improvement(semantic/cfg): better `break` and `continue` flow.

### PR DESCRIPTION
**Pull request by rzvxa**
This PR adds a new edge type called `Jump` to distinguish between normal edges and jumps.
There is also a control flow context which is used to keep track of cfg scopes and labels. It replaces the old `preserve_state` and `restore_state`.
It corrects some mistakes - such as labeled blocks especially labeled continue which wasn't easy to implement with the old approach - in the old control flow but other than that it is mostly refactored to have a more declarative API instead of a procedural approach.

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3462?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3462** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3462?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3453** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3453?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#3238](https://github.com/oxc-project/oxc/pull/3238) <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3238?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#3454](https://github.com/oxc-project/oxc/pull/3454) <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3454?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#3452** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3452?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3451** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3451?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3381** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3381?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3407** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3407?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
I sometimes don't understand how graphite works, why is conflicting on everything 🤔

**Comment by rzvxa** [comment]
> I sometimes don't understand how graphite works, why is conflicting on everything 🤔

I don't know why it was conflicting either, I've restacked it and it went without any conflicts. It might be the `rerere` that took care of that, I'm not sure.

**Comment by rzvxa** [comment]
Nope, seems like there is still something wrong, I'll fix it and let you know.

**Comment by rzvxa** [comment]
@Boshen OK, I can confirm it was the `rerere` that resolved the conflict, and the error mentioned in the previous comment was just my old mistake getting auto-repeated. Now it should be good to go.

**Pull request merged**
