### PR TITLE
feat(transformer/class-properties): transform super call expression that is inside static prop initializer

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7831?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7831** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7831?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7831?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#7830** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7830?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=7831).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by overlookmotel — APPROVED** [review]
Pushed 3 commits with small things.

@Dunqing Going to merge and Github will squash the commits, so I've put them on [overlookmotel/7831-unsquashed branch](https://github.com/oxc-project/oxc/compare/main...overlookmotel/7831-unsquashed) if you want to see what I did. Please delete that branch after you've looked at it (if you want to).

One note: If I buy a dog, then I am the "owner" of the dog. The dog is "owned" by me. So `owned_arguments` is a better description than `arguments_owner` here. We have taken ownership of the arguments, like I took ownership of the dog, so the arguments are "owned".

**Comment by overlookmotel** [comment]
### Merge activity

* **Dec 13, 8:46 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by Dunqing** [comment]
> One note: If I buy a dog, then I am the "owner" of the dog. The dog is "owned" by me. So `owned_arguments` is a better description than `arguments_owner` here. We have taken ownership of the arguments, like I took ownership of the dog, so the arguments are "owned".

Thanks for describing this, it's useful for me!

**Pull request merged**
