### PR TITLE
fix(types)!: append `rest` field into `elements` for objects and arrays to align with estree

### PR DESCRIPTION
**Pull request by ottomated**
Fixes https://github.com/oxc-project/oxc/pull/7149#discussion_r1831677446 and removes the need for some manual typescript.

### CODE REVIEW

**Comment by ottomated** [comment]
* **#7212** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7212?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ottomated and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
### Merge activity

* **Nov 9, 12:22 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by Boshen** [comment]
Thank you! 1 step closer to estree ❤️

**Comment by overlookmotel** [comment]
Great stuff! Thank you.

**Pull request merged**
