### PR TITLE
refactor(linter): use "parsed pattern" in `no_div_regex` rule.

### PR DESCRIPTION
**Pull request by rzvxa**
Part of #5416, Paves the road for upcoming refactors by adding the `oxc_regular_expression` dependency and a helper method for ease of access.

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5417?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5417** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5417?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5256** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5256?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5280** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5278** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5278?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5304** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5304?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
The `autofix` issue will be fixed via https://github.com/oxc-project/oxc/pull/5256#issuecomment-2325364910

**Comment by rzvxa** [comment]
@Boshen Why autofix task keep failing? Do you have any idea why it might be?

**Review by DonIsaac — APPROVED** [review]

**Comment by rzvxa** [comment]
Restacked PR, Adding merge label without review as it was already approved before the merge conflict happened.

**Pull request merged**
