### PR TITLE
feat(linter): eslint-plugin-jest rule `prefer-spy-on`

### PR DESCRIPTION
**Pull request by eryue0220**
Rule Detail: [link](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/prefer-spy-on.ts)

### CODE REVIEW

**Comment by mysteryven** [comment]
If you are blocked by the fixer, it's fine to merge it first and iterate over it later :)

**Comment by eryue0220** [comment]
> If you are blocked by the fixer, it's fine to merge it first and iterate over it later :)

Sorry for the late response, it's complete.

**Review by mysteryven — APPROVED** [review]
Awesome work!

**Review by mysteryven — APPROVED** [review]
Awesome work!

**Review by mysteryven — APPROVED** [review]
Awesome work!

**Pull request merged**
