### PR TITLE
chore(transformer): enable `class-properties` plugin

### PR DESCRIPTION
**Pull request by Dunqing**
Done!

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#7750** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7750?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7750?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Dunqing** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12268946323

**Comment by Dunqing** [comment]
https://github.com/oxc-project/monitor-oxc/actions/workflows/ci.yml

**Comment by Dunqing** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12271863610

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12338396809

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12404732417

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12432442576

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12434465731

**Comment by Dunqing** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12525387408

**Comment by Dunqing** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/12558692378/job/35013360746

**Pull request merged**
