### PR TITLE
feat(linter): generate schemas for rules (with documentation)

### PR DESCRIPTION
**Pull request by DonIsaac**
Re-creation of #4151.

@Boshen I'm not sure what we want to do about `configuration_schema.json`, should we add a `prepublish` task to create it within `oxlint`?

### CODE REVIEW

**Comment by Boshen** [comment]
>  I'm not sure what we want to do about configuration_schema.json, should we add a prepublish task to create it within oxlint?

I'll take a look at this today.

**Comment by Boshen** [comment]
Do you think it's reasonable to only generate the minimum? 

https://github.com/SchemaStore/schemastore/blob/314c1867bd5db7d139804fa40b18d454132921af/src/schemas/json/eslintrc.json#L39-L42

**Comment by DonIsaac** [comment]
> Do you think it's reasonable to only generate the minimum? 
> 
> 
> 
> ```json
> 
>         "comma-dangle": {
> 
>           "$ref": "#/definitions/rule",
> 
>           "description": "Require or disallow trailing commas"
> 
>         },
> 
> ```
> 
> 
> 
> https://github.com/SchemaStore/schemastore/blob/314c1867bd5db7d139804fa40b18d454132921af/src/schemas/json/eslintrc.json#L39-L42

Unfortunately, I'm not sure how to get that... rules only have documentation, not a summary.

**Comment by DonIsaac** [comment]
@Boshen what would you like to do with this PR?

**Comment by Boshen** [comment]
Shall we try and clean up the schema incrementally? It's difficult to review and merge this PR.

**Pull request closed without merging**
