### PR TITLE
refactor(codegen): print indentation before directive

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#3512** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3512?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
This doesn't look right, this changed the strings to directives.

**Comment by Dunqing** [comment]
> This doesn't look right, this changed the strings to directives.

I've been rethinking this and it really isn't right. BTW, I noticed that `swc` is handled that way.

**Comment by Dunqing** [comment]
And then do some stuff in transformer to fix `compiler/sourceMapValidationClasses.ts`

**Pull request merged**
