### PR TITLE
fix(linter): fix panic in fixer for `oxc/only-used-in-recursion`

### LINKED ISSUE #6068: Panic when linting in `crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs`
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
//¿
function writeChunks(a,callac){writeChunks(m,callac)}writeChunks(i,{})
```

command
```
timeout -v 150 oxlint -D all -D nursery --import-plugin --jsdoc-plugin --jest-plugin --vitest-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin TEST___FILE.js --fix
```

cause this
```
thread '<unnamed>' panicked at crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs:239:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/option.rs:2006:5
   4: core::option::Option<T>::unwrap
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/option.rs:969:21
   5: oxc_linter::rules::oxc::only_used_in_recursion::skip_to_next_char
             at ./oxc-main/crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs:239:34
   6: <oxc_linter::rules::oxc::only_used_in_recursion::OnlyUsedInRecursion as oxc_linter::rule::Rule>::run::{{closure}}
             at ./oxc-main/crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs:148:41
   7: oxc_linter::context::LintContext::diagnostic_with_fix_of_kind
             at ./oxc-main/crates/oxc_linter/src/context/mod.rs:265:37
   8: oxc_linter::context::LintContext::diagnostic_with_dangerous_fix
             at ./oxc-main/crates/oxc_linter/src/context/mod.rs:251:9
   9: <oxc_linter::rules::oxc::only_used_in_recursion::OnlyUsedInRecursion as oxc_linter::rule::Rule>::run
             at ./oxc-main/crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs:106:25
  10: oxc_linter::Linter::run
             at ./oxc-main/crates/oxc_linter/src/lib.rs:143:17
  11: oxc_linter::service::Runtime::process_source
             at ./oxc-main/crates/oxc_linter/src/service.rs:399:9
  12: oxc_linter::service::Runtime::process_path
             at ./oxc-main/crates/oxc_linter/src/service.rs:266:17
  13: oxc_linter::service::LintService::run::{{closure}}
             at ./oxc-main/crates/oxc_linter/src/service.rs:106:59
  14: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map_with.rs:304:27
  15: <&rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/par_bridge.rs:145:30
  16: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  17: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:473:31
  18: rayon_core::join::join_context::call_a::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:124:17
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panic/unwind_safe.rs:272:9
  20: std::panicking::try::do_call
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:557:40
  21: std::panicking::try
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:520:19
  22: std::panic::catch_unwind
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panic.rs:348:14
  23: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  24: rayon_core::join::join_context::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:142:24
  25: rayon_core::join::join_context
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:132:5
  26: rayon::iter::plumbing::bridge_unindexed_producer_consumer
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:472:51
  27: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:473:31
  28: rayon_core::join::join_context::call_a::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:124:17
  29: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panic/unwind_safe.rs:272:9
  30: std::panicking::try::do_call
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:557:40
  31: std::panicking::try
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:520:19
  32: std::panic::catch_unwind
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panic.rs:348:14
  33: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  34: rayon_core::join::join_context::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:142:24
  35: rayon_core::join::join_context
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:132:5
  36: rayon::iter::plumbing::bridge_unindexed_producer_consumer
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:472:51
  37: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:473:31
  38: rayon_core::join::join_context::call_a::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:124:17
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panic/unwind_safe.rs:272:9
  40: std::panicking::try::do_call
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:557:40
  41: std::panicking::try
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:520:19
  42: std::panic::catch_unwind
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panic.rs:348:14
  43: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  44: rayon_core::join::join_context::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:142:24
  45: rayon_core::join::join_context
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/join/mod.rs:132:5
  46: rayon::iter::plumbing::bridge_unindexed_producer_consumer
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:472:51
  47: rayon::iter::plumbing::bridge_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/plumbing/mod.rs:451:5
  48: <rayon::iter::par_bridge::IterBridge<Iter> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/par_bridge.rs:91:9
  49: <rayon::iter::map_with::MapWith<I,T,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/map_with.rs:53:9
  50: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<()> for ()>::from_par_iter
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/from_par_iter.rs:308:9
  51: rayon::iter::ParallelIterator::collect
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:2069:9
  52: rayon::iter::ParallelIterator::for_each_with
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.10.0/src/iter/mod.rs:417:33
  53: oxc_linter::service::LintService::run
             at ./oxc-main/crates/oxc_linter/src/service.rs:106:14
  54: <oxlint::lint::LintRunner as oxlint::runner::Runner>::run::{{closure}}
             at ./oxc-main/apps/oxlint/src/lint/mod.rs:157:17
  55: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/core/src/panic/unwind_safe.rs:272:9
  56: std::panicking::try::do_call
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:557:40
  57: std::panicking::try
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panicking.rs:520:19
  58: std::panic::catch_unwind
             at /rustc/363ae4188316b8b22cf6c1890bc73d84d05f70a4/library/std/src/panic.rs:348:14
  59: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  60: rayon_core::registry::Registry::catch_unwind
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:367:27
  61: rayon_core::spawn::spawn_job::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/spawn/mod.rs:97:13
  62: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:169:9
  63: rayon_core::job::JobRef::execute
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:64:9
  64: rayon_core::registry::WorkerThread::execute
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:860:13
  65: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:794:26
  66: rayon_core::registry::WorkerThread::wait_until
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:769:13
  67: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:818:9
  68: rayon_core::registry::main_loop
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:923:5
  69: rayon_core::registry::ThreadBuilder::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:53:18
  70: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:98:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/17143770/compressed.zip)

### PR DESCRIPTION
**Pull request by camc314**
closes #6068

### CODE REVIEW

**Comment by camc314** [comment]
* **#6070** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6070?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camc314 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
We seriously need to ban `chars().nth(i)` and `chars().enumerate()` ... ahhh

**Comment by camc314** [comment]
> We seriously need to ban `chars().nth(i)` and `chars().enumerate()` ... ahhh

too many foot guns 🙂

**Comment by Boshen** [comment]
I found many cases with `chars.enumerate()` and `chars().nth()`, let me create an issue.

**Pull request merged**
