### PR TITLE
feat(linter/oxc): add fixer for `erasing-op`

### PR DESCRIPTION
**Pull request by camc314**
adds a fixer for `erasing-op` (replace the binary expression with `0`)

### CODE REVIEW

**Comment by camc314** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5377?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5377** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5377?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5376** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5376?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camc314 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by DonIsaac** [comment]
While this is semantically equivalent, do you think it best fits the programmer's intent? And should it really be a fix instead of a suggestion?

**Comment by camc314** [comment]
> While this is semantically equivalent, do you think it best fits the programmer's intent? And should it really be a fix instead of a suggestion?

converted it to a suggestion

**Comment by DonIsaac** [comment]
CC: @mysteryven

**Comment by mysteryven** [comment]
> CC: mysteryven

I think I missed many things recently, I have some chores to do, now I'm house hunting and moving, I may back after Sep.18  :(

**Comment by DonIsaac** [comment]
> > CC: mysteryven
> 
> 
> 
> I think I missed many things recently, I have some chores to do, now I'm house hunting and moving, I may back after Sep.18  :(
> 
> 
> 
> 

That's so exciting! Best of luck!

**Pull request merged**
