### PR TITLE
fix: lex abstract as identifier in js

### PR DESCRIPTION
**Pull request by YangchenYe323**
`abstract` is a keyword in typescript but a valid identifier in javascript. Corrected the lexer.

### CODE REVIEW

**Comment by Boshen** [comment]
Thank you for the PR.

I think you have some misunderstandings about this. 

* `abstract` and friends are contextual keywords in TypeScript, `abstract = 1` is actually valid. 
* You never need to check if it's TypeScript in the lexer. Your change will actually kill performance.
* I normally cross reference babel and tsc for this kind of things

Sorry I have to close this PR since this is incorrect.

**Comment by YangchenYe323** [comment]
Thank you for your informative reply. Sorry for the wrong PR. I was playing around exactly with `abstract = 1` in typescript and found that oxc can't parse it so I assumed it's not valid. I did some digging and found the following code path is responsible: 
https://github.com/Boshen/oxc/blob/2cce71a7ebf3f610a21d0b09b4e621c62a2661e6/crates/oxc_parser/src/js/statement.rs#L89-L91
Would you like me to post another patch? Maybe changing it to `if self.at(Kind::Abstract) && self.peek_token().kind == Kind::Class`?

**Comment by Boshen** [comment]
That would be great! Let's try and see if it passes some of the ts errors by running `cargo coverage`

**Comment by Boshen** [comment]
If you want to make improvements to the code, you can try and port the `isStartOfDeclaration` part of `parseStatement` from typescript's parser.

**Pull request closed without merging**
