### PR TITLE
feat(semantic): report parameter related errors for setter/getter

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2316?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #2315** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2316** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2316?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2316?utm_source=stack-comment).

**Review by Boshen — COMMENTED** [review]
This is a javascript error with a missing case from 

https://github.com/oxc-project/oxc/blob/a762d17603f24b5d06d5052beec99f91d0d506b5/crates/oxc_parser/src/js/class.rs#L364-L380

I think it's easier to move these checks over to checker/javascript.js instead of keeping them in the parser?

**Comment by Dunqing** [comment]
> This is a javascript error with a missing case from
> 
> https://github.com/oxc-project/oxc/blob/a762d17603f24b5d06d5052beec99f91d0d506b5/crates/oxc_parser/src/js/class.rs#L364-L380
> 
> I think it's easier to move these checks over to checker/javascript.js instead of keeping them in the parser?

Yes, I will move the implementation to `checker/javascript.js`

**Comment by Boshen** [comment]
### Merge activity

* **Feb 5, 4:38 AM EST**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2316).

**Pull request merged**
