### PR TITLE
chore(deps): remove `static_assertions` dependency.

### PR DESCRIPTION
**Pull request by rzvxa**

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#4883** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4883?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by DonIsaac** [comment]
What advantage does `assert!` have over static assertions?

**Comment by Boshen** [comment]
> What advantage does `assert!` have over static assertions?

It's the same thing. We want less dependencies for the whole project hence the removal.

**Comment by overlookmotel** [comment]
@DonIsaac FYI `static_assertions` allows const assertions i.e. assertions which run at compile time rather than runtime.

But Rust's built-in `assert!` now supports this too.

```rs
// This will cause a compilation error
const _: () = assert!(1 + 1 == 3);
```

**Pull request merged**
