### PR TITLE
perf(semantic): allocate symbol data in Allocator

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
* **#8012** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/8012?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/8012?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=8012).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Boshen** [comment]
### Merge activity

* **Dec 20, 9:13 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Dec 20, 9:13 AM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

**Comment by overlookmotel** [comment]
@Boshen I think implementing `Send` on `Allocator` is perfectly safe. `bumpalo::Bump` implements `Send`, if I remember correctly.

But implementing `Sync` is definitely not safe, and likely a footgun (aka recipe for disaster).

I imagine `Send` is all that Rolldown needs?

**Comment by Boshen** [comment]
> @Boshen I think implementing `Send` on `Allocator` is perfectly safe. `bumpalo::Bump` implements `Send`, if I remember correctly.
> 
> But implementing `Sync` is definitely not safe, and likely a footgun (aka recipe for disaster).
> 
> I imagine `Send` is all that Rolldown needs?

```
error[E0277]: `Cell<NonNull<bumpalo::ChunkFooter>>` cannot be shared between threads safely
   --> crates/rolldown_plugin/src/plugin_context.rs:127:13
    |
127 |       .await?;
    |             ^ `Cell<NonNull<bumpalo::ChunkFooter>>` cannot be shared between threads safely
    |
    = help: within `oxc_allocator::Allocator`, the trait `Sync` is not implemented for `Cell<NonNull<bumpalo::ChunkFooter>>`, which is required by `Result<(), anyhow::Error>: FromResidual<Result<Infallible, tokio::sync::mpsc::error::SendError<ModuleLoaderMsg>>>`
    = note: if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock`
    = help: the trait `FromResidual<Result<Infallible, E>>` is implemented for `Result<T, F>`
note: required because it appears within the type `bumpalo::Bump`
   --> /Users/boshen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bumpalo-3.16.0/src/lib.rs:292:12
    |
292 | pub struct Bump {
    |            ^^^^
note: required because it appears within the type `oxc_allocator::Allocator`
   --> /Users/boshen/oxc/oxc/crates/oxc_allocator/src/lib.rs:71:12
    |
71  | pub struct Allocator {
    |            ^^^^^^^^^
    = note: required for `UnsafeSelfCell<SymbolTableCell, Allocator, SymbolTableInner<'static>>` to implement `Sync`
note: required because it appears within the type `oxc_semantic::symbol::SymbolTableCell`
   --> /Users/boshen/oxc/oxc/crates/oxc_semantic/src/symbol.rs:60:12
    |
60  |     struct SymbolTableCell {
    |            ^^^^^^^^^^^^^^^
note: required because it appears within the type `oxc_semantic::symbol::SymbolTable`
   --> /Users/boshen/oxc/oxc/crates/oxc_semantic/src/symbol.rs:21:12
    |
21  | pub struct SymbolTable {
    |            ^^^^^^^^^^^
note: required because it appears within the type `SymbolRefDbForModule`
   --> /Users/boshen/github/rolldown/crates/rolldown_common/src/types/symbol_ref_db.rs:37:12
    |
37  | pub struct SymbolRefDbForModule {
    |            ^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `RuntimeModuleTaskResult`
   --> /Users/boshen/github/rolldown/crates/rolldown_common/src/module_loader/runtime_task_result.rs:8:12
    |
8   | pub struct RuntimeModuleTaskResult {
    |            ^^^^^^^^^^^^^^^^^^^^^^^
note: required because it appears within the type `ModuleLoaderMsg`
   --> /Users/boshen/github/rolldown/crates/rolldown_common/src/module_loader/mod.rs:11:10
    |
11  | pub enum ModuleLoaderMsg {
    |          ^^^^^^^^^^^^^^^
note: required because it appears within the type `tokio::sync::mpsc::error::SendError<ModuleLoaderMsg>`
   --> /Users/boshen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/sync/mpsc/error.rs:8:12
    |
8   | pub struct SendError<T>(pub T);
    |            ^^^^^^^^^
    = note: required for `anyhow::Error` to implement `From<tokio::sync::mpsc::error::SendError<ModuleLoaderMsg>>`
    = note: required for `Result<(), anyhow::Error>` to implement `FromResidual<Result<Infallible, tokio::sync::mpsc::error::SendError<ModuleLoaderMsg>>>`
    = note: the full name for the type has been written to '/Users/boshen/github/rolldown/target/debug/deps/rolldown_plugin-966d208a591aeead.long-type-4702483371421541226.txt'
    = note: consider using `--verbose` to print the full type name to the console
```

**Comment by overlookmotel** [comment]
OK, well it's asking for trouble in my opinion! `Bump` is not thread-safe. You can *move* it from one thread to another no problem. But you can't safely share it between threads.

**Pull request merged**
