### PR TITLE
feat(linter): Implement `no-undef-init`

### PR DESCRIPTION
**Pull request by radu2147**
Related to https://github.com/oxc-project/oxc/issues/479

### CODE REVIEW

**Review by DonIsaac — COMMENTED** [review]
I have a feeling that we have a rule doing this already, but I'm not certain. @camc314 are you aware of this?

**Comment by radu2147** [comment]
There are `no-undefined` and `no-undef` rules as well but those are different from this one. Looked it up by the eslint name and didn't find any files that matched it

**Comment by camc314** [comment]
duplicate of `no-useless-undefined` ?

```

  × eslint(no-undefined): Disallow the use of `undefined` as an identifier
   ╭─[./test.js:1:9]
 1 │ let l = undefined;
   ·         ─────────
   ╰────
  help: Unexpected use of undefined.

  × eslint(no-unused-vars): Variable 'l' is declared but never used.
   ╭─[./test.js:1:5]
 1 │ let l = undefined;
   ·     ┬
   ·     ╰── 'l' is declared here
   ╰────
  help: Consider removing this declaration.

  × eslint-plugin-unicorn(no-useless-undefined): Do not use useless `undefined`.
   ╭─[./test.js:1:9]
 1 │ let l = undefined;
   ·         ─────────
   ╰────
  help: Consider removing `undefined` or using `null` instead.

Finished in 19ms on 1 file with 
```

**Comment by radu2147** [comment]
Yes, it seems that `no-useless-undefined` treats a more general case which involves this one as well. @camc314 should we mark the `no-undef-init` rule in linter product plan for eslint as done, in this case? 

Also I noticed that `no-lonely-if` is also done in unicorn

**Pull request closed without merging**
