### PR TITLE
feat(minifier): drop useless constructors

### PR DESCRIPTION
**Pull request by DonIsaac**
Drops useless constructor statements, like ones found by ESLint's [`no-useless-constructor`](https://eslint.org/docs/latest/rules/no-useless-constructor) rule. Derived from Closure Compiler's [`OptimizeCompilers`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/OptimizeConstructors.java)

## Todo
- [x] Drop `constructor() {}`
- [x] Drop `constructor(...args) { super(...args) }`
- [ ] Drop `constructor(a, b, c) { super(a, b, c) }`

### CODE REVIEW

**Comment by mysteryven** [comment]
It's a great PR, but I wonder why terser and [ESBuild](https://esbuild.github.io/try/#dAAwLjE4LjEzAC0tbWluaWZ5AGNsYXNzIEZvbyB7IGNvbnN0cnVjdG9yKCkgeyB9IH0) not drop it. 🤔

Terser:

```js
// before
class Foo { constructor() { } }
console.log(Foo)

// after
console.log(class{constructor(){}});
```

google-closure-compiler: 
```js
// before
class Foo { constructor() { } }
// after
class Foo{constructor(){}};
```

**Comment by Boshen** [comment]
> but I wonder why [terser](https://try.terser.org/), [google-closure-compiler](https://github.com/google/closure-compiler) and [ESBuild](https://esbuild.github.io/try/#dAAwLjE4LjEzAC0tbWluaWZ5AGNsYXNzIEZvbyB7IGNvbnN0cnVjdG9yKCkgeyB9IH0) not drop it.

Probably due to everyone shipping ES5 instead of ES6 to this day?

**Comment by DonIsaac** [comment]
> It's a great PR, but I wonder why [terser](https://try.terser.org/), [google-closure-compiler](https://github.com/google/closure-compiler) and [ESBuild](https://esbuild.github.io/try/#dAAwLjE4LjEzAC0tbWluaWZ5AGNsYXNzIEZvbyB7IGNvbnN0cnVjdG9yKCkgeyB9IH0) not drop it. 🤔 Are there some edge cases?
> 
> Terser:
> 
> ```js
> // before
> class Foo { constructor() { } }
> console.log(Foo)
> 
> // after
> console.log(class{constructor(){}});
> ```
> 
> google-closure-compiler:
> 
> ```js
> // before
> class Foo { constructor() { } }
> // after
> class Foo{constructor(){}};
> ```

Closure compiler does support this. I'm porting over [`OptimizeConstructors`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/OptimizeConstructors.java)

**Comment by Boshen** [comment]
> Closure compiler does support this. I'm porting over [OptimizeConstructors](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/OptimizeConstructors.java)

Sorry I didn't see this, but if you are porting a file, you need to setup the tests just like all the other closure compiler tests in `crates/oxc_minifier/tests/closure`
https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/OptimizeConstructorsTest.java

**Comment by DonIsaac** [comment]
> > Closure compiler does support this. I'm porting over [OptimizeConstructors](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/OptimizeConstructors.java)
> 
> Sorry I didn't see this, but if you are porting a file, you need to setup the tests just like all the other closure compiler tests in `crates/oxc_minifier/tests/closure` from https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/OptimizeConstructorsTest.java

Correct, I'm working on this now

**Pull request closed without merging**
