### PR TITLE
feat(ast): serialize StringLiterals to ESTree

### PR DESCRIPTION
**Pull request by ottomated**

### CODE REVIEW

**Comment by ottomated** [comment]
* **#7211** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7211?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ottomated and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ottomated** [comment]
@overlookmotel needs some work. There's a lot of places where string literals are constructed and don't have a `raw` value, and I'm not sure what to do there.

**Comment by overlookmotel** [comment]
Hmm, yes. Tricky. Let me think about that a little... am just catching up now after being away.

**Comment by overlookmotel** [comment]
Hmm, yes, tricky.

I've opened #7254 for the wider problem of these `raw` fields.

I now realize my suggestion to add a `raw` field to `StringLiteral` was unwise. Sorry.

I suggest for now just skip the `raw` field entirely in JSON AST, until we resolve #7254. If we decide to go the route of getting `raw` values via methods, we'll need a way to get the source text into the serializer. But, as we've discussed in #6347, we need to find a way to get external state into the serializer anyway, and we have a few options.

**Comment by overlookmotel** [comment]
Implemented in #7263 instead.

**Pull request closed without merging**
