### PR TITLE
feat(linter) eslint-plugin-react(no-is-mounted)

### PR DESCRIPTION
**Pull request by aminpaks**

### CODE REVIEW

**Review by Boshen — APPROVED** [review]
Thank you for your first contribution!

**Review by Boshen — CHANGES_REQUESTED** [review]
Need a quick `cargo fmt`.

By the way, the test in the plugin checks for `MethodDefinition`, by there are no accompany failure case for it 🤔 https://github.com/jsx-eslint/eslint-plugin-react/blob/9da1bb0f4aa44849b56e8c2064afd582ea8b36f8/lib/rules/no-is-mounted.js#L43-L50

**Comment by aminpaks** [comment]
@Boshen 

> Need a quick `cargo fmt`.
> 
> By the way, the test in the plugin checks for `MethodDefinition`, by there are no accompany failure case for it 🤔 https://github.com/jsx-eslint/eslint-plugin-react/blob/9da1bb0f4aa44849b56e8c2064afd582ea8b36f8/lib/rules/no-is-mounted.js#L43-L50

I think it's testing if any ancestors has a binding of `isMounted`:
```
var Hello = createReactClass({
        someFn: this.isMounted,
	componentDidUpdate: function() {
	if (this.someFn()) {
		return;
	}
	},
	render: function() {
	return <div>Hello</div>;
	}
});
```

I don't know how to achieve this in oxc parser. How do I walk the tree to the root?

**Comment by camc314** [comment]
to see how to access parent nodes, take a look at logic where we do:
```
ctx.nodes().parent_node(node.id()):
```

it returns an option of the parent node


e.g. here: we are walking up the tree, checking the kind of the parent 

https://github.com/web-infra-dev/oxc/blob/25247e3839afcb3fc1c0640e6bc49adf6d61f3ad/crates/oxc_linter/src/rules/react/jsx_key.rs#L74-L83

**Comment by aminpaks** [comment]
👋 @camc314  

Is [this](https://github.com/web-infra-dev/oxc/pull/1033/commits/d019003bb9e7c363225ad5f5079b2ae63899acef#diff-209bfc1d07cd91620a2ed8fadd2b9b1239b72fc5ce6946eeea4394ba1ee6ed3dR71-R82) how we're supposed to implement the ancestors' walk?
I'm not sure but I don't think it would pass in our case. Even when I looked at the ESLint AST I can't find any references to ["MethodDefinition" or "Property"](https://github.com/jsx-eslint/eslint-plugin-react/blob/9da1bb0f4aa44849b56e8c2064afd582ea8b36f8/lib/rules/no-is-mounted.js#L43-L50) in the tree 🤷

**Comment by Boshen** [comment]
> 👋 @camc314
> 
> Is [this](https://github.com/web-infra-dev/oxc/pull/1033/commits/d019003bb9e7c363225ad5f5079b2ae63899acef#diff-209bfc1d07cd91620a2ed8fadd2b9b1239b72fc5ce6946eeea4394ba1ee6ed3dR71-R82) how we're supposed to implement the ancestors' walk?

We also have the `ancestors` you may try for cleaner code. https://github.com/web-infra-dev/oxc/blob/2483e5cbf1776d025b6c8fea2fe5a170817555d0/crates/oxc_linter/src/rules/deepscan/bad_comparison_sequence.rs#L59-L74

> I'm not sure but I don't think it would pass in our case. Even when I looked at the ESLint AST I can't find any references to ["MethodDefinition" or "Property"](https://github.com/jsx-eslint/eslint-plugin-react/blob/9da1bb0f4aa44849b56e8c2064afd582ea8b36f8/lib/rules/no-is-mounted.js#L43-L50) in the tree 🤷

You can try our playground https://web-infra-dev.github.io/oxc/playground/

It seems to be `MethodDefinition` and `ObjectProperty` in our AST.

**Pull request closed without merging**
