### PR TITLE
fix(semantic): get_symbol_id_from_span not searching symbol redeclarations

### LINKED ISSUE #6689: Variable and Type declarations are merged into a single symbol in oxc_semantic
## Summary

A common pattern to define enum in TS is:
```ts
export const Foo = [
  'bar',
  'baz'
] as const;

export type Foo = typeof Foo[number];
```

There are 2 distinct declarations here with the same name, but oxc_semantic symbol table merges them into one. 

## Actual result

`const Foo` is recorded in the symbol table. But `type Foo` is entirely missing.
Instead the `const Foo` declaration gains a `TypeAlias` flag.

[OXC Playground](https://playground.oxc.rs/#eNpFjksOgzAMRK8SecOGE1B1yyWARaCmQkrsyAktFOXuJWpCV37jz3gOmKAB3BxLUBOTD6plVnfV9aRUNWqp6kyfqqdBaf9bu/XUU74Lu8N8lpDnJDpa7Ygy3KAGhuYAWSkVv1PQGzRBVqzBLBQK+4kdXmK3I5uigmjyM4uFZtbGY6zBafEop+PJyaXwtVoaEz/wien3KexCy7z8RxSETWv4naK9UEb2OUKM8QtSumPE)

```json
[
  {
    "name": "Foo",
    "span": {
      "start": 13,
      "end": 16
    },
    "nodeId": 4,
    "scopeId": 0,
    "flags": "BlockScopedVariable | ConstVariable | Export | TypeAlias",
    "references": [
      {
        "nodeId": 24,
        "flags": "Type"
      }
    ]
  }
]
```

## Expected result

`const Foo` and `type Foo` should be treated as 2 distinct symbols: the same way they would be if they were named differently.

[OXC Playground](https://playground.oxc.rs/#eNpFjjEOgzAMRa8SeWHhBKCunKAbMARqKqRgR05ooSh3b6ISOvl929/+B4xQAW6WxauRyXnVMKubajtSqhi0FOVJn6KjXmn3W6s76uj0+d1ist2jLzFPSbW0LgNKX0MJDNUBslIqbievN6i8rFiCmclndiNbvMS+DGyy8qLJTSwLVJM2DkMJVotDiRcjpyuZr9XcGPmBT0y/o1hmmqf5PyIvbBrD7xTthTKwOyOEEL6xGWQY)

```json
[
  {
    "name": "Foo",
    "span": {
      "start": 13,
      "end": 16
    },
    "nodeId": 4,
    "scopeId": 0,
    "flags": "BlockScopedVariable | ConstVariable | Export",
    "references": [
      {
        "nodeId": 24,
        "flags": "Type"
      }
    ]
  },
  {
    "name": "Foo",
    "span": {
      "start": 63,
      "end": 66
    },
    "nodeId": 19,
    "scopeId": 0,
    "flags": "Export | TypeAlias",
    "references": []
  }
]
```

This would also match what TypeScript does ([TS AST Viewer](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7wGIQnAvHAbQCg44ByAIwEMoyAaE86gLzKIF04rVEV0BuIkVCRYcGAE8wwOFhz5J0iADNZ2AsgCuAWwrAo7fkA))
ts-symbol-definition

### PR DESCRIPTION
**Pull request by valeneiko**
Fixes #6689

### CODE REVIEW

**Comment by Dunqing** [comment]
Are there any situations where we need to use this method?

The method looks a little complicated and not very efficient. I have checked our codebase only three places used this method and it looks like we can replace them.

To remove this method, we need to add `SymbolId` to` ModuleRecord`'s ImportEntry struct. Is it possible? @Boshen

**Comment by valeneiko** [comment]
@overlookmotel 
I am building a whole-program dependency graph between symbols E.g.:
- `const a = b+c;` - Symbol `a` depends on `b` and `c`
- `function foo() { return bar(); }` - Symbol `foo` depends on `bar`

I am doing it by iterating over symbol references, for each reference finding the ancestor declaration in root scope and resolving that declaration's AstNode into a Symbol. 

`get_symbol_id_from_span` only works with spans of names already. So I could just do `span.source_text(src)` and use `get_symbol_by_name`. Or if you know of a better way to do all this, I am open to suggestions.

For now the goal was to just explore what can be done with such a graph.


@Dunqing as for the perf of this specific PR. I think it is fine, because symbol redeclarations are rare, so in reality that whole method will most of the time be an empty iterator and occasionally iterate over very few items. As for the `get_symbol_id_from_span` itself, yes it could be improved, or removed if a better alternative exists.

**Comment by Dunqing** [comment]
@valeneiko Sorry for the response too late

Each reference has stored `symbol_id`, I don't think we need to get `symbol_id` by `span`.

**Comment by Dunqing** [comment]
> To remove this method, we need to add `SymbolId` to` ModuleRecord`'s ImportEntry struct. Is it possible? @Boshen

related to https://github.com/oxc-project/oxc/issues/5816#issue-2529431945

**Comment by valeneiko** [comment]
I'm happpy to close the PR. For my use case I instead used `semantic.scopes().get_root_binding(name)`, where `name` comes from `decl.id.name` (instead of previous `decl.id.span`)

**Comment by Dunqing** [comment]
> I'm happpy to close the PR. For my use case I instead used `semantic.scopes().get_root_binding(name)`, where `name` comes from `decl.id.name` (instead of previous `decl.id.span`)

Oh no! I think you should use `decl.id.symbol`!

**Comment by valeneiko** [comment]
Wow, that's even beter! Didn't realize this existed.

**Comment by Dunqing** [comment]
> Wow, that's even beter! Didn't realize this existed.

Very glad to help you! Closing as we are consider to remove the `get_symbol_id_from_span` method.

**Pull request closed without merging**
