### PR TITLE
feat(prettier/ts): better conformance

### PR DESCRIPTION
**Pull request by LIMPIX31**
I know 5% isn't much, but it's small steps like this that move us toward our goal.

### CODE REVIEW

**Review by Boshen — APPROVED** [review]

**Review by Boshen — APPROVED** [review]
Thank you!

**Comment by Boshen** [comment]
Prettier conformance test is failling :-(

**Comment by LIMPIX31** [comment]
> Prettier conformance test is failling :-(

I'm not quite sure why (

**Comment by Dunqing** [comment]
> > Prettier conformance test is failling :-(
> 
> I'm not quite sure why ( I thought that was to be expected.

Yes, it is expected, but you need to update the snap. Let's run `just coverage` in your local and push the changes.

**Review by Dunqing — APPROVED** [review]

**Pull request merged**
