### PR TITLE
refactor(ast_codegen): replace `///@@` with `///@@line_break`

### PR DESCRIPTION
**Pull request by overlookmotel**
Follow-on after #4778. `///@@line_break` is more verbose, but it's clearer what it does.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4786?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4786** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4786?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4785** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4785?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4784** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4784?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4782** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4782?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4781** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4781?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4779** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4779?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4778** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4778?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4777** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4777?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4775** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4775?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4774** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4774?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4773** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4773?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
It is really weird that the line break happens at the end😕 But I guess this one is a bit more clear.

**Comment by overlookmotel** [comment]
> It is really weird that the line break happens at the end😕

How do you mean "at the end"?

**Comment by rzvxa** [comment]
In the sense that it can't be a free-standing thing, It needs to come before an item so we can't have stuff at the end of a scope.

**Review by rzvxa — APPROVED** [review]

**Comment by overlookmotel** [comment]
> In the sense that it can't be a free-standing thing, It needs to come before an item so we can't have stuff at the end of a scope.

Ah I see. Yes it is a bit weird. Annoying that there seems to be no way to do something as simple as line breaks without all these odd workarounds.

**Pull request merged**
