### PR TITLE
refactor(linter): rename `is_same_reference` to `is_same_expression`

### PR DESCRIPTION
**Pull request by camc314**

### CODE REVIEW

**Comment by camc314** [comment]
* **#7654** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7654?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7654?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Boshen** [comment]
Can this be replaced by `ContentEqual`?

**Comment by Boshen** [comment]
### Merge activity

* **Dec 4, 11:07 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Comment by camc314** [comment]
> Can this be replaced by `ContentEqual`?
> 
> 
> 
> Edit: I replaced it with `left.content_eq(right)` but a bunch of tests failed. May need to replace it case by case :-(

yeah this one is a little looser than content_eq

**Pull request merged**
