### PR TITLE
feat(regular_expression): add terms visitor to pattern

### PR DESCRIPTION
**Pull request by camchenry**
To make it easier to iterate over the nodes in the regex AST, I attempted to add a pseudo-visitor method for patterns

### CODE REVIEW

**Comment by camchenry** [comment]
* **#5951** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5951?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camchenry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by leaysgur** [comment]
@DonIsaac I am not familiar with this area...! 😅 

Should these be handwritten? Or we need some updates for `tasks/ast_tools`?

**Comment by camchenry** [comment]
I feel like this might be the wrong implementation, but we probably do need some sort of regular expression AST visitor. I'm going to mark this as draft for now

**Comment by leaysgur** [comment]
> create a generic AST visitor that can visit every node type

I agree.

For the main `oxc_ast` ASTs, it seems adding `#[ast(visit)]` instructs `tasks/ast_tools` to automatically generate the `visit_` implementation (sorry, maybe I'm wrong).

However, I don't know the details of how it works or whether we should do the same here.

@Boshen Would you please help me to review? 🙏🏻

**Comment by Boshen** [comment]
We can always start with a manual one to test the water, and then migrate to ast_tools.

**Comment by leaysgur** [comment]
@camchenry If that's the case, I think there's no problem. 

Just 1 point, I think it would be nice to separate the file as `visit.rs` with comments referring to `ast_tools`.

**Comment by camchenry** [comment]
closing this in favor of https://github.com/oxc-project/oxc/pull/6055, which is the better implementation I think

**Pull request closed without merging**
