### PR TITLE
feat(linter/eslint-plugin-vitest): implement prefer-to-be-truthy

### PR DESCRIPTION
**Pull request by shulaoda**
Related to #4656

### CODE REVIEW

**Comment by shulaoda** [comment]
The difference in rules between `jest` and `vitest` is not significant, and I may be able to make simple modifications to `jest utilities` for unified use.

**Comment by mysteryven** [comment]
> The difference in rules between `jest` and `vitest` is not significant, and I may be able to make simple modifications to `jest utilities` for unified use.

Most of them are the same, simply modifying is preferred, even it may make the code ugly :(

**Comment by mysteryven** [comment]
Thank you! I am thinking whether we should move `parse_jest_fn_call` to `parse_test_fn_call`, and derive `parse_jest_fn_call` and `parse_vitest_fn_call` from it? Feel likes extends `expectTypeOf` in jest is a bit of a mess.

And need DonIsaac's review.👀

**Comment by shulaoda** [comment]
> Thank you! I am thinking whether we should move `parse_jest_fn_call` to `parse_test_fn_call`, and derive `parse_jest_fn_call` and `parse_vitest_fn_call` from it? Feel likes extends `expectTypeOf` in jest is a bit of a mess.


The current difference between them is too small. If necessary, I can implement it in the next related PR, which won't be too long.

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
LGTM, I'll let @mysteryven merge when he's happy with it.

**Comment by mysteryven** [comment]
> I can implement it in the next related PR

It didn't influence other jest rules currently, let's follow the current step and refactor it when needed :)

**Review by mysteryven — APPROVED** [review]
Thank you!

**Pull request merged**
