### PR TITLE
feat(transformer): Add babel-plugin-transform-dotall-regex

### PR DESCRIPTION
**Pull request by bschoenmaeckers**

### CODE REVIEW

**Comment by Dunqing** [comment]
I think we should [oxc-regex-parser](https://github.com/oxc-project/oxc/pull/2030) to implement this plugin, but the parser still working in progress

**Comment by Boshen** [comment]
Leave this to me.

**Comment by bschoenmaeckers** [comment]
> Leave this to me.

Do you mean you want to implement this plugin yourself (including the other regex plugins)?

**Comment by DonIsaac** [comment]
Closing this PR as it seems stale and unmergeable in its current state.

**Pull request closed without merging**
