### PR TITLE
chore(ci): generate `.generated_ast_watch_list.yml`

### LINKED ISSUE #4699: Generate CI filter for files included in `oxc_ast_codegen`
Generate what files are watched, It is currently manually written here:

https://github.com/oxc-project/oxc/blob/82e2f6b92466fa7f22858a1d55be49e9ab4556f4/.github/workflows/ci.yml#L277-L284

### PR DESCRIPTION
**Pull request by rzvxa**
closes #4699

I also did some reordering to the code so it is easier to follow.

### CODE REVIEW

**Comment by rzvxa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4737?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4737** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4737?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4735** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4735?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4732** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4732?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4731** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4731?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4728** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4728?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4730** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4730?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4729** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4729?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4726** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4726?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
Not reviewed in full yet, but a couple of quick things:

1. Is there a reason for `.` on start of `.generated_ast_watch_list.yml`? Can it be just `generated_ast_watch_list.yml`?
2. Could you add a line break on end of the file?

**Comment by rzvxa** [comment]
>     1. Is there a reason for `.` on start of `.generated_ast_watch_list.yml`? Can it be just `generated_ast_watch_list.yml`?

It is a preference thing, Since the file is generated and we wish to forget about it; Having it hidden might be better.
Now that we always keep the CI filter updated there is no need to worry about this file. Think of it like a socket file or named pipe, It is just an identifier to pass data to our CI on behalf of the codegen.

>     2. Could you add a line break on end of the file?

Sure, I don't like the trailing newline but that's just me.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
> > ```
> > 1. Is there a reason for `.` on start of `.generated_ast_watch_list.yml`? Can it be just `generated_ast_watch_list.yml`?
> > ```
> 
> It is a preference thing, Since the file is generated and we wish to forget about it; Having it hidden might be better. Now that we always keep the CI filter updated there is no need to worry about this file. Think of it like a socket file or named pipe, It is just an identifier to pass data to our CI on behalf of the codegen.

OK cool.

> > ```
> > 2. Could you add a line break on end of the file?
> > ```
> 
> Sure, ~I don't like the trailing newline but that's just me.~

It's a matter of taste, but it's the project's convention...

**Pull request merged**
