### PR TITLE
feat(semantic): add current_scope_flags function in SemanticBuilder

### PR DESCRIPTION
**Pull request by Dunqing**

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1906** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1906?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #1907** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1907?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1906?utm_source=stack-comment).

**Review by Boshen — COMMENTED** [review]
I'm going to deny this change, keeping multiple states is error prone, you can add a function instead.

The performance impact should be negligible.

**Review by Boshen — CHANGES_REQUESTED** [review]
You may add a `fn current_scope_flags()` instead.

**Comment by Dunqing** [comment]
> You may add a `fn current_scope_flags()` instead.

Sounds good

**Review by Boshen — APPROVED** [review]

**Comment by Boshen** [comment]
### Merge activity

* **Jan 5, 11:51 PM**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1906).

**Pull request merged**
