### PR TITLE
perf(transformer): store needed options only on `RegExp`

### PR DESCRIPTION
**Pull request by overlookmotel**
#5482 makes most of the `RegExpOptions` not be needed outside `new` method. So only store the remaining options which are actually needed on `RegExp`. This reduces size of `RegExp`.

(this is micro-optimization, and unlikely to make a measurable difference, but why not?)

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5484?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5484** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5484?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5483** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5482** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Dunqing — APPROVED** [review]

**Comment by overlookmotel** [comment]
bench

That's *really* surprising!

Maybe we should try the same on other transforms.

**Comment by Dunqing** [comment]
> bench
> 
> 
> 
> That's *really* surprising!
> 
> 
> 
> Maybe we should try the same on other transforms.
> 

This is not a micro-optimazation

**Comment by overlookmotel** [comment]
Actually, I think maybe CodSpeed is giving a misleading result. I think this perf gain was actually due to the previous PR #5483.

**Pull request merged**
