### PR TITLE
refactor(prettier): Refactor IR related macros

### PR DESCRIPTION
**Pull request by leaysgur**
- Remove `format!` macro
- Rename string related macros, `&'static`: `text!` and `'a`: `dynamic_text!`
- Apply `wrap!` macro instead of manually using `enter|leave_node`
- Introduce `/ir` directory and move `Doc`, `impl Display`, `DocBuilder`, etc.

I'm not yet determined how to, how deep to use macro, but this is first stepping stone... 🥌

### CODE REVIEW

**Comment by leaysgur** [comment]
> free to make any changes to the oxc_prettier crate.

@Boshen Can I understand this to mean that I can merge PRs without review?

**Comment by Boshen** [comment]
> how deep to use macro

Although I ban macros in the rest of the codebase, I allow in this crate to make code easier to read.

So the general guideline is:

* make the formatter functions easier to read by making everything shorter and more concise.
* save some key strokes

**Comment by Boshen** [comment]
> > free to make any changes to the oxc_prettier crate.
> > [#5068 (comment)](https://github.com/oxc-project/oxc/issues/5068#issuecomment-2496593075)
> 
> @Boshen Can I understand this to mean that I can merge PRs without review?

Or use graphite to stack the PRs, whatever makes you productive. I can review after merge.

**Comment by Boshen** [comment]
### Merge activity

* **Nov 26, 4:27 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

**Pull request merged**
