### PR TITLE
chore(prettier): Update conformance tests to Prettier v3.3.3

### PR DESCRIPTION
**Pull request by leaysgur**
- v3.3.3 is latest released version
- Test file name was changed from v3.3.x
  - https://github.com/prettier/prettier/pull/16244

### CODE REVIEW

**Comment by Boshen** [comment]
It's hitting a infinite loop somewhere 😢

**Comment by leaysgur** [comment]
😭 

Submodule is not updated correctly?

image

This hash is for

https://github.com/prettier/prettier/commit/7142cf354cce2558f41574f44b967baf11d5b603

We expect for v3.3.3

https://github.com/prettier/prettier/commit/52829385bcc4d785e58ae2602c0b098a643523c9

I know that this task hangs if the target file cannot be found.

**Comment by leaysgur** [comment]
Now I learned CI does not use `just submodules`. 🕵🏻

**Comment by Boshen** [comment]
> Now I learned CI does not use `just submodules`. 🕵🏻

This is not nice, let me change it.

**Comment by Boshen** [comment]
> > Now I learned CI does not use `just submodules`. 🕵🏻
> 
> This is not nice, let me change it.

Oh wait, I tried it before but got stuck with git credentials in CI :-/

**Pull request merged**
