### PR TITLE
feat(rulegen): skip the test case when it has a languageOption and only has the ecmaVersion option

### LINKED ISSUE #3366: new-rule for eslint doesn't handle `languageOptions`
I was a bit confused after having run `new-rule` and valid test cases error'ing out as languageOptions are not respected when generating a new rule.

For example:
```
{ code: "globalThis.Math.pow(a, b)", languageOptions: { ecmaVersion: 2019 } },
```

https://github.com/eslint/eslint/blob/main/tests/lib/rules/prefer-exponentiation-operator.js#L73

### PR DESCRIPTION
**Pull request by Dunqing**
close: #3366

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#3382** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3382?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Boshen — COMMENTED** [review]
We skip because the code will end up being exactly the same?

What happens if there two snippets with the same code, and they both have `ecmaVersion`, do we end up removing both?

**Comment by Dunqing** [comment]
> We skip because the code will end up being exactly the same?
> 

We don't need to care about these test cases. These test cases are mainly for checking unsupported syntax.

https://github.com/eslint/eslint/blob/main/tests/lib/rules/prefer-exponentiation-operator.js#L73
> What happens if there two snippets with the same code, and they both have `ecmaVersion`, do we end up removing both?

Yes.

**Comment by Dunqing** [comment]
I'll look later at other rules that use the `ecmaVersion` and what they are doing to make sure we're removing really useless test cases

**Comment by Dunqing** [comment]
I have checked [no-eval](https://github.com/eslint/eslint/blob/389744be255717c507fafc158746e579ac08d77e/tests/lib/rules/no-eval.js) rule. There are some tests that only have the `ecmaVersion` option, but the behavior of their test code is different, so we can't remove them

**Pull request closed without merging**
