### PR TITLE
fix(linter): block in eslint/no_cond_assign

### LINKED ISSUE #4687: Rule `no-cond-assign` misbehaves with `always` option
- version: oxlint@0.7.0
- my config:  
```json
{
    "rules": {
        "no-cond-assign": ["error", "always"]
    }
}
```

image

- expects: https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3Qgb2JqID0ge1xuICAgIGtleTogdHJ1ZSxcbn07XG5pZiAob2JqLmtleSkge1xuICAgIChvYmoua2V5ID0gZmFsc2UpXG59XG4iLCJvcHRpb25zIjp7InJ1bGVzIjp7Im5vLWNvbmQtYXNzaWduIjpbImVycm9yIiwiYWx3YXlzIl19LCJsYW5ndWFnZU9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==

### PR DESCRIPTION
**Pull request by heygsc**
fix: #4687

### CODE REVIEW

**Comment by Boshen** [comment]
Try `just ready` before pushing, it'll run the same CI tasks.

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
Nice find!

**Comment by heygsc** [comment]
> Try `just ready` before pushing, it'll run the same CI tasks locally.

Thank you for reminding me. I just tried binstall/rust ready and it's great.

**Comment by heygsc** [comment]
> Nice find!

Thank you!

**Pull request merged**
