### PR TITLE
feat(Codegen): Improve codegen

### PR DESCRIPTION
**Pull request by andymac4182**
This gets all the new TS types working to the same level TS output was before and fixes a bunch of other codegen

### CODE REVIEW

**Review by Boshen — COMMENTED** [review]
Everything seems good except the part where we imported `oxc_parser`, we can move the relevant functions to the `oxc_syntax` crate instead.

**Comment by andymac4182** [comment]
Are you happy for me to move the Enum to that crate?

**Comment by Boshen** [comment]
> Are you happy for me to move the Enum to that crate or will you do that?

I'll move it on top of your PR.

**Comment by andymac4182** [comment]
Thanks for all your help with this work :) It has been great to work on :)

**Comment by Boshen** [comment]
Thank you so much for working on this!

**Pull request merged**
