### PR TITLE
chore: remove oncecell dep

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
1. Remove the dependency of `once_cell`

### CODE REVIEW

**Comment by Boshen** [comment]
This raises our msrv (minimal supported rust version) to v1.80.0, which isn't nice for crate consumers :-(

**Comment by IWANABETHATGUY** [comment]
> This raises our msrv (minimal supported rust version) to v1.80.0, which isn't nice for crate consumers :-(

I see

**Comment by rzvxa** [comment]
> This raises our msrv (minimal supported rust version) to v1.80.0, which isn't nice for crate consumers :-(

We already have msrv of 1.80.0, take a look at this:
https://discord.com/channels/1079625926024900739/1117322804291964931/1272270360263266367

**Comment by rzvxa** [comment]
> This raises our msrv (minimal supported rust version) to v1.80.0, which isn't nice for crate consumers :-(

We already have msrv of 1.80.0, take a look at this:
https://discord.com/channels/1079625926024900739/1117322804291964931/1272270360263266367

**Pull request closed without merging**
