### PR TITLE
fix(ci): transform conformance do not skip any errors

### PR DESCRIPTION
**Pull request by overlookmotel**
Snapshots generated by transform conformance were missing a few errors (e.g. `declarations/const-enum/input.ts` at bottom of diff). Make sure all errors fail the test.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#5134** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5134?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@Boshen This definitely reveals at least 1 genuine error that was previously hidden. I'm unsure if the many `preset-env: unknown field 'corejs'` errors should be considered test fails or not. Can you advise?

**Comment by overlookmotel** [comment]
Ah, I wasn't sure if this was ready to merge. @Boshen can you advise:

1. Are the `preset-env: unknown field 'corejs'` errors meant to be test failures or not?

2. Should the 2 x `TS(18010): An accessibility modifier cannot be used with a private` errors be considered failures? These errors seem to come from the parser, but it doesn't stop the transform transforming them correctly.

Perhaps we shouldn't add parser errors to `actual_errors` unless they cause a complete parsing failure (i.e. `program.body.is_empty()`)?

**Comment by Boshen** [comment]
> Should the 2 x TS(18010): An accessibility modifier cannot be used with a private errors be considered failures?

Babel is not conforming to tsc.

> Are the preset-env: unknown field 'corejs' errors meant to be test failures or not?

I'll fix these.

**Pull request merged**
