### PR TITLE
fix(napi/transform)!: remove unused `declaration.sourcemap` option

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7013?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7013** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7013?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7012** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7012?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Boshen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Dunqing** [comment]
Shouldn't we support this? See https://github.com/oxc-project/oxc/issues/4313

**Comment by Boshen** [comment]
> Shouldn't we support this? See #4313

This is on the declaration api, not the transform.typescript.declaration api

I'll take a look at the APIs later.

**Comment by Dunqing** [comment]
> > Shouldn't we support this? See #4313
> 
> This is on the declaration api, not the transform.typescript.declaration api
> 
> I'll take a look at the APIs later.

Oh, yes, you are right! Feel free to continue merging

**Pull request closed without merging**
