### PR TITLE
feat(minifier): fold bigint operation

### PR DESCRIPTION
**Pull request by 7086cmd**

### CODE REVIEW

**Comment by 7086cmd** [comment]
* **#6414** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6414?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @7086cmd and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
> ## [CodSpeed Performance Report](https://codspeed.io/oxc-project/oxc/branches/10-10-feat_minifier_fold_bigint_operation)
> ### Merging #6414 will **degrade performances by 3.22%**
> Comparing `10-10-feat_minifier_fold_bigint_operation` (154a285) with `main` (a1a2721)
> 
> ### Summary
> `❌ 1` regressions `✅ 28` untouched benchmarks
> 
> > ⚠️ _Please fix the performance issues or [acknowledge them on CodSpeed](https://codspeed.io/oxc-project/oxc/branches/10-10-feat_minifier_fold_bigint_operation)._
> 
> ### Benchmarks breakdown
> Benchmark	`main`	`10-10-feat_minifier_fold_bigint_operation`	Change
> ❌	`minifier[react.development.js]`	2.5 ms	2.6 ms	-3.22%

This is not good :-(

**Comment by 7086cmd** [comment]
> This is not good :-(

Yes, and I am currently assessing the factors that influence the performance.

**Comment by 7086cmd** [comment]
Seeking for another solution.

**Pull request closed without merging**
