### PR TITLE
add icon file for vscode extension (#1134)

### LINKED ISSUE #1134: Failed to build `oxc_lsp.vsix` (The specified icon 'extension/icon.png' wasn't found in the extension.)
Thank you for the wonderful project!
I wanted to contribute to this project and encountered a problem while setting up the environment, so I'd like to share it.

# Problem
While trying to generate oxc_lsp.vsix by executing pnpm run package in editor/vscode, the following error occurred and failed.

The specified icon 'extension/icon.png' wasn't found in the extension.

It seemed that without the icon file set for the extension, it was not possible to generate oxc_lsp.vsix.

# Solution
The issue was resolved by creating a new file at editor/vscode/icon.png. The existence of the file was crucial, and its content did not seem to matter. (In fact, I created an empty file, but I was able to generate oxc_lsp.vsix successfully.)

# Environment

Node.js: v20.9.0
pnpm: v8.9.0
vsce: 2.22.0

### PR DESCRIPTION
**Pull request by ubugeeei**
Closes #1134 

I'm not sure if it's the correct solution, but I solved it this way, so I'll submit a PR. As for the icon, I took it from the marketplace.

https://marketplace.visualstudio.com/items?itemName=oxc.oxc-vscode

### CODE REVIEW

**Comment by Boshen** [comment]
It's bad to commit big binary files into git. I was planning to add a small initialize script that downloads this file but didn't have the time to do so.

**Comment by Ubugeeei** [comment]
I see, so that was the situation.
I can create a commit to address this issue, but which direction would be best?

There are a few methods:

- Place an empty file instead of an image file.
- Write a script to download the image file.
- Ignore it from git and mention in the contribution guide to create the file.


If we are to download an image, from where should we download it?

**Comment by Ubugeeei** [comment]
@Boshen 
For the time being, in this PR, I've excluded the icon file from git tracking and added a step to create the file during the development environment setup.
If there's a better approach, please don't hesitate to suggest it.

**Comment by Boshen** [comment]
> @Boshen For the time being, in this PR, I've excluded the icon file from git tracking and added a step to create the file during the development environment setup. If there's a better approach, please don't hesitate to suggest it.

Let's a simple `wget https://github.com/Boshen/oxc-assets/blob/main/logo-square.png`

All the assets are in https://github.com/Boshen/oxc-assets

Sorry for the delay as I was busy with some other stuff.
And thank you for mentioning oxc on twitter!

**Comment by Ubugeeei** [comment]
@Boshen 

The project was so impressive that I couldn't help but mention it!
Please don't worry about the delayed response.
I'm truly grateful for your assistance amidst your busy schedule.

---

I tried setting it up to download using wget during preinstall, based on the link you provided.
Since it's excluded from git's tracking, there are also changes in the .gitignore.

**Comment by Boshen** [comment]
Thank you!

**Pull request merged**
