### PR TITLE
feat(transformer): react jsx transform

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
* **#2961** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2961?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Boshen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Dunqing — APPROVED** [review]
Is this copied from a previous implementation?

**Comment by Boshen** [comment]
### Merge activity

* **Apr 13, 10:50 PM EDT**: @Boshen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2961).

**Comment by Boshen** [comment]
> Is this copied from a previous implementation?

Yes, I adjusted some lines to cut the total number of lines down 😅

**Pull request merged**
