### PR TITLE
refactor(ast_codegen): use doc comments instead of `endl!`

### PR DESCRIPTION
**Pull request by overlookmotel**
Similar to #4777.

Use `///@@` instead of `endl!();` in AST codegen to create line breaks.

NB: `///@@` needs to be before an item, not after it.

### CODE REVIEW

**Comment by overlookmotel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4778?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4778** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4778?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4777** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4777?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4775** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4775?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4774** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4774?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4773** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4773?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rzvxa** [comment]
> @rzvxa I'm less sure about this one than #4777.
> 
> Reasons I prefer `///@@` to `endl!()`:
> 
>     * Because it's a comment, it's clearer that it's incidental and not part of the output code.
> 
>     * VS Code colours the comments in green, so the code is more broken up visually, which makes it easier to read.
> 
> 
> What I don't like:
> 
>     * What the fuck does `///@@` mean?!
> 
> 
> On balance I do prefer `///@@`, but what do you think? Would it be clearer if it was `///@@<line break>`? Or are you completely opposed?

I'll let you decide on this one, As long as we can generate the same output it doesn't matter.

**Comment by overlookmotel** [comment]
We *could* make our own proc macro which wraps `quote!` and figures out where line breaks are from the spans of tokens, and inserts `endl!();` for us in those places. So then we could just write the code normally and avoid all this nonsense. But it seems like overkill to me to have a proc macro purely for use in the codegen.

**Comment by overlookmotel** [comment]
OK, thanks. I'm going to merge it. Might go back and change it `///@@<line break>` later on.

**Pull request merged**
