### PR TITLE
feat(linter): support partial selectors in `eslint/no-restricted-syntax`

### PR DESCRIPTION
**Pull request by mysteryven**
In this version, we firstly support selectors in [Vue's ESlint config file](https://github.com/vuejs/core/blame/main/eslint.config.js#L28-L48), it needs more exploration to find a more universal approach.

### CODE REVIEW

**Comment by mysteryven** [comment]
* **#3419** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3419?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mysteryven and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
It feels like we should add a specific oxc rule for this 🤔 

* no-spread-args `https://github.com/eslint/eslint/issues/16407`
* [prefer-object-spread](https://eslint.org/docs/latest/rules/prefer-object-spread) -> `no-object-spread`?

**Comment by mysteryven** [comment]
Found there also a [`no-const-enum`](https://biomejs.dev/linter/rules/no-const-enum/), looks also like valuable.

But thereafter, where the proper position for `AwaitExpression` 🤔

**Comment by Boshen** [comment]
> Found there also a [`no-const-enum`](https://biomejs.dev/linter/rules/no-const-enum/), looks also like valuable.
> 
> But thereafter, where the proper position for `AwaitExpression` 👀

I found 

* https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-async-await.md
* https://github.com/brendenpalmer/eslint-plugin-disable-features/blob/master/docs/rules/disable-async-await.md

**Pull request closed without merging**
