### PR TITLE
feat(traverse): `CombinedTraverse` type to compose `Traverse`s

### PR DESCRIPTION
**Pull request by overlookmotel**
Implements the `CombinedTraverse` type discussed in https://github.com/oxc-project/oxc/pull/3216#issuecomment-2103070633. This type and the accompanying `combine_traverses!` macro allow composing multiple traverses/transforms with minimal boilerplate.

I am actually not sure if this is a good idea or not. The API is nice I think, but it may blow up compile times.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#3219** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3219?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Dunqing** [comment]
Can we combine multiple Traversers ( >2 )?

**Comment by overlookmotel** [comment]
> Can we combine multiple Traversers ( >2 )?

Yes!

```rs
let all_five = combine_traverses!(
    MyTraverse1::new(),
    MyTraverse2::new(),
    MyTraverse3::new(),
    MyTraverse4::new(),
    MyTraverse5::new(), 
);
```

https://github.com/oxc-project/oxc/blob/2ff2eb883ca485ef1895b3a142d69ac307e8d5f8/crates/oxc_traverse/src/lib.rs#L210-L287

**Comment by Boshen** [comment]
Crazy! Let's hop on a call every time we gonna add 3000 lines of code 😛

**Comment by overlookmotel** [comment]
> Crazy!

Can I take that as "no way we're going to merge this nonsense"?

Well I did say "I am actually not sure if this is a good idea". It's just responding to Dunqing's request for a less verbose API in #3216.

And the joy of codegens is you can generate 3000 lines of code in about 20 mins! 😆

**Comment by Boshen** [comment]
Let's refine the infra once all tests passes so we have the whole picture of the current infra.

**Pull request closed without merging**
