### PR TITLE
docs(parser): share `oxc_parser` module docs with `oxc::parser`

### PR DESCRIPTION
**Pull request by DonIsaac**
# What This PR Does

Moves `oxc_parser` module documentation to a README.md file so that the
`oxc` crate can benefit from it as well.

The downside of this PR is that it breaks example inclusion with
`#![doc include_str(..)]`, since macros in loaded files are not run. I'm
not 100% sure that the tradeoffs are worth it, but this is worth
discussing.

### CODE REVIEW

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5832?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5832** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5831** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5831?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
> since macros in loaded files are not run

Did you mean *examples* in loaded files are not run?

**Comment by DonIsaac** [comment]
> > since macros in loaded files are not run
> 
> Did you mean _examples_ in loaded files are not run?

I did not.

Given this README:
```md
Here's a description for some stuff 

## Example
'''rust
#![doc = include_str!("../examples/foo.rs")]
'''
```
> note: using single quotes instead of backticks above as to not break formatting of this comment

When this gets loaded in as documentation in `lib.rs`
```rust
#![doc = include_str!("../README.md")]
```
then the macro invocation in `README.md` (`include_str!("../examples/foo.rs")`) wiil not be invoked, and will instead be displayed as-is.

**Comment by overlookmotel** [comment]
Ah. Now I understand. Thanks for explaining.

**Comment by Boshen** [comment]
This seems confusing, maybe just a docs.rs link to the actual crate should suffice?

**Pull request closed without merging**
