### PR TITLE
fix(ast): visit `Program`s `hashbang` field first

### PR DESCRIPTION
**Pull request by overlookmotel**
Visit `hashbang` before `directives` for `Program`.

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#4368** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4368?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@Dunqing This makes sense, right?

**Comment by Dunqing** [comment]
SemanticBuilder’s `visit_program` missing visit `hashbang`. Do you mind adding it to this PR?

**Comment by overlookmotel** [comment]
> SemanticBuilder’s `visit_program` missing visit `hashbang`. Do you mind adding it to this PR?

I thought that was intentional, because `SemanticBuilder` doesn't do anything with it anyway.

**Comment by Dunqing** [comment]
> > SemanticBuilder’s `visit_program` missing visit `hashbang`. Do you mind adding it to this PR?
> 
> I thought that was intentional, because `SemanticBuilder` doesn't do anything with it anyway. But yeah, I see it's needed for #4367. I'll do it in a separate PR.

Thanks. Yes. I thought too.

**Review by Dunqing — APPROVED** [review]

**Pull request merged**
